#
# Makefile - Omni-Path IB verbs driver
# Copyright(c) 2015, Intel Corporation.
#
ccflags-y += -I $(src)/../common
ccflags-y += -I $(src)/../common/uapi
obj-m += opa2_ib.o

opa2_ib-y :=
opa2_ib-y += cq.o
opa2_ib-y += dma.o
opa2_ib-y += mad.o
opa2_ib-y += mmap.o
opa2_ib-y += mr.o
opa2_ib-y += pd.o
opa2_ib-y += qp.o
opa2_ib-y += rdma.o
opa2_ib-y += rc.o
opa2_ib-y += ruc.o
opa2_ib-y += uc.o
opa2_ib-y += ud.o
opa2_ib-y += verbs.o
opa2_ib-y += fxr.o
