/*
* Autogenerated by i_csrs.pl on Mon Jan 13 07:02:50 2014
* 
* i_csrs.pl Version 1.4 last modified on Wednesday 1/8/14 13:42:49.
*/

#ifndef DEF_WFR_CCE_SW_STRUCT
#define DEF_WFR_CCE_SW_STRUCT

/*
*  Stuctures and Unions from Tables
*/

#endif 		/* DEF_WFR_CCE_SW_STRUCT */
