// SPDX-License-Identifier: GPL-2.0
/*
 * Intel Ice Lake PCH pinctrl/GPIO driver
 *
 * Copyright (C) 2019, Intel Corporation
 * Author: Andy Shevchenko <andriy.shevchenko@linux.intel.com>
 */

#include <linux/mod_devicetable.h>
#include <linux/module.h>
#include <linux/platform_device.h>

#include <linux/pinctrl/pinctrl.h>

#include "pinctrl-intel.h"

#define ICL_PAD_OWN	0x020
#define ICL_PADCFGLOCK	0x080
#define ICL_HOSTSW_OWN	0x0b0
#define ICL_GPI_IS	0x100
#define ICL_GPI_IE	0x120

#define ICL_GPP(r, s, e)				\
	{						\
		.reg_num = (r),				\
		.base = (s),				\
		.size = ((e) - (s) + 1),		\
	}

#define ICL_COMMUNITY(b, s, e, g)			\
	{						\
		.barno = (b),				\
		.padown_offset = ICL_PAD_OWN,		\
		.padcfglock_offset = ICL_PADCFGLOCK,	\
		.hostown_offset = ICL_HOSTSW_OWN,	\
		.is_offset = ICL_GPI_IS,		\
		.ie_offset = ICL_GPI_IE,		\
		.pin_base = (s),			\
		.npins = ((e) - (s) + 1),		\
		.gpps = (g),				\
		.ngpps = ARRAY_SIZE(g),			\
	}

/* Ice Lake-N */
static const struct pinctrl_pin_desc icln_pins[] = {
	/* GPP_B */
	PINCTRL_PIN(0, "CORE_VID_0"),
	PINCTRL_PIN(1, "CORE_VID_1"),
	PINCTRL_PIN(2, "VRALERTB"),
	PINCTRL_PIN(3, "CPU_GP_2"),
	PINCTRL_PIN(4, "CPU_GP_3"),
	PINCTRL_PIN(5, "SRCCLKREQB_0"),
	PINCTRL_PIN(6, "SRCCLKREQB_1"),
	PINCTRL_PIN(7, "SRCCLKREQB_2"),
	PINCTRL_PIN(8, "SRCCLKREQB_3"),
	PINCTRL_PIN(9, "SRCCLKREQB_4"),
	PINCTRL_PIN(10, "SRCCLKREQB_5"),
	PINCTRL_PIN(11, "PMCALERTB"),
	PINCTRL_PIN(12, "SLP_S0B"),
	PINCTRL_PIN(13, "PLTRSTB"),
	PINCTRL_PIN(14, "SPKR"),
	PINCTRL_PIN(15, "GSPI0_CS0B"),
	PINCTRL_PIN(16, "GSPI0_CLK"),
	PINCTRL_PIN(17, "GSPI0_MISO"),
	PINCTRL_PIN(18, "GSPI0_MOSI"),
	PINCTRL_PIN(19, "GSPI1_CS0B"),
	PINCTRL_PIN(20, "GSPI1_CLK"),
	PINCTRL_PIN(21, "GSPI1_MISO"),
	PINCTRL_PIN(22, "GSPI1_MOSI"),
	PINCTRL_PIN(23, "GSPI1_CS1B"),
	PINCTRL_PIN(24, "GSPI0_CLK_LOOPBK"),
	PINCTRL_PIN(25, "GSPI1_CLK_LOOPBK"),
	/* GPP_A */
	PINCTRL_PIN(26, "ESPI_IO_0"),
	PINCTRL_PIN(27, "ESPI_IO_1"),
	PINCTRL_PIN(28, "ESPI_IO_2"),
	PINCTRL_PIN(29, "ESPI_IO_3"),
	PINCTRL_PIN(30, "ESPI_CSB"),
	PINCTRL_PIN(31, "ESPI_CLK"),
	PINCTRL_PIN(32, "ESPI_RESETB"),
	PINCTRL_PIN(33, "SMBCLK"),
	PINCTRL_PIN(34, "SMBDATA"),
	PINCTRL_PIN(35, "SMBALERTB"),
	PINCTRL_PIN(36, "CPU_GP_0"),
	PINCTRL_PIN(37, "CPU_GP_1"),
	PINCTRL_PIN(38, "USB2_OCB_1"),
	PINCTRL_PIN(39, "USB2_OCB_2"),
	PINCTRL_PIN(40, "USB2_OCB_3"),
	PINCTRL_PIN(41, "DDSP_HPD_A"),
	PINCTRL_PIN(42, "DDSP_HPD_B"),
	PINCTRL_PIN(43, "DDSP_HPD_C"),
	PINCTRL_PIN(44, "USB2_OCB_0"),
	PINCTRL_PIN(45, "PCHHOTB"),
	PINCTRL_PIN(46, "ESPI_CLK_LOOPBK"),
	/* GPP_S */
	PINCTRL_PIN(47, "SNDW1_CLK"),
	PINCTRL_PIN(48, "SNDW1_DATA"),
	PINCTRL_PIN(49, "SNDW2_CLK"),
	PINCTRL_PIN(50, "SNDW2_DATA"),
	PINCTRL_PIN(51, "SNDW1_CLK"),
	PINCTRL_PIN(52, "SNDW1_DATA"),
	PINCTRL_PIN(53, "SNDW4_CLK_DMIC_CLK_0"),
	PINCTRL_PIN(54, "SNDW4_DATA_DMIC_DATA_0"),
	/* GPP_R */
	PINCTRL_PIN(55, "HDA_BCLK"),
	PINCTRL_PIN(56, "HDA_SYNC"),
	PINCTRL_PIN(57, "HDA_SDO"),
	PINCTRL_PIN(58, "HDA_SDI_0"),
	PINCTRL_PIN(59, "HDA_RSTB"),
	PINCTRL_PIN(60, "HDA_SDI_1"),
	PINCTRL_PIN(61, "I2S1_SFRM"),
	PINCTRL_PIN(62, "I2S1_TXD"),
	/* GPP_H */
	PINCTRL_PIN(63, "GPPC_H_0"),
	PINCTRL_PIN(64, "SD_PWR_EN_B"),
	PINCTRL_PIN(65, "MODEM_CLKREQ"),
	PINCTRL_PIN(66, "SX_EXIT_HOLDOFFB"),
	PINCTRL_PIN(67, "I2C2_SDA"),
	PINCTRL_PIN(68, "I2C2_SCL"),
	PINCTRL_PIN(69, "I2C3_SDA"),
	PINCTRL_PIN(70, "I2C3_SCL"),
	PINCTRL_PIN(71, "I2C4_SDA"),
	PINCTRL_PIN(72, "I2C4_SCL"),
	PINCTRL_PIN(73, "CPU_VCCIO_PWR_GATEB"),
	PINCTRL_PIN(74, "I2S2_SCLK"),
	PINCTRL_PIN(75, "I2S2_SFRM"),
	PINCTRL_PIN(76, "I2S2_TXD"),
	PINCTRL_PIN(77, "I2S2_RXD"),
	PINCTRL_PIN(78, "I2S1_SCLK"),
	PINCTRL_PIN(79, "GPPC_H_16"),
	PINCTRL_PIN(80, "GPPC_H_17"),
	PINCTRL_PIN(81, "GPPC_H_18"),
	PINCTRL_PIN(82, "GPPC_H_19"),
	PINCTRL_PIN(83, "GPPC_H_20"),
	PINCTRL_PIN(84, "GPPC_H_21"),
	PINCTRL_PIN(85, "GPPC_H_22"),
	PINCTRL_PIN(86, "GPPC_H_23"),
	/* GPP_D */
	PINCTRL_PIN(87, "SPI1_CSB"),
	PINCTRL_PIN(88, "SPI1_CLK"),
	PINCTRL_PIN(89, "SPI1_MISO_IO_1"),
	PINCTRL_PIN(90, "SPI1_MOSI_IO_0"),
	PINCTRL_PIN(91, "ISH_I2C0_SDA"),
	PINCTRL_PIN(92, "ISH_I2C0_SCL"),
	PINCTRL_PIN(93, "ISH_I2C1_SDA"),
	PINCTRL_PIN(94, "ISH_I2C1_SCL"),
	PINCTRL_PIN(95, "ISH_SPI_CSB"),
	PINCTRL_PIN(96, "ISH_SPI_CLK"),
	PINCTRL_PIN(97, "ISH_SPI_MISO"),
	PINCTRL_PIN(98, "ISH_SPI_MOSI"),
	PINCTRL_PIN(99, "ISH_UART0_RXD"),
	PINCTRL_PIN(100, "ISH_UART0_TXD"),
	PINCTRL_PIN(101, "ISH_UART0_RTSB"),
	PINCTRL_PIN(102, "ISH_UART0_CTSB"),
	PINCTRL_PIN(103, "SPI1_IO_2"),
	PINCTRL_PIN(104, "SPI1_IO_3"),
	PINCTRL_PIN(105, "I2S_MCLK"),
	PINCTRL_PIN(106, "CNV_MFUART2_RXD"),
	PINCTRL_PIN(107, "CNV_MFUART2_TXD"),
	PINCTRL_PIN(108, "CNV_PA_BLANKING"),
	PINCTRL_PIN(109, "I2C5_SDA"),
	PINCTRL_PIN(110, "I2C5_SCL"),
	PINCTRL_PIN(111, "GSPI2_CLK_LOOPBK"),
	PINCTRL_PIN(112, "SPI1_CLK_LOOPBK"),
	/* vGPIO */
	PINCTRL_PIN(113, "CNV_BTEN"),
	PINCTRL_PIN(114, "CNV_WCEN"),
	PINCTRL_PIN(115, "CNV_BT_HOST_WAKEB"),
	PINCTRL_PIN(116, "CNV_BT_IF_SELECT"),
	PINCTRL_PIN(117, "vCNV_BT_UART_TXD"),
	PINCTRL_PIN(118, "vCNV_BT_UART_RXD"),
	PINCTRL_PIN(119, "vCNV_BT_UART_CTS_B"),
	PINCTRL_PIN(120, "vCNV_BT_UART_RTS_B"),
	PINCTRL_PIN(121, "vCNV_MFUART1_TXD"),
	PINCTRL_PIN(122, "vCNV_MFUART1_RXD"),
	PINCTRL_PIN(123, "vCNV_MFUART1_CTS_B"),
	PINCTRL_PIN(124, "vCNV_MFUART1_RTS_B"),
	PINCTRL_PIN(125, "vUART0_TXD"),
	PINCTRL_PIN(126, "vUART0_RXD"),
	PINCTRL_PIN(127, "vUART0_CTS_B"),
	PINCTRL_PIN(128, "vUART0_RTS_B"),
	PINCTRL_PIN(129, "vISH_UART0_TXD"),
	PINCTRL_PIN(130, "vISH_UART0_RXD"),
	PINCTRL_PIN(131, "vISH_UART0_CTS_B"),
	PINCTRL_PIN(132, "vISH_UART0_RTS_B"),
	PINCTRL_PIN(133, "vCNV_BT_I2S_BCLK"),
	PINCTRL_PIN(134, "vCNV_BT_I2S_WS_SYNC"),
	PINCTRL_PIN(135, "vCNV_BT_I2S_SDO"),
	PINCTRL_PIN(136, "vCNV_BT_I2S_SDI"),
	PINCTRL_PIN(137, "vI2S2_SCLK"),
	PINCTRL_PIN(138, "vI2S2_SFRM"),
	PINCTRL_PIN(139, "vI2S2_TXD"),
	PINCTRL_PIN(140, "vI2S2_RXD"),
	PINCTRL_PIN(141, "vSD3_CD_B"),
	/* GPP_C */
	PINCTRL_PIN(142, "GPPC_C_0"),
	PINCTRL_PIN(143, "GPPC_C_1"),
	PINCTRL_PIN(144, "GPPC_C_2"),
	PINCTRL_PIN(145, "GPPC_C_3"),
	PINCTRL_PIN(146, "GPPC_C_4"),
	PINCTRL_PIN(147, "GPPC_C_5"),
	PINCTRL_PIN(148, "SUSWARNB_SUSPWRDNACK"),
	PINCTRL_PIN(149, "SUSACKB"),
	PINCTRL_PIN(150, "UART0_RXD"),
	PINCTRL_PIN(151, "UART0_TXD"),
	PINCTRL_PIN(152, "UART0_RTSB"),
	PINCTRL_PIN(153, "UART0_CTSB"),
	PINCTRL_PIN(154, "UART1_RXD"),
	PINCTRL_PIN(155, "UART1_TXD"),
	PINCTRL_PIN(156, "UART1_RTSB"),
	PINCTRL_PIN(157, "UART1_CTSB"),
	PINCTRL_PIN(158, "I2C0_SDA"),
	PINCTRL_PIN(159, "I2C0_SCL"),
	PINCTRL_PIN(160, "I2C1_SDA"),
	PINCTRL_PIN(161, "I2C1_SCL"),
	PINCTRL_PIN(162, "UART2_RXD"),
	PINCTRL_PIN(163, "UART2_TXD"),
	PINCTRL_PIN(164, "UART2_RTSB"),
	PINCTRL_PIN(165, "UART2_CTSB"),
	/* vGPIO_3 */
	PINCTRL_PIN(166, "P0_CLKREQTX_VW_0"),
	PINCTRL_PIN(167, "P0_CLKREQTX_VW_1"),
	PINCTRL_PIN(168, "P0_CLKREQTX_VW_2"),
	PINCTRL_PIN(169, "P0_CLKREQTX_VW_3"),
	PINCTRL_PIN(170, "P0_CLKREQTX_VW_4"),
	PINCTRL_PIN(171, "P0_CLKREQTX_VW_5"),
	PINCTRL_PIN(172, "P0_CLKREQTX_VW_6"),
	PINCTRL_PIN(173, "P0_CLKREQTX_VW_7"),
	PINCTRL_PIN(174, "P0_CLKREQTX_VW_8"),
	PINCTRL_PIN(175, "P0_CLKREQTX_VW_9"),
	PINCTRL_PIN(176, "P0_CLKREQTX_VW_10"),
	PINCTRL_PIN(177, "P0_CLKREQTX_VW_11"),
	PINCTRL_PIN(178, "P0_CLKREQTX_VW_12"),
	PINCTRL_PIN(179, "P0_CLKREQTX_VW_13"),
	PINCTRL_PIN(180, "P0_CLKREQTX_VW_14"),
	PINCTRL_PIN(181, "P0_CLKREQTX_VW_15"),
	PINCTRL_PIN(182, "P1_CLKREQTX_VW_0"),
	PINCTRL_PIN(183, "P1_CLKREQTX_VW_1"),
	PINCTRL_PIN(184, "P1_CLKREQTX_VW_2"),
	PINCTRL_PIN(185, "P1_CLKREQTX_VW_3"),
	PINCTRL_PIN(186, "P1_CLKREQTX_VW_4"),
	PINCTRL_PIN(187, "P1_CLKREQTX_VW_5"),
	PINCTRL_PIN(188, "P1_CLKREQTX_VW_6"),
	PINCTRL_PIN(189, "P1_CLKREQTX_VW_7"),
	PINCTRL_PIN(190, "P1_CLKREQTX_VW_8"),
	PINCTRL_PIN(191, "P1_CLKREQTX_VW_9"),
	PINCTRL_PIN(192, "P1_CLKREQTX_VW_10"),
	PINCTRL_PIN(193, "P1_CLKREQTX_VW_11"),
	PINCTRL_PIN(194, "P1_CLKREQTX_VW_12"),
	PINCTRL_PIN(195, "P1_CLKREQTX_VW_13"),
	PINCTRL_PIN(196, "P1_CLKREQTX_VW_14"),
	PINCTRL_PIN(197, "P1_CLKREQTX_VW_15"),
	PINCTRL_PIN(198, "P2_CLKREQTX_VW_0"),
	PINCTRL_PIN(199, "P2_CLKREQTX_VW_1"),
	PINCTRL_PIN(200, "P2_CLKREQTX_VW_2"),
	PINCTRL_PIN(201, "P2_CLKREQTX_VW_3"),
	PINCTRL_PIN(202, "P2_CLKREQTX_VW_4"),
	PINCTRL_PIN(203, "P2_CLKREQTX_VW_5"),
	PINCTRL_PIN(204, "P2_CLKREQTX_VW_6"),
	PINCTRL_PIN(205, "P2_CLKREQTX_VW_7"),
	PINCTRL_PIN(206, "P2_CLKREQTX_VW_8"),
	PINCTRL_PIN(207, "P2_CLKREQTX_VW_9"),
	PINCTRL_PIN(208, "P2_CLKREQTX_VW_10"),
	PINCTRL_PIN(209, "P2_CLKREQTX_VW_11"),
	PINCTRL_PIN(210, "P2_CLKREQTX_VW_12"),
	PINCTRL_PIN(211, "P2_CLKREQTX_VW_13"),
	PINCTRL_PIN(212, "P2_CLKREQTX_VW_14"),
	PINCTRL_PIN(213, "P2_CLKREQTX_VW_15"),
	PINCTRL_PIN(214, "P3_CLKREQTX_VW_0"),
	PINCTRL_PIN(215, "P3_CLKREQTX_VW_1"),
	PINCTRL_PIN(216, "P3_CLKREQTX_VW_2"),
	PINCTRL_PIN(217, "P3_CLKREQTX_VW_3"),
	PINCTRL_PIN(218, "P3_CLKREQTX_VW_4"),
	PINCTRL_PIN(219, "P3_CLKREQTX_VW_5"),
	PINCTRL_PIN(220, "P3_CLKREQTX_VW_6"),
	PINCTRL_PIN(221, "P3_CLKREQTX_VW_7"),
	PINCTRL_PIN(222, "P3_CLKREQTX_VW_8"),
	PINCTRL_PIN(223, "P3_CLKREQTX_VW_9"),
	PINCTRL_PIN(224, "P3_CLKREQTX_VW_10"),
	PINCTRL_PIN(225, "P3_CLKREQTX_VW_11"),
	PINCTRL_PIN(226, "P3_CLKREQTX_VW_12"),
	PINCTRL_PIN(227, "P3_CLKREQTX_VW_13"),
	PINCTRL_PIN(228, "P3_CLKREQTX_VW_14"),
	PINCTRL_PIN(229, "P3_CLKREQTX_VW_15"),
	PINCTRL_PIN(230, "P0_CLKREQRX_VW_0"),
	PINCTRL_PIN(231, "P0_CLKREQRX_VW_1"),
	PINCTRL_PIN(232, "P0_CLKREQRX_VW_2"),
	PINCTRL_PIN(233, "P0_CLKREQRX_VW_3"),
	PINCTRL_PIN(234, "P1_CLKREQRX_VW_0"),
	PINCTRL_PIN(235, "P1_CLKREQRX_VW_1"),
	PINCTRL_PIN(236, "P1_CLKREQRX_VW_2"),
	PINCTRL_PIN(237, "P1_CLKREQRX_VW_3"),
	PINCTRL_PIN(238, "P2_CLKREQRX_VW_0"),
	PINCTRL_PIN(239, "P2_CLKREQRX_VW_1"),
	PINCTRL_PIN(240, "P2_CLKREQRX_VW_2"),
	PINCTRL_PIN(241, "P2_CLKREQRX_VW_3"),
	PINCTRL_PIN(242, "P3_CLKREQRX_VW_0"),
	PINCTRL_PIN(243, "P3_CLKREQRX_VW_1"),
	PINCTRL_PIN(244, "P3_CLKREQRX_VW_2"),
	PINCTRL_PIN(245, "P3_CLKREQRX_VW_3"),
	PINCTRL_PIN(246, "ESPI_USB_OCB_0"),
	PINCTRL_PIN(247, "ESPI_USB_OCB_1"),
	PINCTRL_PIN(248, "ESPI_USB_OCB_2"),
	PINCTRL_PIN(249, "ESPI_USB_OCB_3"),
	PINCTRL_PIN(250, "ESPI_USB_OCB_4"),
	PINCTRL_PIN(251, "ESPI_USB_OCB_5"),
	PINCTRL_PIN(252, "USB_CPU_OCB_0"),
	PINCTRL_PIN(253, "USB_CPU_OCB_1"),
	PINCTRL_PIN(254, "USB_CPU_OCB_2"),
	PINCTRL_PIN(255, "USB_CPU_OCB_3"),
	PINCTRL_PIN(256, "USB_CPU_OCB_4"),
	PINCTRL_PIN(257, "USB_CPU_OCB_5"),
	/* GPP_E */
	PINCTRL_PIN(258, "ISH_GP_0"),
	PINCTRL_PIN(259, "ISH_GP_1"),
	PINCTRL_PIN(260, "IMGCLKOUT_1"),
	PINCTRL_PIN(261, "ISH_GP_2"),
	PINCTRL_PIN(262, "IMGCLKOUT_2"),
	PINCTRL_PIN(263, "SATA_LEDB"),
	PINCTRL_PIN(264, "IMGCLKOUT_3"),
	PINCTRL_PIN(265, "ISH_GP_3"),
	PINCTRL_PIN(266, "ISH_GP_4"),
	PINCTRL_PIN(267, "ISH_GP_5"),
	PINCTRL_PIN(268, "ISH_GP_6"),
	PINCTRL_PIN(269, "ISH_GP_7"),
	PINCTRL_PIN(270, "IMGCLKOUT_4"),
	PINCTRL_PIN(271, "DDPA_CTRLCLK"),
	PINCTRL_PIN(272, "DDPA_CTRLDATA"),
	PINCTRL_PIN(273, "DDPB_CTRLCLK"),
	PINCTRL_PIN(274, "DDPB_CTRLDATA"),
	PINCTRL_PIN(275, "DDPC_CTRLCLK"),
	PINCTRL_PIN(276, "DDPC_CTRLDATA"),
	PINCTRL_PIN(277, "IMGCLKOUT_5"),
	PINCTRL_PIN(278, "CNV_BRI_DT"),
	PINCTRL_PIN(279, "CNV_BRI_RSP"),
	PINCTRL_PIN(280, "CNV_RGI_DT"),
	PINCTRL_PIN(281, "CNV_RGI_RSP"),
	/* vGPIO_4 */
	PINCTRL_PIN(282, "CPU_PCIE_LNK_DN_0"),
	PINCTRL_PIN(283, "CPU_PCIE_LNK_DN_1"),
	PINCTRL_PIN(284, "CPU_PCIE_LNK_DN_2"),
	PINCTRL_PIN(285, "CPU_PCIE_LNK_DN_3"),
	/* GPP_G */
	PINCTRL_PIN(286, "SD3_CMD"),
	PINCTRL_PIN(287, "SD3_D0"),
	PINCTRL_PIN(288, "SD3_D1"),
	PINCTRL_PIN(289, "SD3_D2"),
	PINCTRL_PIN(290, "SD3_D3"),
	PINCTRL_PIN(291, "SD3_CDB"),
	PINCTRL_PIN(292, "SD3_CLK"),
	PINCTRL_PIN(293, "SD3_WP"),
};

static const struct intel_padgroup icln_community0_gpps[] = {
	ICL_GPP(0, 0, 25),	/* GPP_B */
	ICL_GPP(1, 26, 46),	/* GPP_A */
	ICL_GPP(2, 47, 54),	/* GPP_S */
	ICL_GPP(3, 55, 62),	/* GPP_R */
};

static const struct intel_padgroup icln_community1_gpps[] = {
	ICL_GPP(0, 63, 86),	/* GPP_H */
	ICL_GPP(1, 87, 112),	/* GPP_D */
	ICL_GPP(2, 113, 141),	/* vGPIO */
	ICL_GPP(3, 142, 165),	/* GPP_C */
};

static const struct intel_padgroup icln_community3_gpps[] = {
	ICL_GPP(0, 166, 197),	/* vGPIO_3_0 */
	ICL_GPP(1, 198, 229),	/* vGPIO_3_1 */
	ICL_GPP(2, 230, 257),	/* vGPIO_3_2 */
};

static const struct intel_padgroup icln_community4_gpps[] = {
	ICL_GPP(0, 258, 281),	/* GPP_E */
	ICL_GPP(1, 282, 285),	/* vGPIO_4 */
};

static const struct intel_padgroup icln_community5_gpps[] = {
	ICL_GPP(0, 286, 293),	/* GPP_G */
};

static const struct intel_community icln_communities[] = {
	ICL_COMMUNITY(0, 0, 62, icln_community0_gpps),
	ICL_COMMUNITY(1, 63, 165, icln_community1_gpps),
	ICL_COMMUNITY(2, 166, 257, icln_community3_gpps),
	ICL_COMMUNITY(3, 258, 285, icln_community4_gpps),
	ICL_COMMUNITY(4, 286, 293, icln_community5_gpps),
};

static const struct intel_pingroup icln_groups[] = {
	/* PLACE HOLDER */
};

static const struct intel_function icln_functions[] = {
	/* PLACE HOLDER */
};

static const struct intel_pinctrl_soc_data icln_soc_data = {
	.pins = icln_pins,
	.npins = ARRAY_SIZE(icln_pins),
	.groups = icln_groups,
	.ngroups = ARRAY_SIZE(icln_groups),
	.functions = icln_functions,
	.nfunctions = ARRAY_SIZE(icln_functions),
	.communities = icln_communities,
	.ncommunities = ARRAY_SIZE(icln_communities),
};

static const struct acpi_device_id icln_pinctrl_acpi_match[] = {
	{ "", (kernel_ulong_t)&icln_soc_data },
	{ }
};
MODULE_DEVICE_TABLE(acpi, icln_pinctrl_acpi_match);

static INTEL_PINCTRL_PM_OPS(icln_pinctrl_pm_ops);

static struct platform_driver icln_pinctrl_driver = {
	.probe = intel_pinctrl_probe_by_hid,
	.driver = {
		.name = "icelake-n-pinctrl",
		.acpi_match_table = icln_pinctrl_acpi_match,
		.pm = &icln_pinctrl_pm_ops,
	},
};

module_platform_driver(icln_pinctrl_driver);

MODULE_AUTHOR("Andy Shevchenko <andriy.shevchenko@linux.intel.com>");
MODULE_DESCRIPTION("Intel Ice Lake PCH pinctrl/GPIO driver");
MODULE_LICENSE("GPL v2");
