// SPDX-License-Identifier: GPL-2.0
/*
 * Intel Ice Lake PCH pinctrl/GPIO driver
 *
 * Copyright (C) 2019, Intel Corporation
 * Author: Andy Shevchenko <andriy.shevchenko@linux.intel.com>
 */

#include <linux/mod_devicetable.h>
#include <linux/module.h>
#include <linux/platform_device.h>

#include <linux/pinctrl/pinctrl.h>

#include "pinctrl-intel.h"

#define ICL_PAD_OWN	0x020
#define ICL_PADCFGLOCK	0x080
#define ICL_HOSTSW_OWN	0x0c0
#define ICL_GPI_IS	0x100
#define ICL_GPI_IE	0x120

#define ICL_GPP(r, s, e)				\
	{						\
		.reg_num = (r),				\
		.base = (s),				\
		.size = ((e) - (s) + 1),		\
	}

#define ICL_COMMUNITY(b, s, e, g)			\
	{						\
		.barno = (b),				\
		.padown_offset = ICL_PAD_OWN,		\
		.padcfglock_offset = ICL_PADCFGLOCK,	\
		.hostown_offset = ICL_HOSTSW_OWN,	\
		.is_offset = ICL_GPI_IS,		\
		.ie_offset = ICL_GPI_IE,		\
		.pin_base = (s),			\
		.npins = ((e) - (s) + 1),		\
		.gpps = (g),				\
		.ngpps = ARRAY_SIZE(g),			\
	}

/* Ice Lake-N */
static const struct pinctrl_pin_desc icln_pins[] = {
	/* SPI */
	PINCTRL_PIN(0, "SPI0_IO_2"),
	PINCTRL_PIN(1, "SPI0_IO_3"),
	PINCTRL_PIN(2, "SPI0_MOSI_IO_0"),
	PINCTRL_PIN(3, "SPI0_MISO_IO_1"),
	PINCTRL_PIN(4, "SPI0_TPM_CSB"),
	PINCTRL_PIN(5, "SPI0_FLASH_0_CSB"),
	PINCTRL_PIN(6, "SPI0_FLASH_1_CSB"),
	PINCTRL_PIN(7, "SPI0_CLK"),
	PINCTRL_PIN(8, "SPI0_CLK_LOOPBK"),
	/* GPP_B */
	PINCTRL_PIN(9, "CORE_VID_0"),
	PINCTRL_PIN(10, "CORE_VID_1"),
	PINCTRL_PIN(11, "VRALERTB"),
	PINCTRL_PIN(12, "CPU_GP_2"),
	PINCTRL_PIN(13, "CPU_GP_3"),
	PINCTRL_PIN(14, "SRCCLKREQB_0"),
	PINCTRL_PIN(15, "SRCCLKREQB_1"),
	PINCTRL_PIN(16, "SRCCLKREQB_2"),
	PINCTRL_PIN(17, "SRCCLKREQB_3"),
	PINCTRL_PIN(18, "SRCCLKREQB_4"),
	PINCTRL_PIN(19, "SRCCLKREQB_5"),
	PINCTRL_PIN(20, "PMCALERTB"),
	PINCTRL_PIN(21, "SLP_S0B"),
	PINCTRL_PIN(22, "PLTRSTB"),
	PINCTRL_PIN(23, "SPKR"),
	PINCTRL_PIN(24, "GSPI0_CS0B"),
	PINCTRL_PIN(25, "GSPI0_CLK"),
	PINCTRL_PIN(26, "GSPI0_MISO"),
	PINCTRL_PIN(27, "GSPI0_MOSI"),
	PINCTRL_PIN(28, "GSPI1_CS0B"),
	PINCTRL_PIN(29, "GSPI1_CLK"),
	PINCTRL_PIN(30, "GSPI1_MISO"),
	PINCTRL_PIN(31, "GSPI1_MOSI"),
	PINCTRL_PIN(32, "GSPI1_CS1B"),
	PINCTRL_PIN(33, "GSPI0_CLK_LOOPBK"),
	PINCTRL_PIN(34, "GSPI1_CLK_LOOPBK"),
	/* GPP_A */
	PINCTRL_PIN(35, "ESPI_IO_0"),
	PINCTRL_PIN(36, "ESPI_IO_1"),
	PINCTRL_PIN(37, "ESPI_IO_2"),
	PINCTRL_PIN(38, "ESPI_IO_3"),
	PINCTRL_PIN(39, "ESPI_CSB"),
	PINCTRL_PIN(40, "ESPI_CLK"),
	PINCTRL_PIN(41, "ESPI_RESETB"),
	PINCTRL_PIN(42, "SMBCLK"),
	PINCTRL_PIN(43, "SMBDATA"),
	PINCTRL_PIN(44, "SMBALERTB"),
	PINCTRL_PIN(45, "CPU_GP_0"),
	PINCTRL_PIN(46, "CPU_GP_1"),
	PINCTRL_PIN(47, "USB2_OCB_1"),
	PINCTRL_PIN(48, "USB2_OCB_2"),
	PINCTRL_PIN(49, "USB2_OCB_3"),
	PINCTRL_PIN(50, "DDSP_HPD_A"),
	PINCTRL_PIN(51, "DDSP_HPD_B"),
	PINCTRL_PIN(52, "DDSP_HPD_C"),
	PINCTRL_PIN(53, "USB2_OCB_0"),
	PINCTRL_PIN(54, "PCHHOTB"),
	PINCTRL_PIN(55, "ESPI_CLK_LOOPBK"),
	/* GPP_S */
	PINCTRL_PIN(56, "SNDW1_CLK"),
	PINCTRL_PIN(57, "SNDW1_DATA"),
	PINCTRL_PIN(58, "SNDW2_CLK"),
	PINCTRL_PIN(59, "SNDW2_DATA"),
	PINCTRL_PIN(60, "SNDW1_CLK"),
	PINCTRL_PIN(61, "SNDW1_DATA"),
	PINCTRL_PIN(62, "SNDW4_CLK_DMIC_CLK_0"),
	PINCTRL_PIN(63, "SNDW4_DATA_DMIC_DATA_0"),
	/* GPP_R */
	PINCTRL_PIN(64, "HDA_BCLK"),
	PINCTRL_PIN(65, "HDA_SYNC"),
	PINCTRL_PIN(66, "HDA_SDO"),
	PINCTRL_PIN(67, "HDA_SDI_0"),
	PINCTRL_PIN(68, "HDA_RSTB"),
	PINCTRL_PIN(69, "HDA_SDI_1"),
	PINCTRL_PIN(70, "I2S1_SFRM"),
	PINCTRL_PIN(71, "I2S1_TXD"),
	/* GPP_H */
	PINCTRL_PIN(72, "GPPC_H_0"),
	PINCTRL_PIN(73, "SD_PWR_EN_B"),
	PINCTRL_PIN(74, "MODEM_CLKREQ"),
	PINCTRL_PIN(75, "SX_EXIT_HOLDOFFB"),
	PINCTRL_PIN(76, "I2C2_SDA"),
	PINCTRL_PIN(77, "I2C2_SCL"),
	PINCTRL_PIN(78, "I2C3_SDA"),
	PINCTRL_PIN(79, "I2C3_SCL"),
	PINCTRL_PIN(80, "I2C4_SDA"),
	PINCTRL_PIN(81, "I2C4_SCL"),
	PINCTRL_PIN(82, "CPU_VCCIO_PWR_GATEB"),
	PINCTRL_PIN(83, "I2S2_SCLK"),
	PINCTRL_PIN(84, "I2S2_SFRM"),
	PINCTRL_PIN(85, "I2S2_TXD"),
	PINCTRL_PIN(86, "I2S2_RXD"),
	PINCTRL_PIN(87, "I2S1_SCLK"),
	PINCTRL_PIN(88, "GPPC_H_16"),
	PINCTRL_PIN(89, "GPPC_H_17"),
	PINCTRL_PIN(90, "GPPC_H_18"),
	PINCTRL_PIN(91, "GPPC_H_19"),
	PINCTRL_PIN(92, "GPPC_H_20"),
	PINCTRL_PIN(93, "GPPC_H_21"),
	PINCTRL_PIN(94, "GPPC_H_22"),
	PINCTRL_PIN(95, "GPPC_H_23"),
	/* GPP_D */
	PINCTRL_PIN(96, "SPI1_CSB"),
	PINCTRL_PIN(97, "SPI1_CLK"),
	PINCTRL_PIN(98, "SPI1_MISO_IO_1"),
	PINCTRL_PIN(99, "SPI1_MOSI_IO_0"),
	PINCTRL_PIN(100, "ISH_I2C0_SDA"),
	PINCTRL_PIN(101, "ISH_I2C0_SCL"),
	PINCTRL_PIN(102, "ISH_I2C1_SDA"),
	PINCTRL_PIN(103, "ISH_I2C1_SCL"),
	PINCTRL_PIN(104, "ISH_SPI_CSB"),
	PINCTRL_PIN(105, "ISH_SPI_CLK"),
	PINCTRL_PIN(106, "ISH_SPI_MISO"),
	PINCTRL_PIN(107, "ISH_SPI_MOSI"),
	PINCTRL_PIN(108, "ISH_UART0_RXD"),
	PINCTRL_PIN(109, "ISH_UART0_TXD"),
	PINCTRL_PIN(110, "ISH_UART0_RTSB"),
	PINCTRL_PIN(111, "ISH_UART0_CTSB"),
	PINCTRL_PIN(112, "SPI1_IO_2"),
	PINCTRL_PIN(113, "SPI1_IO_3"),
	PINCTRL_PIN(114, "I2S_MCLK"),
	PINCTRL_PIN(115, "CNV_MFUART2_RXD"),
	PINCTRL_PIN(116, "CNV_MFUART2_TXD"),
	PINCTRL_PIN(117, "CNV_PA_BLANKING"),
	PINCTRL_PIN(118, "I2C5_SDA"),
	PINCTRL_PIN(119, "I2C5_SCL"),
	PINCTRL_PIN(120, "GSPI2_CLK_LOOPBK"),
	PINCTRL_PIN(121, "SPI1_CLK_LOOPBK"),
	/* vGPIO */
	PINCTRL_PIN(122, "CNV_BTEN"),
	PINCTRL_PIN(123, "CNV_WCEN"),
	PINCTRL_PIN(124, "CNV_BT_HOST_WAKEB"),
	PINCTRL_PIN(125, "CNV_BT_IF_SELECT"),
	PINCTRL_PIN(126, "vCNV_BT_UART_TXD"),
	PINCTRL_PIN(127, "vCNV_BT_UART_RXD"),
	PINCTRL_PIN(128, "vCNV_BT_UART_CTS_B"),
	PINCTRL_PIN(129, "vCNV_BT_UART_RTS_B"),
	PINCTRL_PIN(130, "vCNV_MFUART1_TXD"),
	PINCTRL_PIN(131, "vCNV_MFUART1_RXD"),
	PINCTRL_PIN(132, "vCNV_MFUART1_CTS_B"),
	PINCTRL_PIN(133, "vCNV_MFUART1_RTS_B"),
	PINCTRL_PIN(134, "vUART0_TXD"),
	PINCTRL_PIN(135, "vUART0_RXD"),
	PINCTRL_PIN(136, "vUART0_CTS_B"),
	PINCTRL_PIN(137, "vUART0_RTS_B"),
	PINCTRL_PIN(138, "vISH_UART0_TXD"),
	PINCTRL_PIN(139, "vISH_UART0_RXD"),
	PINCTRL_PIN(140, "vISH_UART0_CTS_B"),
	PINCTRL_PIN(141, "vISH_UART0_RTS_B"),
	PINCTRL_PIN(142, "vCNV_BT_I2S_BCLK"),
	PINCTRL_PIN(143, "vCNV_BT_I2S_WS_SYNC"),
	PINCTRL_PIN(144, "vCNV_BT_I2S_SDO"),
	PINCTRL_PIN(145, "vCNV_BT_I2S_SDI"),
	PINCTRL_PIN(146, "vI2S2_SCLK"),
	PINCTRL_PIN(147, "vI2S2_SFRM"),
	PINCTRL_PIN(148, "vI2S2_TXD"),
	PINCTRL_PIN(149, "vI2S2_RXD"),
	PINCTRL_PIN(150, "vSD3_CD_B"),
	/* GPP_C */
	PINCTRL_PIN(151, "GPPC_C_0"),
	PINCTRL_PIN(152, "GPPC_C_1"),
	PINCTRL_PIN(153, "GPPC_C_2"),
	PINCTRL_PIN(154, "GPPC_C_3"),
	PINCTRL_PIN(155, "GPPC_C_4"),
	PINCTRL_PIN(156, "GPPC_C_5"),
	PINCTRL_PIN(157, "SUSWARNB_SUSPWRDNACK"),
	PINCTRL_PIN(158, "SUSACKB"),
	PINCTRL_PIN(159, "UART0_RXD"),
	PINCTRL_PIN(160, "UART0_TXD"),
	PINCTRL_PIN(161, "UART0_RTSB"),
	PINCTRL_PIN(162, "UART0_CTSB"),
	PINCTRL_PIN(163, "UART1_RXD"),
	PINCTRL_PIN(164, "UART1_TXD"),
	PINCTRL_PIN(165, "UART1_RTSB"),
	PINCTRL_PIN(166, "UART1_CTSB"),
	PINCTRL_PIN(167, "I2C0_SDA"),
	PINCTRL_PIN(168, "I2C0_SCL"),
	PINCTRL_PIN(169, "I2C1_SDA"),
	PINCTRL_PIN(170, "I2C1_SCL"),
	PINCTRL_PIN(171, "UART2_RXD"),
	PINCTRL_PIN(172, "UART2_TXD"),
	PINCTRL_PIN(173, "UART2_RTSB"),
	PINCTRL_PIN(174, "UART2_CTSB"),
	/* GPP_E */
	PINCTRL_PIN(175, "ISH_GP_0"),
	PINCTRL_PIN(176, "ISH_GP_1"),
	PINCTRL_PIN(177, "IMGCLKOUT_1"),
	PINCTRL_PIN(178, "ISH_GP_2"),
	PINCTRL_PIN(179, "IMGCLKOUT_2"),
	PINCTRL_PIN(180, "SATA_LEDB"),
	PINCTRL_PIN(181, "IMGCLKOUT_3"),
	PINCTRL_PIN(182, "ISH_GP_3"),
	PINCTRL_PIN(183, "ISH_GP_4"),
	PINCTRL_PIN(184, "ISH_GP_5"),
	PINCTRL_PIN(185, "ISH_GP_6"),
	PINCTRL_PIN(186, "ISH_GP_7"),
	PINCTRL_PIN(187, "IMGCLKOUT_4"),
	PINCTRL_PIN(188, "DDPA_CTRLCLK"),
	PINCTRL_PIN(189, "DDPA_CTRLDATA"),
	PINCTRL_PIN(190, "DDPB_CTRLCLK"),
	PINCTRL_PIN(191, "DDPB_CTRLDATA"),
	PINCTRL_PIN(192, "DDPC_CTRLCLK"),
	PINCTRL_PIN(193, "DDPC_CTRLDATA"),
	PINCTRL_PIN(194, "IMGCLKOUT_5"),
	PINCTRL_PIN(195, "CNV_BRI_DT"),
	PINCTRL_PIN(196, "CNV_BRI_RSP"),
	PINCTRL_PIN(197, "CNV_RGI_DT"),
	PINCTRL_PIN(198, "CNV_RGI_RSP"),
	/* GPP_G */
	PINCTRL_PIN(199, "SD3_CMD"),
	PINCTRL_PIN(200, "SD3_D0"),
	PINCTRL_PIN(201, "SD3_D1"),
	PINCTRL_PIN(202, "SD3_D2"),
	PINCTRL_PIN(203, "SD3_D3"),
	PINCTRL_PIN(204, "SD3_CDB"),
	PINCTRL_PIN(205, "SD3_CLK"),
	PINCTRL_PIN(206, "SD3_WP"),
};

static const struct intel_padgroup icln_community0_gpps[] = {
	ICL_GPP(0, 0, 8),	/* SPI */
	ICL_GPP(1, 9, 34),	/* GPP_B */
	ICL_GPP(2, 35, 55),	/* GPP_A */
	ICL_GPP(3, 56, 63),	/* GPP_S */
	ICL_GPP(4, 64, 71),	/* GPP_R */
};

static const struct intel_padgroup icln_community1_gpps[] = {
	ICL_GPP(0, 72, 95),	/* GPP_H */
	ICL_GPP(1, 96, 121),	/* GPP_D */
	ICL_GPP(2, 122, 150),	/* vGPIO */
	ICL_GPP(3, 151, 174),	/* GPP_C */
};

static const struct intel_padgroup icln_community4_gpps[] = {
	ICL_GPP(0, 175, 198),	/* GPP_E */
};

static const struct intel_padgroup icln_community5_gpps[] = {
	ICL_GPP(0, 199, 206),	/* GPP_G */
};

static const struct intel_community icln_communities[] = {
	ICL_COMMUNITY(0, 0, 71, icln_community0_gpps),
	ICL_COMMUNITY(1, 72, 174, icln_community1_gpps),
	ICL_COMMUNITY(2, 175, 198, icln_community4_gpps),
	ICL_COMMUNITY(3, 199, 206, icln_community5_gpps),
};

static const struct intel_pingroup icln_groups[] = {
	/* PLACE HOLDER */
};

static const struct intel_function icln_functions[] = {
	/* PLACE HOLDER */
};

static const struct intel_pinctrl_soc_data icln_soc_data = {
	.pins = icln_pins,
	.npins = ARRAY_SIZE(icln_pins),
	.groups = icln_groups,
	.ngroups = ARRAY_SIZE(icln_groups),
	.functions = icln_functions,
	.nfunctions = ARRAY_SIZE(icln_functions),
	.communities = icln_communities,
	.ncommunities = ARRAY_SIZE(icln_communities),
};

static const struct acpi_device_id icln_pinctrl_acpi_match[] = {
	{ "", (kernel_ulong_t)&icln_soc_data },
	{ }
};
MODULE_DEVICE_TABLE(acpi, icln_pinctrl_acpi_match);

static INTEL_PINCTRL_PM_OPS(icln_pinctrl_pm_ops);

static struct platform_driver icln_pinctrl_driver = {
	.probe = intel_pinctrl_probe_by_hid,
	.driver = {
		.name = "icelake-n-pinctrl",
		.acpi_match_table = icln_pinctrl_acpi_match,
		.pm = &icln_pinctrl_pm_ops,
	},
};

module_platform_driver(icln_pinctrl_driver);

MODULE_AUTHOR("Andy Shevchenko <andriy.shevchenko@linux.intel.com>");
MODULE_DESCRIPTION("Intel Ice Lake PCH pinctrl/GPIO driver");
MODULE_LICENSE("GPL v2");
