#
# Makefile - STL2 PCIe device driver
# Copyright(c) 2014, Intel Corporation.
#
obj-m += hfi2.o

hfi2-y :=
hfi2-y += debugfs.o
hfi2-y += init.o
hfi2-y += fxr.o
hfi2-y += intr.o
hfi2-y += pcie.o
hfi2-y += portals.o
hfi2-y += privileged.o
