/*
* Autogenerated by i_csrs.pl on Thu Sep 12 10:01:30 2013
* 
* i_csrs.pl Version 1.1 last modified on Thursday 9/12/13 10:01:19.
*/
#ifndef DC_PCSLPE_TOP
#define DC_PCSLPE_TOP 0x000000000000
#endif
#define DC_PCSLPE_LPE (DC_PCSLPE_TOP + 0x000000000000)
#define DC_PCSLPE_PCS_8B10B (DC_PCSLPE_TOP + 0x000000000400)
#define DC_PCSLPE_PCS_66 (DC_PCSLPE_TOP + 0x000000000600)
