#
# Makefile for ThunderBay OCS AES Crypto API Linux driver
#
obj-$(CONFIG_CRYPTO_DEV_THUNDERBAY_OCS_AES) += thunderbay-ocs-aes.o
thunderbay-ocs-aes-objs := thunderbay-ocs-aes-core.o ocs-aes.o
obj-$(CONFIG_CRYPTO_DEV_THUNDERBAY_OCS_HCU) += thunderbay-ocs-hcu.o
thunderbay-ocs-hcu-objs := thunderbay-ocs-hcu-core.o ocs-hcu.o

