/*
* Autogenerated by i_csrs.pl on Wed Dec 11 09:08:26 2013
* 
* i_csrs.pl Version 1.4 last modified on Monday 12/9/13 13:25:19.
*/

#ifndef DEF_DC_TOP_CSRS_SW_DEF
#define DEF_DC_TOP_CSRS_SW_DEF

#define DC_TOP_CSRS		0x000000000000
#define DCC_CSRS		(DC_TOP_CSRS + 0x000000000000)
#define DC_LCB_CSRS		(DC_TOP_CSRS + 0x000000001000)
#define DC_8051_CSRS		(DC_TOP_CSRS + 0x000000002000)

#endif 		/* DEF_DC_TOP_CSRS_SW_DEF */
