/*
* Autogenerated by i_csrs.pl on Wed Dec 11 09:08:24 2013
* 
* i_csrs.pl Version 1.4 last modified on Monday 12/9/13 13:25:19.
*/

#ifndef DEF_WFR_PCIE_SW_STRUCT
#define DEF_WFR_PCIE_SW_STRUCT

/*
*  Stuctures and Unions from Tables
*/

#endif 		/* DEF_WFR_PCIE_SW_STRUCT */
