#!/bin/bash

source common/config
source common/rc

: "${runs:=10}"
: "${time:=30}"
: "${perf:=0}"
: "${invalidate:=0}"

perfcmd=

if [ $perf -ne 0 ]; then
	echo "Using perf, setting runs=1"
	runs=1
	perfcmd="perf record -g"
	rm -f /dev/shm/perf.db
fi

res=$results/$(basename $0)

[ -n "$1" ] || _fail "Please provide a device to run on. $0 btt|pmem will suffice"
device=$(get_dev $1)

[ -b $device ] || _fail "$0: $device: no such block device"

_basic_checks $device
btt_lazy_init $device

dev_sub=" -e s|^filename=.*|filename=$device|g"
time_sub=" -e s|^runtime=.*|runtime=$time|g"

sed $dev_sub $time_sub generic.fio > tmp.fio

[ -s tmp.fio ] || _fail "error in setting up fio config"

for (( i=0; i<$runs; i++ )); do
	echo "running fio ($i)"
	if [ $invalidate -ne 0 ]; then
		drop_caches
	fi
	$perfcmd fio tmp.fio > ${res}_$i 2>&1
	sleep 1
done

# analyze
process_fio_files $results tmp.fio

rm -f tmp.fio

[ -n "$perfcmd" ] && echo "perf stats: $ perf report -g"

exit 0

# vim:ft=sh
