/*
* Autogenerated by i_csrs.pl on Mon Jul  9 11:36:19 2018
* 
* i_csrs.pl Version 1.5 last modified on Thursday 6/28/18 12:45:58.
*/

#ifndef DEF_FXR_RCF_SW_STRUCT_DEFS
#define DEF_FXR_RCF_SW_STRUCT_DEFS



#endif                 /* DEF_FXR_RCF_SW_STRUCT_DEFS */
