/*
* Autogenerated by i_csrs.pl on Mon Jun 18 11:50:58 2018
* 
* i_csrs.pl Version 1.5 last modified on Thursday 5/24/18 14:54:42.
*/

#ifndef DEF_FXR_FW_SW_STRUCT
#define DEF_FXR_FW_SW_STRUCT

/*
*  Structures and Unions from Tables
*/

#endif                 /* DEF_FXR_FW_SW_STRUCT */
