/*
* Autogenerated by i_csrs.pl on Tue May 30 15:16:49 2017
* 
* i_csrs.pl Version 1.5 last modified on Monday 12/19/16 11:42:34.
*/

#ifndef DEF_FXR_TX_OTR_MSG_TOP_CSRS_SW_STRUCT_DEFS
#define DEF_FXR_TX_OTR_MSG_TOP_CSRS_SW_STRUCT_DEFS



#endif                 /* DEF_FXR_TX_OTR_MSG_TOP_CSRS_SW_STRUCT_DEFS */
