/*
* Autogenerated by i_csrs.pl on Wed Aug 15 07:34:11 2018
* 
* i_csrs.pl Version 1.5 last modified on Wednesday 8/8/18 08:19:29.
*/

#ifndef DEF_FXR_RX_HP_SW_STRUCT_DEFS
#define DEF_FXR_RX_HP_SW_STRUCT_DEFS



#endif                 /* DEF_FXR_RX_HP_SW_STRUCT_DEFS */
