/*
* Autogenerated by i_csrs.pl on Mon Jul  9 11:36:00 2018
* 
* i_csrs.pl Version 1.5 last modified on Thursday 6/28/18 12:45:58.
*/

#ifndef DEF_FXR_TX_OTR_PKT_TOP_CSRS_SW_STRUCT
#define DEF_FXR_TX_OTR_PKT_TOP_CSRS_SW_STRUCT

/*
*  Structures and Unions from Tables
*/

#endif                 /* DEF_FXR_TX_OTR_PKT_TOP_CSRS_SW_STRUCT */
