/*
*------------------------------------------------------------------------------
*                                                                              
*  INTEL CONFIDENTIAL                                                          
*                                                                              
*  Copyright 2018 Intel Corporation All Rights Reserved.                 
*                                                                              
*  The source code contained or described herein and all documents related     
*  to the source code ("Material") are owned by Intel Corporation or its    
*  suppliers or licensors. Title to the Material remains with Intel            
*  Corporation or its suppliers and licensors. The Material contains trade     
*  secrets and proprietary and confidential information of Intel or its        
*  suppliers and licensors. The Material is protected by worldwide copyright   
*  and trade secret laws and treaty provisions. No part of the Material may    
*  be used, copied, reproduced, modified, published, uploaded, posted,         
*  transmitted, distributed, or disclosed in any way without Intel's prior     
*  express written permission.                                                 
*                                                                              
*  No license under any patent, copyright, trade secret or other intellectual  
*  property right is granted to or conferred upon you by disclosure or         
*  delivery of the Materials, either expressly, by implication, inducement,    
*  estoppel or otherwise. Any license under such intellectual property rights  
*  must be express and approved by Intel in writing.                           
*                                                                              
*------------------------------------------------------------------------------
*  Auto-generated by /p/hdk/rtl/proj_tools/sl2_tools/sl2_tools-srvr10nm-18ww26b/scripts/i_csrs/i_csrs.pl
*  i_csrs.pl Version 1.5 last modified on Thursday 6/28/18 12:45:58
*  /p/hdk/rtl/proj_tools/sl2_tools/sl2_tools-srvr10nm-18ww26b/scripts/i_csrs/i_csrs.pl -C -o /nfs/sc/disks/slx_0108/pvesv/fxr_autogen/fxr /nfs/sc/disks/slx_0108/pvesv/fxr_autogen/repo_xml/300_Memory_Map.xml
*------------------------------------------------------------------------------
*/

#ifndef DEF_FXR_TOP_SW_DEF
#define DEF_FXR_TOP_SW_DEF

#ifndef FXR_TOP
#define FXR_TOP					0x000000000000
#endif
#define FXR_CONFIG_CSRS				(FXR_TOP + 0x000000000000)
#define FXR_TX_CI_FAST_CSRS			(FXR_TOP + 0x000000000000)
#define FXR_RX_CI_FAST_CSRS			(FXR_TOP + 0x000000400000)
#define FXR_AT_CSRS				(FXR_TOP + 0x000000800000)
#define FXR_TX_CI_CID_CSRS			(FXR_TOP + 0x000000C00000)
#define FXR_TX_CI_CIC_CSRS			(FXR_TOP + 0x000001000000)
#define FXR_TX_OTR_PKT_TOP_CSRS			(FXR_TOP + 0x000001080000)
#define FXR_TX_OTR_MSG_TOP_CSRS			(FXR_TOP + 0x000001100000)
#define FXR_TX_DMA_CSRS				(FXR_TOP + 0x000001180000)
#define FXR_RX_CI_CID_CSRS			(FXR_TOP + 0x000001200000)
#define FXR_RX_CI_CIC_CSRS			(FXR_TOP + 0x000001300000)
#define FXR_RX_HP_CSRS				(FXR_TOP + 0x000001400000)
#define FXR_RX_E2E_CSRS				(FXR_TOP + 0x000001480000)
#define FXR_RX_DMA_CSRS				(FXR_TOP + 0x000001500000)
#define FXR_RX_HIARB_CSRS			(FXR_TOP + 0x000001580000)
#define FXR_RX_ET_CSRS				(FXR_TOP + 0x000001600000)
#define FXR_AT_IOMMU_CSRS			(FXR_TOP + 0x000001680000)
#define FXR_IOMMU_CSRS				(FXR_TOP + 0x000001681000)
#define HFI_LOCA_CSRS				(FXR_TOP + 0x000001800000)
#define HFI_HIFIS_CSRS				(FXR_TOP + 0x000001A00000)
#define HFI_PCIM_CSRS				(FXR_TOP + 0x000001A80000)
#define FXR_LM_CSRS				(FXR_TOP + 0x000001B00000)
#define FXR_LM_CM_CSRS				(FXR_TOP + 0x000001B40000)
#define FXR_LM_FPC_CSRS				(FXR_TOP + 0x000001B80000)
#define FXR_LM_TP_CSRS				(FXR_TOP + 0x000001BC0000)
#define FXR_GBL_CSRS				(FXR_TOP + 0x000001C00000)
#define FXR_RCF_CSRS				(FXR_TOP + 0x000001C01000)
#define FXR_FW_CSRS				(FXR_TOP + 0x000001C10000)
#define FXR_PMON_CSRS				(FXR_TOP + 0x000001D00000)
#define FXR_CCLK_DFD_CAP_CSRS			(FXR_TOP + 0x000001D80000)
#define FXR_LOCA_DFD_CSRS			(FXR_TOP + 0x000001D82000)
#define FXR_LM_DFD_CSRS				(FXR_TOP + 0x000001D83000)
#define FXR_AT_DFD_CSRS				(FXR_TOP + 0x000001D84000)
#define FXR_AT_IOMMU_DFD_CSRS			(FXR_TOP + 0x000001D85000)
#define FXR_HIFIS_DFD_CSRS			(FXR_TOP + 0x000001D86000)
#define FXR_PCIM_DFD_CSRS			(FXR_TOP + 0x000001D87000)
#define FXR_RX_CI_CID_DFD_CSRS			(FXR_TOP + 0x000001D88000)
#define FXR_RX_DMA_DFD_CSRS			(FXR_TOP + 0x000001D89000)
#define FXR_RX_E2E_DFD_CSRS			(FXR_TOP + 0x000001D8A000)
#define FXR_RX_ET_DFD_CSRS			(FXR_TOP + 0x000001D8B000)
#define FXR_RX_HIARB_DFD_CSRS			(FXR_TOP + 0x000001D8C000)
#define FXR_RX_HP_DFD_CSRS			(FXR_TOP + 0x000001D8D000)
#define FXR_TX_CI_CID_DFD_CSRS			(FXR_TOP + 0x000001D8F000)
#define FXR_TX_DMA_DFD_CSRS			(FXR_TOP + 0x000001D90000)
#define FXR_TX_OTR_BPE_TOP_DFD_CSRS		(FXR_TOP + 0x000001D91000)
#define FXR_TX_OTR_MSG_TOP_DFD_CSRS		(FXR_TOP + 0x000001D92000)
#define FXR_TX_OTR_PKT_TOP_DFD_CSRS		(FXR_TOP + 0x000001D93000)
#define FXR_PCIE_DFD_CSRS			(FXR_TOP + 0x000001D94000)
#define FXR_DFD_PA_CSRS				(FXR_TOP + 0x000001D96000)
#define FXR_CRK_8051_CSRS			(FXR_TOP + 0x000001E00000)
#define FXR_CRK_LCB_CSRS			(FXR_TOP + 0x000001E08000)
#define FXR_DFD_CRK_CSRS			(FXR_TOP + 0x000001E18000)
#define FXR_TOP_SIZE				0x2000000
#define FXR_TX_CI_FAST_CSRS_SIZE		0x0200000
#define FXR_RX_CI_FAST_CSRS_SIZE		0x0200000
#define FXR_AT_CSRS_SIZE			0x0400000
#define FXR_AT_CSRS_EP				0x07
#define FXR_TX_CI_CID_CSRS_SIZE			0x0400000
#define FXR_TX_CI_CID_CSRS_EP			0x08
#define FXR_TX_CI_CIC_CSRS_SIZE			0x0080000
#define FXR_TX_CI_CIC_CSRS_EP			0x08
#define FXR_TX_OTR_PKT_TOP_CSRS_SIZE		0x0080000
#define FXR_TX_OTR_PKT_TOP_CSRS_EP		0x09
#define FXR_TX_OTR_MSG_TOP_CSRS_SIZE		0x0080000
#define FXR_TX_OTR_MSG_TOP_CSRS_EP		0x09
#define FXR_TX_DMA_CSRS_SIZE			0x0080000
#define FXR_TX_DMA_CSRS_EP			0x0a
#define FXR_RX_CI_CID_CSRS_SIZE			0x0100000
#define FXR_RX_CI_CID_CSRS_EP			0x0e
#define FXR_RX_CI_CIC_CSRS_SIZE			0x0100000
#define FXR_RX_CI_CIC_CSRS_EP			0x0e
#define FXR_RX_HP_CSRS_SIZE			0x0080000
#define FXR_RX_HP_CSRS_EP			0x0f
#define FXR_RX_E2E_CSRS_SIZE			0x0080000
#define FXR_RX_E2E_CSRS_EP			0x11
#define FXR_RX_DMA_CSRS_SIZE			0x0080000
#define FXR_RX_DMA_CSRS_EP			0x0c
#define FXR_RX_HIARB_CSRS_SIZE			0x0080000
#define FXR_RX_HIARB_CSRS_EP			0x0b
#define FXR_RX_ET_CSRS_SIZE			0x0080000
#define FXR_RX_ET_CSRS_EP			0x0d
#define FXR_AT_IOMMU_CSRS_SIZE			0x0001000
#define FXR_AT_IOMMU_CSRS_EP			0x06
#define FXR_IOMMU_CSRS_SIZE			0x0001000
#define FXR_IOMMU_CSRS_EP			0x06
#define HFI_LOCA_CSRS_SIZE			0x0200000
#define HFI_LOCA_CSRS_EP			0x03
#define HFI_HIFIS_CSRS_SIZE			0x0080000
#define HFI_HIFIS_CSRS_EP			0x02
#define HFI_PCIM_CSRS_SIZE			0x0080000
#define HFI_PCIM_CSRS_EP			0x01
#define FXR_PCIM_MSTR_EP			0x00
#define FXR_LM_CSRS_SIZE			0x0040000
#define FXR_LM_CSRS_EP				0x13
#define FXR_LM_CM_CSRS_SIZE			0x0040000
#define FXR_LM_CM_CSRS_EP			0x13
#define FXR_LM_FPC_CSRS_SIZE			0x0040000
#define FXR_LM_FPC_CSRS_EP			0x13
#define FXR_LM_TP_CSRS_SIZE			0x0040000
#define FXR_LM_TP_CSRS_EP			0x13
#define FXR_GBL_CSRS_SIZE			0x0001000
#define FXR_GBL_CSRS_EP				0x30
#define FXR_RCF_CSRS_SIZE			0x0001000
#define FXR_RCF_CSRS_EP				0x31
#define FXR_TAP2IOSFSB_EP			0x32
#define FXR_FW_CSRS_SIZE			0x0010000
#define FXR_FW_CSRS_EP				0x33
#define FXR_PMON_CSRS_SIZE			0x0080000
#define FXR_PMON_CSRS_EP			0xb
#define FXR_CCLK_DFD_CAP_CSRS_SIZE		0x0001000
#define FXR_CCLK_DFD_CAP_CSRS_EP		0x2C
#define FXR_LOCA_DFD_CSRS_SIZE			0x0001000
#define FXR_LOCA_DFD_CSRS_EP			0x03
#define FXR_LM_DFD_CSRS_SIZE			0x0001000
#define FXR_LM_DFD_CSRS_EP			0x13
#define FXR_AT_DFD_CSRS_SIZE			0x0001000
#define FXR_AT_DFD_CSRS_EP			0x07
#define FXR_AT_IOMMU_DFD_CSRS_SIZE		0x0001000
#define FXR_AT_IOMMU_DFD_CSRS_EP		0x06
#define FXR_HIFIS_DFD_CSRS_SIZE			0x0001000
#define FXR_HIFIS_DFD_CSRS_EP			0x02
#define FXR_PCIM_DFD_CSRS_SIZE			0x0001000
#define FXR_PCIM_DFD_CSRS_EP			0x01
#define FXR_RX_CI_CID_DFD_CSRS_SIZE		0x0001000
#define FXR_RX_CI_CID_DFD_CSRS_EP		0x0e
#define FXR_RX_DMA_DFD_CSRS_SIZE		0x0001000
#define FXR_RX_DMA_DFD_CSRS_EP			0x0c
#define FXR_RX_E2E_DFD_CSRS_SIZE		0x0001000
#define FXR_RX_E2E_DFD_CSRS_EP			0x11
#define FXR_RX_ET_DFD_CSRS_SIZE			0x0001000
#define FXR_RX_ET_DFD_CSRS_EP			0x0d
#define FXR_RX_HIARB_DFD_CSRS_SIZE		0x0001000
#define FXR_RX_HIARB_DFD_CSRS_EP		0x0b
#define FXR_RX_HP_DFD_CSRS_SIZE			0x0001000
#define FXR_RX_HP_DFD_CSRS_EP			0x0f
#define FXR_TX_CI_CID_DFD_CSRS_SIZE		0x0001000
#define FXR_TX_CI_CID_DFD_CSRS_EP		0x08
#define FXR_TX_DMA_DFD_CSRS_SIZE		0x0001000
#define FXR_TX_DMA_DFD_CSRS_EP			0x0a
#define FXR_TX_OTR_BPE_TOP_DFD_CSRS_SIZE	0x0001000
#define FXR_TX_OTR_BPE_TOP_DFD_CSRS_EP		0x09
#define FXR_TX_OTR_MSG_TOP_DFD_CSRS_SIZE	0x0001000
#define FXR_TX_OTR_MSG_TOP_DFD_CSRS_EP		0x09
#define FXR_TX_OTR_PKT_TOP_DFD_CSRS_SIZE	0x0001000
#define FXR_TX_OTR_PKT_TOP_DFD_CSRS_EP		0x09
#define FXR_PCIE_DFD_CSRS_SIZE			0x0001000
#define FXR_PCIE_DFD_CSRS_EP			0x2c
#define FXR_DFD_PA_CSRS_SIZE			0x0001000
#define FXR_DFD_PA_CSRS_EP			0x2c
#define FXR_CRK_8051_CSRS_SIZE			0x0004000
#define FXR_CRK_8051_CSRS_EP			0x14
#define FXR_CRK_LCB_CSRS_SIZE			0x0004000
#define FXR_CRK_LCB_CSRS_EP			0x14
#define FXR_DFD_CRK_CSRS_SIZE			0x0001000
#define FXR_DFD_CRK_CSRS_EP			0x14
#define FXR_NUM_CONTEXTS			256
#define FXR_NUM_PIDS				4096
#define FXR_MAX_CONTEXT				255
#define FXR_TX_CONTEXT_ENTRIES			128
#define FXR_TX_CONTEXT_MAX			127
#define FXR_RX_CONTEXT_ENTRIES			32
#define FXR_RX_CONTEXT_MAX			31
#define FXR_NUM_SL				32
#define FXR_MAX_SL				31

#endif 		/* DEF_FXR_TOP_SW_DEF */
