/*
* Autogenerated by i_csrs.pl on Tue May 16 21:51:16 2017
* 
* i_csrs.pl Version 1.5 last modified on Monday 12/19/16 11:42:34.
*/

#ifndef DEF_FXR_LINKMUX_TP_SW_STRUCT_DEFS
#define DEF_FXR_LINKMUX_TP_SW_STRUCT_DEFS



#endif                 /* DEF_FXR_LINKMUX_TP_SW_STRUCT_DEFS */
