/*
*------------------------------------------------------------------------------
*                                                                              
*  INTEL CONFIDENTIAL                                                          
*                                                                              
*  Copyright 2018 Intel Corporation All Rights Reserved.                 
*                                                                              
*  The source code contained or described herein and all documents related     
*  to the source code ("Material") are owned by Intel Corporation or its    
*  suppliers or licensors. Title to the Material remains with Intel            
*  Corporation or its suppliers and licensors. The Material contains trade     
*  secrets and proprietary and confidential information of Intel or its        
*  suppliers and licensors. The Material is protected by worldwide copyright   
*  and trade secret laws and treaty provisions. No part of the Material may    
*  be used, copied, reproduced, modified, published, uploaded, posted,         
*  transmitted, distributed, or disclosed in any way without Intel's prior     
*  express written permission.                                                 
*                                                                              
*  No license under any patent, copyright, trade secret or other intellectual  
*  property right is granted to or conferred upon you by disclosure or         
*  delivery of the Materials, either expressly, by implication, inducement,    
*  estoppel or otherwise. Any license under such intellectual property rights  
*  must be express and approved by Intel in writing.                           
*                                                                              
*------------------------------------------------------------------------------
*  Auto-generated by /p/hdk/rtl/proj_tools/sl2_tools/sl2_tools-srvr10nm-18ww26b/scripts/i_csrs/i_csrs.pl
*  i_csrs.pl Version 1.5 last modified on Thursday 6/28/18 12:45:58
*  /p/hdk/rtl/proj_tools/sl2_tools/sl2_tools-srvr10nm-18ww26b/scripts/i_csrs/i_csrs.pl -C -RVREGS -ST fxr_fast_path -o /nfs/sc/disks/slx_0108/pvesv/fxr_autogen/fxr /nfs/sc/disks/slx_0108/pvesv/fxr_autogen/repo_xml/300_Memory_Map.xml /nfs/sc/disks/slx_0108/pvesv/fxr_autogen/repo_xml/310_Memory_Map_Fast_Path.xml
*------------------------------------------------------------------------------
*/

#ifndef DEF_FXR_FAST_PATH_SW_DEF
#define DEF_FXR_FAST_PATH_SW_DEF

#ifndef FXR_TX_CI_FAST_CSRS 
#define FXR_TX_CI_FAST_CSRS			0x000000000000
#endif
#ifndef FXR_RX_CI_FAST_CSRS
#define FXR_RX_CI_FAST_CSRS			0x000000000000
#endif
#define FXR_NUM_CONTEXTS			256
#define FXR_NUM_PIDS				4096
#define FXR_MAX_CONTEXT				255
#define FXR_TX_CONTEXT_ENTRIES			128
#define FXR_TX_CONTEXT_MAX			127
#define FXR_RX_CONTEXT_ENTRIES			32
#define FXR_RX_CONTEXT_MAX			31
#define FXR_NUM_SL				32
#define FXR_MAX_SL				31
/*
* Table #3 of fxr_top - TX_CQ_ENTRY
* This CSR is used to describe the address region that is mapped to the transmit 
* command queues and uses the high bandwidth path from the host 
* interface.
*/
#define FXR_TX_CQ_ENTRY				(FXR_TX_CI_FAST_CSRS + 0x000000000000)
#define FXR_TX_CQ_ENTRY_RESETCSR		0x0000000000000000ull
#define FXR_TX_CQ_ENTRY_TX_CQ_ENTRY_SHIFT	0
#define FXR_TX_CQ_ENTRY_TX_CQ_ENTRY_MASK	0xFFFFFFFFFFFFFFFFull
#define FXR_TX_CQ_ENTRY_TX_CQ_ENTRY_SMASK	0xFFFFFFFFFFFFFFFFull
/*
* Table #3 of fxr_tx_ci_fast_csrs - RX_CQ_ENTRY
* This CSR is used to describe the address region that is mapped to the receive 
* command queues and uses the high bandwidth path from the host interface. The 
* address is not packed, so each command queue starts on an 8 KB boundary even 
* though the Command Queues have a capacity smaller than 8 KB.
*/
#define FXR_RX_CQ_ENTRY				(FXR_RX_CI_FAST_CSRS + 0x000000000000)
#define FXR_RX_CQ_ENTRY_RESETCSR		0x0000000000000000ull
#define FXR_RX_CQ_ENTRY_RX_CQ_ENTRY_SHIFT	0
#define FXR_RX_CQ_ENTRY_RX_CQ_ENTRY_MASK	0xFFFFFFFFFFFFFFFFull
#define FXR_RX_CQ_ENTRY_RX_CQ_ENTRY_SMASK	0xFFFFFFFFFFFFFFFFull

#endif 		/* DEF_FXR_FAST_PATH_SW_DEF */
