//                                                                             
// File:       fxr_top_map_top.h                                               
// Creator:    pvesvslx                                                        
// Time:       Thursday Feb 6, 2014 [2:28:50 pm]                               
//                                                                             
// Path:       /tmp/pvesvslx/nebulon_run/12340                                 
// Arguments:  /p/com/eda/denali/blueprint/3.7.4/Linux/blueprint -chdr -I      
//             /p/slx/eda/intel/nebulon/2.05_fdo/include -I                    
//             /p/slx/pvesv/fxr_autogen/fxr -xml fxr_top_map.rdl               
//                                                                             
// Sources:    /tmp/pvesvslx/nebulon_run/12340/fxr_top_map.rdl                 
//             /tmp/pvesvslx/nebulon_run/12340/fxr_rx_ci.rdl                   
//             /tmp/pvesvslx/nebulon_run/12340/fxr_pmon.rdlh                   
//             /tmp/pvesvslx/nebulon_run/12340/fxr_hifis.rdlh                  
//             /tmp/pvesvslx/nebulon_run/12340/fxr_at.rdlh                     
//             /tmp/pvesvslx/nebulon_run/12340/fxr_tx_ci.rdlh                  
//             /tmp/pvesvslx/nebulon_run/12340/fxr_tx_otr.rdlh                 
//             /tmp/pvesvslx/nebulon_run/12340/fxr_sma.rdlh                    
//             /tmp/pvesvslx/nebulon_run/12340/fxr_lm.rdlh                     
//             /tmp/pvesvslx/nebulon_run/12340/lib_udp.rdl                     
//             /tmp/pvesvslx/nebulon_run/12340/fxr_at.rdl                      
//             /tmp/pvesvslx/nebulon_run/12340/fxr_pmon.rdl                    
//             /tmp/pvesvslx/nebulon_run/12340/fxr_rx_ci.rdlh                  
//             /tmp/pvesvslx/nebulon_run/12340/fxr_tx_dma.rdlh                 
//             /tmp/pvesvslx/nebulon_run/12340/fxr_tx_otr.rdl                  
//             /tmp/pvesvslx/nebulon_run/12340/fxr_rx_hp.rdl                   
//             /tmp/pvesvslx/nebulon_run/12340/fxr_tx_dma.rdl                  
//             /tmp/pvesvslx/nebulon_run/12340/fxr_hifis.rdl                   
//             /tmp/pvesvslx/nebulon_run/12340/fxr_rx_hp.rdlh                  
//             /tmp/pvesvslx/nebulon_run/12340/fxr_sma.rdl                     
//             /tmp/pvesvslx/nebulon_run/12340/fxr_loca.rdl                    
//             /tmp/pvesvslx/nebulon_run/12340/fxr_loca.rdlh                   
//             /tmp/pvesvslx/nebulon_run/12340/fxr_tx_ci.rdl                   
//             /tmp/pvesvslx/nebulon_run/12340/fxr_lm.rdl                      
//             /p/com/eda/intel/nebulon/2.05p1/generators/generator_common.pm  
//             /p/com/eda/intel/nebulon/2.05p1/generators/xml.pm               
//             /p/com/eda/intel/nebulon/2.05p1/generators/walk_through.pm      
//             /p/com/eda/intel/nebulon/2.05p1/generators/chdr.pm              
//                                                                             
// Blueprint:   3.7.4 (Tue Jun 23 00:17:01 PDT 2009)                           
// Machine:    scci56220                                                       
// OS:         Linux 2.6.16.60-0.58.1.3835.0.PTF.638363-smp                    
// Description:                                                                
//                                                                             
// No Description Provided                                                     
//                                                                             
// Copyright (C) 2014 Denali Software Inc.  All rights reserved                
// THIS FILE IS AUTOMATICALLY GENERATED BY DENALI BLUEPRINT, DO NOT EDIT       
//                                                                             



#include "fxr_tx_ci_csrs.h"
#include "fxr_tx_otr_csrs.h"
#include "fxr_tx_dma_csrs.h"
#include "fxr_rx_ci_csrs.h"
#include "fxr_rx_hp_csrs.h"
#include "fxr_hifis_csrs.h"
#include "fxr_loca_csrs.h"
#include "fxr_pmon_csrs.h"
#include "fxr_sma_csrs.h"
#include "fxr_lm_csrs.h"
#include "fxr_at_csrs.h"


// begin top instantiation section
typedef struct {
  uint8_t         RSVD0[0x1000000];
  fxr_tx_ci_csrs_t fxr_tx_ci_csrs;
  uint8_t         RSVD1[0x7FFD8];
  fxr_tx_otr_csrs_t fxr_tx_otr_csrs;
  uint8_t         RSVD2[0x3FFFF8];
  fxr_tx_dma_csrs_t fxr_tx_dma_csrs;
  uint8_t         RSVD3[0x7DFF00];
  fxr_rx_ci_csrs_t fxr_rx_ci_csrs;
  uint8_t         RSVD4[0x101BE0];
  fxr_rx_hp_csrs_t fxr_rx_hp_csrs;
  uint8_t         RSVD5[0x0BBFD70];
  fxr_hifis_csrs_t fxr_hifis_csrs;
  uint8_t         RSVD6[0x1FFFF8];
  fxr_loca_csrs_t fxr_loca_csrs;
  uint8_t         RSVD7[0x2FFFF8];
  fxr_pmon_csrs_t fxr_pmon_csrs;
  uint8_t         RSVD8[0x7F000];
  fxr_sma_csrs_t fxr_sma_csrs;
  uint8_t         RSVD9[0x0FFFF8];
  fxr_lm_csrs_t fxr_lm_csrs;
  uint8_t         RSVD10[0x8FFFF8];
  fxr_at_csrs_t fxr_at_csrs;

} fxr_top_map_top;    // size: 28'h4180000
