/*
* -------------------------------------------------------------------
* --                      Intel Proprietary
* --              Copyright (C) 2014 Intel Corporation
* --                    All Rights Reserved
* -------------------------------------------------------------------
* --           Auto-generated by /p/slx/pvesv/wfr_autogen/utils/scripts/i_csrs/i_csrs.pl 
* --  i_csrs.pl Version 1.5 last modified on Monday 6/23/14 20:00:52
* --   /p/slx/pvesv/wfr_autogen/utils/scripts/i_csrs/i_csrs.pl -s WFR_PCIE=0 -C -o /p/slx/pvesv/wfr_autogen/wfr /p/slx/pvesv/wfr_autogen/SL1_fixed_xml/WFR/220_Memory_Map.xml /p/slx/pvesv/wfr_autogen/SL1_fixed_xml/DC/200_Memory_Map.xml  
* --------------------------------------------------------------------
*/

#ifndef DEF_WFR_CORE_SW_DEF
#define DEF_WFR_CORE_SW_DEF

#define WFR_PCIE		0
#define WFR_CORE		0x000000000000
#define WFR_CCE			(WFR_CORE + 0x000000000000)
#define WFR_ASIC		(WFR_CORE + 0x000000400000)
#define WFR_MISC		(WFR_CORE + 0x000000500000)
#define DC_TOP_CSRS		(WFR_CORE + 0x000000600000)
#define WFR_DEBUG		(WFR_CORE + 0x000000700000)
#define WFR_RXE			(WFR_CORE + 0x000001000000)
#define WFR_TXE			(WFR_CORE + 0x000001800000)
#define DCC_CSRS		(DC_TOP_CSRS + 0x000000000000)
#define DC_LCB_CSRS		(DC_TOP_CSRS + 0x000000001000)
#define DC_8051_CSRS		(DC_TOP_CSRS + 0x000000002000)

#endif 		/* DEF_WFR_CORE_SW_DEF */
