#
# Makefile for the Intel(R) Dynamic Load Balancer (dlb.ko) driver
#

obj-$(CONFIG_INTEL_DLB) := dlb.o

dlb-objs :=      \
  dlb_main.o     \
  dlb_intr.o     \
  dlb_ioctl.o    \
  dlb_mem.o      \
  dlb_pf_ops.o   \
  dlb_resource.o \
  dlb_sriov.o    \
  dlb_vf_ops.o   \
