# Makefile - Intel Omni-Path virtual Network Controller bus driver
# Copyright(c) 2015, Intel Corporation.
#
ccflags-y += -I $(src)/../Include
obj-m += opa_vnic_bus.o

opa_vnic_bus-y := opa_vnic_device.o
