#
# Makefile - Intel Omni-Path Gen2 network driver
# Copyright(c) 2014, Intel Corporation.
#
ccflags-y += -mno-fentry
ccflags-y += -I $(src)/../common
ccflags-y += -I $(src)/../common/uapi
obj-m = opa2_netdev.o
