#
# Makefile - Omni-Path HFI character device driver
# Copyright(c) 2014, Intel Corporation.
#
obj-m += opa2_user.o

opa2_user-y :=
opa2_user-y += device.o
opa2_user-y += file_ops.o
opa2_user-y += job.o
opa2_user-y += mpin.o
