/*
*------------------------------------------------------------------------------
*                                                                              
*  INTEL CONFIDENTIAL                                                          
*                                                                              
*  Copyright 2016 Intel Corporation All Rights Reserved.                 
*                                                                              
*  The source code contained or described herein and all documents related     
*  to the source code ("Material") are owned by Intel Corporation or its    
*  suppliers or licensors. Title to the Material remains with Intel            
*  Corporation or its suppliers and licensors. The Material contains trade     
*  secrets and proprietary and confidential information of Intel or its        
*  suppliers and licensors. The Material is protected by worldwide copyright   
*  and trade secret laws and treaty provisions. No part of the Material may    
*  be used, copied, reproduced, modified, published, uploaded, posted,         
*  transmitted, distributed, or disclosed in any way without Intel's prior     
*  express written permission.                                                 
*                                                                              
*  No license under any patent, copyright, trade secret or other intellectual  
*  property right is granted to or conferred upon you by disclosure or         
*  delivery of the Materials, either expressly, by implication, inducement,    
*  estoppel or otherwise. Any license under such intellectual property rights  
*  must be express and approved by Intel in writing.                           
*                                                                              
*------------------------------------------------------------------------------
*  Auto-generated by /nfs/sc/disks/slx_0108/pvesv/fxr_autogen/i_csrs.pl
*  i_csrs.pl Version 1.5 last modified on Thursday 1/7/16 17:24:50
*  /nfs/sc/disks/slx_0108/pvesv/fxr_autogen/i_csrs.pl -C -o /nfs/sc/disks/slx_0108/pvesv/fxr_autogen/fxr /nfs/sc/disks/slx_0108/pvesv/fxr_autogen/Fox_River/xml/300_Memory_Map.xml
*------------------------------------------------------------------------------
*/

#ifndef DEF_FXR_TOP_SW_DEF
#define DEF_FXR_TOP_SW_DEF

#ifndef FXR_TOP
#define FXR_TOP					0x000000000000
#endif
#define FXR_CONFIG_CSRS				(FXR_TOP + 0x000000000000)
#define FXR_TX_CI_FAST_CSRS			(FXR_TOP + 0x000000000000)
#define FXR_RX_CI_FAST_CSRS			(FXR_TOP + 0x000000400000)
#define FXR_AT_CSRS				(FXR_TOP + 0x000000800000)
#define FXR_IOMMU_CSRS				(FXR_TOP + 0x000000000000)
#define FXR_TX_CI_CID_CSRS			(FXR_TOP + 0x000000C00000)
#define FXR_TX_CI_CIC_CSRS			(FXR_TOP + 0x000001000000)
#define FXR_TX_OTR_PKT_TOP_CSRS			(FXR_TOP + 0x000001080000)
#define FXR_TX_OTR_MSG_TOP_CSRS			(FXR_TOP + 0x000001100000)
#define FXR_TX_DMA_CSRS				(FXR_TOP + 0x000001180000)
#define FXR_RX_CI_CID_CSRS			(FXR_TOP + 0x000001200000)
#define FXR_RX_CI_CIC_CSRS			(FXR_TOP + 0x000001380000)
#define FXR_RX_HP_CSRS				(FXR_TOP + 0x000001400000)
#define FXR_RX_E2E_CSRS				(FXR_TOP + 0x000001480000)
#define FXR_RX_DMA_CSRS				(FXR_TOP + 0x000001500000)
#define FXR_RX_HIARB_CSRS			(FXR_TOP + 0x000001580000)
#define FXR_RX_ET_CSRS				(FXR_TOP + 0x000001600000)
#define FXR_LOCA_CSRS				(FXR_TOP + 0x000001800000)
#define FXR_HIFIS_CSRS				(FXR_TOP + 0x000001A00000)
#define FXR_PCIM_CSRS				(FXR_TOP + 0x000001A80000)
#define FXR_PCIM_MSTR				(FXR_TOP + 0x000000000000)
#define FXR_LM_CSRS				(FXR_TOP + 0x000001B00000)
#define FXR_LM_CM0_CSRS				(FXR_TOP + 0x000001B40000)
#define FXR_LM_FPC0_CSRS			(FXR_TOP + 0x000001B80000)
#define FXR_LM_TP0_CSRS				(FXR_TOP + 0x000001BC0000)
#define FXR_LM_CM1_CSRS				(FXR_TOP + 0x000001C40000)
#define FXR_LM_FPC1_CSRS			(FXR_TOP + 0x000001C80000)
#define FXR_LM_TP1_CSRS				(FXR_TOP + 0x000001CC0000)
#define FXR_PMON_CSRS				(FXR_TOP + 0x000001D00000)
#define FXR_CHS_DFD_CAP_CSRS			(FXR_TOP + 0x000001D80000)
#define FXR_LOCA_DFD_CAP_CSRS			(FXR_TOP + 0x000001D81000)
#define FXR_LOCA_DFD_CSRS			(FXR_TOP + 0x000001D82000)
#define FXR_LM_DFD_CSRS				(FXR_TOP + 0x000001D83000)
#define FXR_AT_DFD_CSRS				(FXR_TOP + 0x000001D84000)
#define FXR_AT_IOMMU_DFD_CSRS			(FXR_TOP + 0x000001D85000)
#define FXR_HI_HIFIS_DFD_CSRS			(FXR_TOP + 0x000001D86000)
#define FXR_HI_PCIM_DFD_CSRS			(FXR_TOP + 0x000001D87000)
#define FXR_RX_CI_DFD_CSRS			(FXR_TOP + 0x000001D88000)
#define FXR_RX_DMA_DFD_CSRS			(FXR_TOP + 0x000001D89000)
#define FXR_RX_E2E_DFD_CSRS			(FXR_TOP + 0x000001D8A000)
#define FXR_RX_ET_DFD_CSRS			(FXR_TOP + 0x000001D8B000)
#define FXR_RX_HIARB_DFD_CSRS			(FXR_TOP + 0x000001D8C000)
#define FXR_RX_HP_DFD_CSRS			(FXR_TOP + 0x000001D8D000)
#define FXR_TX_CIC_DFD_CSRS			(FXR_TOP + 0x000001D8E000)
#define FXR_TX_CID_DFD_CSRS			(FXR_TOP + 0x000001D8F000)
#define FXR_TX_DMA_DFD_CSRS			(FXR_TOP + 0x000001D90000)
#define FXR_TX_OTR_BPE_TOP_DFD_CSRS		(FXR_TOP + 0x000001D91000)
#define FXR_TX_OTR_MSG_TOP_DFD_CSRS		(FXR_TOP + 0x000001D92000)
#define FXR_TX_OTR_PKT_TOP_DFD_CSRS		(FXR_TOP + 0x000001D93000)
#define FXR_DFD_RTB12_CSRS			(FXR_TOP + 0x000001D94000)
#define FXR_DFD_RTB18_CSRS			(FXR_TOP + 0x000001D96000)
#define FXR_URC_CSRS				(FXR_TOP + 0x000001E80000)
#define FXR_FZC_LCB0_CSRS			(FXR_TOP + 0x000002000000)
#define FXR_FZC_LCB1_CSRS			(FXR_TOP + 0x000002004000)
#define FXR_FZC_OPIO_CSRS			(FXR_TOP + 0x000002008000)
#define FXR_FZC_LPHY				(FXR_TOP + 0x000002010000)
#define FXR_FZC_AFE				(FXR_TOP + 0x000002020000)
#define FXR_FZC_FXRSB2MNH			(FXR_TOP + 0x000000000000)
#define FXR_MNH_LPHY				(FXR_TOP + 0x000002080000)
#define FXR_MNH_AFE				(FXR_TOP + 0x000002090000)
#define FXR_MNH_OPIO_CSRS			(FXR_TOP + 0x0000020A0000)
#define FXR_MNH_S0_8051_CSRS			(FXR_TOP + 0x0000020B0000)
#define FXR_MNH_S0_BCC_CSRS			(FXR_TOP + 0x0000020B4000)
#define FXR_MNH_S0_SNUP_CSRS			(FXR_TOP + 0x0000020B8000)
#define FXR_MNH_S0_SNDN_CSRS			(FXR_TOP + 0x0000020BC000)
#define FXR_MNH_S1_8051_CSRS			(FXR_TOP + 0x0000020C0000)
#define FXR_MNH_S1_BCC_CSRS			(FXR_TOP + 0x0000020C4000)
#define FXR_MNH_S1_SNUP_CSRS			(FXR_TOP + 0x0000020C8000)
#define FXR_MNH_S1_SNDN_CSRS			(FXR_TOP + 0x0000020CC000)
#define FXR_MNH_MISC_CSRS			(FXR_TOP + 0x0000020D0000)
#define FXR_MNH_FUSE_AGG			(FXR_TOP + 0x0000020D8000)
#define FXR_MNH_EBC				(FXR_TOP + 0x000000000000)
#define FXR_MNH_DFX_AGG				(FXR_TOP + 0x000000000000)
#define FXR_MNH_FUSE_CONTROLLER			(FXR_TOP + 0x000000000000)
#define FXR_MNH_TAP2IOSF			(FXR_TOP + 0x000000000000)
#define FXR_TOP_SIZE				0x4000000
#define FXR_CONFIG_CSRS_EP			0x01
#define FXR_TX_CI_FAST_CSRS_SIZE		0x0180000
#define FXR_TX_CI_FAST_CSRS_EP			HPI
#define FXR_RX_CI_FAST_CSRS_SIZE		0x0180000
#define FXR_RX_CI_FAST_CSRS_EP			HPI
#define FXR_AT_CSRS_SIZE			0x0400000
#define FXR_AT_CSRS_EP				0x07
#define FXR_IOMMU_CSRS_EP			0x06
#define FXR_TX_CI_CID_CSRS_SIZE			0x0400000
#define FXR_TX_CI_CID_CSRS_EP			0x08
#define FXR_TX_CI_CIC_CSRS_SIZE			0x0080000
#define FXR_TX_CI_CIC_CSRS_EP			0x08
#define FXR_TX_OTR_PKT_TOP_CSRS_SIZE		0x0080000
#define FXR_TX_OTR_PKT_TOP_CSRS_EP		0x09
#define FXR_TX_OTR_MSG_TOP_CSRS_SIZE		0x0080000
#define FXR_TX_OTR_MSG_TOP_CSRS_EP		0x09
#define FXR_TX_DMA_CSRS_SIZE			0x0080000
#define FXR_TX_DMA_CSRS_EP			0x0a
#define FXR_RX_CI_CID_CSRS_SIZE			0x0180000
#define FXR_RX_CI_CID_CSRS_EP			0x0e
#define FXR_RX_CI_CIC_CSRS_SIZE			0x0080000
#define FXR_RX_CI_CIC_CSRS_EP			0x0e
#define FXR_RX_HP_CSRS_SIZE			0x0080000
#define FXR_RX_HP_CSRS_EP			0x0f
#define FXR_RX_E2E_CSRS_SIZE			0x0080000
#define FXR_RX_E2E_CSRS_EP			0x11
#define FXR_RX_DMA_CSRS_SIZE			0x0080000
#define FXR_RX_DMA_CSRS_EP			0x0c
#define FXR_RX_HIARB_CSRS_SIZE			0x0080000
#define FXR_RX_HIARB_CSRS_EP			0x0b
#define FXR_RX_ET_CSRS_SIZE			0x0080000
#define FXR_RX_ET_CSRS_EP			0x0d
#define FXR_LOCA_CSRS_SIZE			0x0200000
#define FXR_LOCA_CSRS_EP			0x03
#define FXR_HIFIS_CSRS_SIZE			0x0080000
#define FXR_HIFIS_CSRS_EP			0x02
#define FXR_PCIM_CSRS_SIZE			0x0080000
#define FXR_PCIM_CSRS_EP			0x01
#define FXR_PCIM_MSTR_EP			0x00
#define FXR_LM_CSRS_SIZE			0x0040000
#define FXR_LM_CSRS_EP				0x13
#define FXR_LM_CM0_CSRS_SIZE			0x0040000
#define FXR_LM_CM0_CSRS_EP			0x13
#define FXR_LM_FPC0_CSRS_SIZE			0x0040000
#define FXR_LM_FPC0_CSRS_EP			0x13
#define FXR_LM_TP0_CSRS_SIZE			0x0040000
#define FXR_LM_TP0_CSRS_EP			0x13
#define FXR_LM_CM1_CSRS_SIZE			0x0040000
#define FXR_LM_CM1_CSRS_EP			0x13
#define FXR_LM_FPC1_CSRS_SIZE			0x0040000
#define FXR_LM_FPC1_CSRS_EP			0x13
#define FXR_LM_TP1_CSRS_SIZE			0x0040000
#define FXR_LM_TP1_CSRS_EP			0x13
#define FXR_PMON_CSRS_SIZE			0x0080000
#define FXR_PMON_CSRS_EP			0x10
#define FXR_CHS_DFD_CAP_CSRS_SIZE		0x0001000
#define FXR_CHS_DFD_CAP_CSRS_EP			0x2C
#define FXR_LOCA_DFD_CAP_CSRS_SIZE		0x0001000
#define FXR_LOCA_DFD_CAP_CSRS_EP		0x2c
#define FXR_LOCA_DFD_CSRS_SIZE			0x0001000
#define FXR_LOCA_DFD_CSRS_EP			0x03
#define FXR_LM_DFD_CSRS_SIZE			0x0001000
#define FXR_LM_DFD_CSRS_EP			0x13
#define FXR_AT_DFD_CSRS_SIZE			0x0001000
#define FXR_AT_DFD_CSRS_EP			0x07
#define FXR_AT_IOMMU_DFD_CSRS_SIZE		0x0001000
#define FXR_AT_IOMMU_DFD_CSRS_EP		0x05
#define FXR_HI_HIFIS_DFD_CSRS_SIZE		0x0001000
#define FXR_HI_HIFIS_DFD_CSRS_EP		0x02
#define FXR_HI_PCIM_DFD_CSRS_SIZE		0x0001000
#define FXR_HI_PCIM_DFD_CSRS_EP			0x01
#define FXR_RX_CI_DFD_CSRS_SIZE			0x0001000
#define FXR_RX_CI_DFD_CSRS_EP			0x0e
#define FXR_RX_DMA_DFD_CSRS_SIZE		0x0001000
#define FXR_RX_DMA_DFD_CSRS_EP			0x0c
#define FXR_RX_E2E_DFD_CSRS_SIZE		0x0001000
#define FXR_RX_E2E_DFD_CSRS_EP			0x11
#define FXR_RX_ET_DFD_CSRS_SIZE			0x0001000
#define FXR_RX_ET_DFD_CSRS_EP			0x0d
#define FXR_RX_HIARB_DFD_CSRS_SIZE		0x0001000
#define FXR_RX_HIARB_DFD_CSRS_EP		0x0b
#define FXR_RX_HP_DFD_CSRS_SIZE			0x0001000
#define FXR_RX_HP_DFD_CSRS_EP			0x0f
#define FXR_TX_CIC_DFD_CSRS_SIZE		0x0001000
#define FXR_TX_CIC_DFD_CSRS_EP			0x08
#define FXR_TX_CID_DFD_CSRS_SIZE		0x0001000
#define FXR_TX_CID_DFD_CSRS_EP			0x08
#define FXR_TX_DMA_DFD_CSRS_SIZE		0x0001000
#define FXR_TX_DMA_DFD_CSRS_EP			0x0a
#define FXR_TX_OTR_BPE_TOP_DFD_CSRS_SIZE	0x0001000
#define FXR_TX_OTR_BPE_TOP_DFD_CSRS_EP		0x09
#define FXR_TX_OTR_MSG_TOP_DFD_CSRS_SIZE	0x0001000
#define FXR_TX_OTR_MSG_TOP_DFD_CSRS_EP		0x09
#define FXR_TX_OTR_PKT_TOP_DFD_CSRS_SIZE	0x0001000
#define FXR_TX_OTR_PKT_TOP_DFD_CSRS_EP		0x09
#define FXR_DFD_RTB12_CSRS_SIZE			0x0002000
#define FXR_DFD_RTB12_CSRS_EP			0x2C
#define FXR_DFD_RTB18_CSRS_SIZE			0x0002000
#define FXR_DFD_RTB18_CSRS_EP			0x2c
#define FXR_URC_CSRS_SIZE			0x0080000
#define FXR_URC_CSRS_EP				0x1C
#define FXR_FZC_LCB0_CSRS_SIZE			0x0004000
#define FXR_FZC_LCB0_CSRS_EP			0x14
#define FXR_FZC_LCB1_CSRS_SIZE			0x0004000
#define FXR_FZC_LCB1_CSRS_EP			0x14
#define FXR_FZC_OPIO_CSRS_SIZE			0x0008000
#define FXR_FZC_OPIO_CSRS_EP			0x14
#define FXR_FZC_LPHY_SIZE			0x0010000
#define FXR_FZC_LPHY_EP				0x15
#define FXR_FZC_AFE_SIZE			0x0010000
#define FXR_FZC_AFE_EP				0x16
#define FXR_FZC_FXRSB2MNH_EP			0xE0
#define FXR_MNH_LPHY_SIZE			0x0010000
#define FXR_MNH_LPHY_EP				0xE1
#define FXR_MNH_AFE_SIZE			0x0010000
#define FXR_MNH_AFE_EP				0xE2
#define FXR_MNH_OPIO_CSRS_SIZE			0x0008000
#define FXR_MNH_OPIO_CSRS_EP			0xE3
#define FXR_MNH_S0_8051_CSRS_SIZE		0x0004000
#define FXR_MNH_S0_8051_CSRS_EP			0xE4
#define FXR_MNH_S0_BCC_CSRS_SIZE		0x0004000
#define FXR_MNH_S0_BCC_CSRS_EP			0xE4
#define FXR_MNH_S0_SNUP_CSRS_SIZE		0x0004000
#define FXR_MNH_S0_SNUP_CSRS_EP			0xE4
#define FXR_MNH_S0_SNDN_CSRS_SIZE		0x0004000
#define FXR_MNH_S0_SNDN_CSRS_EP			0xE4
#define FXR_MNH_S1_8051_CSRS_SIZE		0x0004000
#define FXR_MNH_S1_8051_CSRS_EP			0xE5
#define FXR_MNH_S1_BCC_CSRS_SIZE		0x0004000
#define FXR_MNH_S1_BCC_CSRS_EP			0xE5
#define FXR_MNH_S1_SNUP_CSRS_SIZE		0x0004000
#define FXR_MNH_S1_SNUP_CSRS_EP			0xE5
#define FXR_MNH_S1_SNDN_CSRS_SIZE		0x0004000
#define FXR_MNH_S1_SNDN_CSRS_EP			0xE5
#define FXR_MNH_MISC_CSRS_SIZE			0x0008000
#define FXR_MNH_MISC_CSRS_EP			0xE6
#define FXR_MNH_FUSE_AGG_SIZE			0x0008000
#define FXR_MNH_FUSE_AGG_EP			0xE6
#define FXR_NUM_CONTEXTS			192
#define FXR_NUM_PIDS				4096
#define FXR_MAX_CONTEXT				191
#define FXR_TX_CONTEXT_ENTRIES			128
#define FXR_TX_CONTEXT_MAX			127
#define FXR_RX_CONTEXT_ENTRIES			16
#define FXR_RX_CONTEXT_MAX			15
#define FXR_NUM_SL				32
#define FXR_MAX_SL				31

#endif 		/* DEF_FXR_TOP_SW_DEF */
