/*
*------------------------------------------------------------------------------
*                                                                              
*  INTEL CONFIDENTIAL                                                          
*                                                                              
*  Copyright 2016 Intel Corporation All Rights Reserved.                 
*                                                                              
*  The source code contained or described herein and all documents related     
*  to the source code ("Material") are owned by Intel Corporation or its    
*  suppliers or licensors. Title to the Material remains with Intel            
*  Corporation or its suppliers and licensors. The Material contains trade     
*  secrets and proprietary and confidential information of Intel or its        
*  suppliers and licensors. The Material is protected by worldwide copyright   
*  and trade secret laws and treaty provisions. No part of the Material may    
*  be used, copied, reproduced, modified, published, uploaded, posted,         
*  transmitted, distributed, or disclosed in any way without Intel's prior     
*  express written permission.                                                 
*                                                                              
*  No license under any patent, copyright, trade secret or other intellectual  
*  property right is granted to or conferred upon you by disclosure or         
*  delivery of the Materials, either expressly, by implication, inducement,    
*  estoppel or otherwise. Any license under such intellectual property rights  
*  must be express and approved by Intel in writing.                           
*                                                                              
*------------------------------------------------------------------------------
*  Auto-generated by /nfs/sc/disks/slx_0108/pvesv/fxr_autogen/i_csrs.pl
*  i_csrs.pl Version 1.5 last modified on Thursday 1/7/16 17:24:50
*  /nfs/sc/disks/slx_0108/pvesv/fxr_autogen/i_csrs.pl -C -R -ST fxr_hifis -o /nfs/sc/disks/slx_0108/pvesv/fxr_autogen/fxr /nfs/sc/disks/slx_0108/pvesv/fxr_autogen/repo_xml/300_Memory_Map.xml /nfs/sc/disks/slx_0108/pvesv/fxr_autogen/repo_xml/340_Memory_Map_HIFIS.xml
*------------------------------------------------------------------------------
*/

#ifndef DEF_FXR_HIFIS_SW_DEF
#define DEF_FXR_HIFIS_SW_DEF

#ifndef FXR_HIFIS_CSRS
#define FXR_HIFIS_CSRS						0x000000000000
#endif
#define FXR_NUM_CONTEXTS					192
#define FXR_NUM_PIDS						4096
#define FXR_MAX_CONTEXT						191
#define FXR_TX_CONTEXT_ENTRIES					128
#define FXR_TX_CONTEXT_MAX					127
#define FXR_RX_CONTEXT_ENTRIES					16
#define FXR_RX_CONTEXT_MAX					15
#define FXR_NUM_SL						32
#define FXR_MAX_SL						31
#define HIFIS_IN_CFG_BASE					0
#define HIFIS_ERR_BASE						512
/*
* Table #4 of fxr_top - HIFIS_IN_CONTROL
* The HIFIS IN CONTROL register enables selected modes and operations within the 
* 1.2Ghz clock domain of the HIFIS Block.
*/
#define FXR_HIFIS_IN_CONTROL					(FXR_HIFIS_CSRS + 0x000000000000)
#define FXR_HIFIS_IN_CONTROL_RESETCSR				0x0000000000000000ull
#define FXR_HIFIS_IN_CONTROL_DEBUG_SPARE_SHIFT			0
#define FXR_HIFIS_IN_CONTROL_DEBUG_SPARE_MASK			0x1FFFFFFFFFFFull
#define FXR_HIFIS_IN_CONTROL_DEBUG_SPARE_SMASK			0x1FFFFFFFFFFFull
/*
* Table #5 of fxr_top - HIFIS_IN_CFG
* The HIFIS IN CFG register enables selected modes and operations within the 
* 1.2Ghz clock domain of the HIFIS Block.
*/
#define FXR_HIFIS_IN_CFG					(FXR_HIFIS_CSRS + 0x000000000008)
#define FXR_HIFIS_IN_CFG_RESETCSR				0x0000539400000000ull
#define FXR_HIFIS_IN_CFG_RX_HIFIS_PKT_CREDIT_MAX_SHIFT		42
#define FXR_HIFIS_IN_CFG_RX_HIFIS_PKT_CREDIT_MAX_MASK		0x1Full
#define FXR_HIFIS_IN_CFG_RX_HIFIS_PKT_CREDIT_MAX_SMASK		0x7C0000000000ull
#define FXR_HIFIS_IN_CFG_TX_HIFIS_PKT_CREDIT_MAX_SHIFT		37
#define FXR_HIFIS_IN_CFG_TX_HIFIS_PKT_CREDIT_MAX_MASK		0x1Full
#define FXR_HIFIS_IN_CFG_TX_HIFIS_PKT_CREDIT_MAX_SMASK		0x3E000000000ull
#define FXR_HIFIS_IN_CFG_AT_HIFIS_PKT_CREDIT_MAX_SHIFT		32
#define FXR_HIFIS_IN_CFG_AT_HIFIS_PKT_CREDIT_MAX_MASK		0x1Full
#define FXR_HIFIS_IN_CFG_AT_HIFIS_PKT_CREDIT_MAX_SMASK		0x1F00000000ull
/*
* Table #6 of fxr_top - HIFIS_OUT_CFG1
* The HIFIS OUT CFG1 register enables selected modes and operations within the 
* 1.2Ghz clock domain of the HIFIS Block.
*/
#define FXR_HIFIS_OUT_CFG1					(FXR_HIFIS_CSRS + 0x000000000010)
#define FXR_HIFIS_OUT_CFG1_RESETCSR				0x00820C106050AAAAull
#define FXR_HIFIS_OUT_CFG1_CREDIT_EN_RX_SHIFT			55
#define FXR_HIFIS_OUT_CFG1_CREDIT_EN_RX_MASK			0x1ull
#define FXR_HIFIS_OUT_CFG1_CREDIT_EN_RX_SMASK			0x80000000000000ull
#define FXR_HIFIS_OUT_CFG1_CREDITS_AVAIL_RX_REQ_SHIFT		49
#define FXR_HIFIS_OUT_CFG1_CREDITS_AVAIL_RX_REQ_MASK		0x3Full
#define FXR_HIFIS_OUT_CFG1_CREDITS_AVAIL_RX_REQ_SMASK		0x7E000000000000ull
#define FXR_HIFIS_OUT_CFG1_CREDITS_AVAIL_RX_RSP_SHIFT		43
#define FXR_HIFIS_OUT_CFG1_CREDITS_AVAIL_RX_RSP_MASK		0x3Full
#define FXR_HIFIS_OUT_CFG1_CREDITS_AVAIL_RX_RSP_SMASK		0x1F80000000000ull
#define FXR_HIFIS_OUT_CFG1_CREDIT_EN_TX_SHIFT			42
#define FXR_HIFIS_OUT_CFG1_CREDIT_EN_TX_MASK			0x1ull
#define FXR_HIFIS_OUT_CFG1_CREDIT_EN_TX_SMASK			0x40000000000ull
#define FXR_HIFIS_OUT_CFG1_CREDITS_AVAIL_TX_REQ_SHIFT		36
#define FXR_HIFIS_OUT_CFG1_CREDITS_AVAIL_TX_REQ_MASK		0x3Full
#define FXR_HIFIS_OUT_CFG1_CREDITS_AVAIL_TX_REQ_SMASK		0x3F000000000ull
#define FXR_HIFIS_OUT_CFG1_CREDITS_AVAIL_TX_RSP_SHIFT		30
#define FXR_HIFIS_OUT_CFG1_CREDITS_AVAIL_TX_RSP_MASK		0x3Full
#define FXR_HIFIS_OUT_CFG1_CREDITS_AVAIL_TX_RSP_SMASK		0xFC0000000ull
#define FXR_HIFIS_OUT_CFG1_CREDIT_EN_AT_SHIFT			29
#define FXR_HIFIS_OUT_CFG1_CREDIT_EN_AT_MASK			0x1ull
#define FXR_HIFIS_OUT_CFG1_CREDIT_EN_AT_SMASK			0x20000000ull
#define FXR_HIFIS_OUT_CFG1_CREDITS_AVAIL_AT_RSP_SHIFT		22
#define FXR_HIFIS_OUT_CFG1_CREDITS_AVAIL_AT_RSP_MASK		0x7Full
#define FXR_HIFIS_OUT_CFG1_CREDITS_AVAIL_AT_RSP_SMASK		0x1FC00000ull
#define FXR_HIFIS_OUT_CFG1_PCIM_HIFIS_PKT_CREDIT_MAX_SHIFT	16
#define FXR_HIFIS_OUT_CFG1_PCIM_HIFIS_PKT_CREDIT_MAX_MASK	0x3Full
#define FXR_HIFIS_OUT_CFG1_PCIM_HIFIS_PKT_CREDIT_MAX_SMASK	0x3F0000ull
#define FXR_HIFIS_OUT_CFG1_ARB_CNTL_AT_SHIFT			0
#define FXR_HIFIS_OUT_CFG1_ARB_CNTL_AT_MASK			0xFFFFull
#define FXR_HIFIS_OUT_CFG1_ARB_CNTL_AT_SMASK			0xFFFFull
/*
* Table #7 of fxr_top - HIFIS_OUT_CFG2
* The HIFIS OUT CFG2 register enables selected modes and operations within the 
* 1.2Ghz clock domain of the HIFIS Block.
*/
#define FXR_HIFIS_OUT_CFG2					(FXR_HIFIS_CSRS + 0x000000000018)
#define FXR_HIFIS_OUT_CFG2_RESETCSR				0xAAAA4924AAAA4924ull
#define FXR_HIFIS_OUT_CFG2_ARB_CNTL_RX_A_SHIFT			48
#define FXR_HIFIS_OUT_CFG2_ARB_CNTL_RX_A_MASK			0xFFFFull
#define FXR_HIFIS_OUT_CFG2_ARB_CNTL_RX_A_SMASK			0xFFFF000000000000ull
#define FXR_HIFIS_OUT_CFG2_ARB_CNTL_RX_B_SHIFT			32
#define FXR_HIFIS_OUT_CFG2_ARB_CNTL_RX_B_MASK			0xFFFFull
#define FXR_HIFIS_OUT_CFG2_ARB_CNTL_RX_B_SMASK			0xFFFF00000000ull
#define FXR_HIFIS_OUT_CFG2_ARB_CNTL_TX_A_SHIFT			16
#define FXR_HIFIS_OUT_CFG2_ARB_CNTL_TX_A_MASK			0xFFFFull
#define FXR_HIFIS_OUT_CFG2_ARB_CNTL_TX_A_SMASK			0xFFFF0000ull
#define FXR_HIFIS_OUT_CFG2_ARB_CNTL_TX_B_SHIFT			0
#define FXR_HIFIS_OUT_CFG2_ARB_CNTL_TX_B_MASK			0xFFFFull
#define FXR_HIFIS_OUT_CFG2_ARB_CNTL_TX_B_SMASK			0xFFFFull
/*
* Table #8 of fxr_top - HIFIS_ERR_STS
* This is the Error Status CSR. Bits are set by hardware or by writing to the 
* HIFIS_ERR_FRC CSR. Bits are cleared by writing to the HIFIS_ERR_CLR 
* CSR.
*/
#define FXR_HIFIS_ERR_STS					(FXR_HIFIS_CSRS + 0x000000000200)
#define FXR_HIFIS_ERR_STS_RESETCSR				0x0000000000000000ull
#define FXR_HIFIS_ERR_STS_ADM_HDR_SBE_SHIFT			4
#define FXR_HIFIS_ERR_STS_ADM_HDR_SBE_MASK			0x1ull
#define FXR_HIFIS_ERR_STS_ADM_HDR_SBE_SMASK			0x10ull
#define FXR_HIFIS_ERR_STS_ADM_HDR_MBE_SHIFT			3
#define FXR_HIFIS_ERR_STS_ADM_HDR_MBE_MASK			0x1ull
#define FXR_HIFIS_ERR_STS_ADM_HDR_MBE_SMASK			0x8ull
#define FXR_HIFIS_ERR_STS_IMI_HDR_SBE_SHIFT			2
#define FXR_HIFIS_ERR_STS_IMI_HDR_SBE_MASK			0x1ull
#define FXR_HIFIS_ERR_STS_IMI_HDR_SBE_SMASK			0x4ull
#define FXR_HIFIS_ERR_STS_IMI_HDR_MBE_SHIFT			1
#define FXR_HIFIS_ERR_STS_IMI_HDR_MBE_MASK			0x1ull
#define FXR_HIFIS_ERR_STS_IMI_HDR_MBE_SMASK			0x2ull
#define FXR_HIFIS_ERR_STS_PCIM_Q_ERR_SHIFT			0
#define FXR_HIFIS_ERR_STS_PCIM_Q_ERR_MASK			0x1ull
#define FXR_HIFIS_ERR_STS_PCIM_Q_ERR_SMASK			0x1ull
/*
* Table #9 of fxr_top - HIFIS_ERR_CLR
* This is the Error Clear CSR. Writing a 1 to a valid bit will clear the 
* corresponding bit in the HIFIS_ERR_STS CSR.
*/
#define FXR_HIFIS_ERR_CLR					(FXR_HIFIS_CSRS + 0x000000000208)
#define FXR_HIFIS_ERR_CLR_RESETCSR				0x0000000000000000ull
#define FXR_HIFIS_ERR_CLR_EVENTS_SHIFT				0
#define FXR_HIFIS_ERR_CLR_EVENTS_MASK				0xFFFFFFFFFFFFFFFFull
#define FXR_HIFIS_ERR_CLR_EVENTS_SMASK				0xFFFFFFFFFFFFFFFFull
/*
* Table #10 of fxr_top - HIFIS_ERR_FRC
* This is the Error Force CSR. Writing a 1 to a valid bit will set the 
* corresponding bit in the HIFIS_ERR_STS CSR.
*/
#define FXR_HIFIS_ERR_FRC					(FXR_HIFIS_CSRS + 0x000000000210)
#define FXR_HIFIS_ERR_FRC_RESETCSR				0x0000000000000000ull
#define FXR_HIFIS_ERR_FRC_EVENTS_SHIFT				0
#define FXR_HIFIS_ERR_FRC_EVENTS_MASK				0xFFFFFFFFFFFFFFFFull
#define FXR_HIFIS_ERR_FRC_EVENTS_SMASK				0xFFFFFFFFFFFFFFFFull
/*
* Table #11 of fxr_top - HIFIS_ERR_EN_HOST
* This is the Error Enable for the Host Interrupt. If a bit is set, the 
* corresponding error bit in HIFIS_ERR_STS will cause an interrupt on the HOST 
* interrupt signal.
*/
#define FXR_HIFIS_ERR_EN_HOST					(FXR_HIFIS_CSRS + 0x000000000218)
#define FXR_HIFIS_ERR_EN_HOST_RESETCSR				0x0000000000000000ull
#define FXR_HIFIS_ERR_EN_HOST_EVENTS_SHIFT			0
#define FXR_HIFIS_ERR_EN_HOST_EVENTS_MASK			0x1Full
#define FXR_HIFIS_ERR_EN_HOST_EVENTS_SMASK			0x1Full
/*
* Table #12 of fxr_top - HIFIS_ERR_FIRST_HOST
* This is the First Error CSR for the Host Interrupt. When this CSR is clear, it 
* will capture the next HIFIS_ERR_STS value when a new HOST Interrupt 
* occurs.
*/
#define FXR_HIFIS_ERR_FIRST_HOST				(FXR_HIFIS_CSRS + 0x000000000220)
#define FXR_HIFIS_ERR_FIRST_HOST_RESETCSR			0x0000000000000000ull
#define FXR_HIFIS_ERR_FIRST_HOST_EVENTS_SHIFT			0
#define FXR_HIFIS_ERR_FIRST_HOST_EVENTS_MASK			0x1Full
#define FXR_HIFIS_ERR_FIRST_HOST_EVENTS_SMASK			0x1Full
/*
* Table #13 of fxr_top - HIFIS_ERR_EN_BMC
* This is the Error Enable for the BMC Interrupt. If a bit is set, the 
* corresponding error bit in HIFIS_ERR_STS will cause an interrupt on the BMC 
* interrupt signal.
*/
#define FXR_HIFIS_ERR_EN_BMC					(FXR_HIFIS_CSRS + 0x000000000228)
#define FXR_HIFIS_ERR_EN_BMC_RESETCSR				0x0000000000000000ull
#define FXR_HIFIS_ERR_EN_BMC_EVENTS_SHIFT			0
#define FXR_HIFIS_ERR_EN_BMC_EVENTS_MASK			0x1Full
#define FXR_HIFIS_ERR_EN_BMC_EVENTS_SMASK			0x1Full
/*
* Table #14 of fxr_top - HIFIS_ERR_FIRST_BMC
* This is the First Error CSR for the BMC Interrupt. When this CSR is clear, it 
* will capture the next HIFIS_ERR_STS value when a new BMC Interrupt 
* occurs.
*/
#define FXR_HIFIS_ERR_FIRST_BMC					(FXR_HIFIS_CSRS + 0x000000000230)
#define FXR_HIFIS_ERR_FIRST_BMC_RESETCSR			0x0000000000000000ull
#define FXR_HIFIS_ERR_FIRST_BMC_EVENTS_SHIFT			0
#define FXR_HIFIS_ERR_FIRST_BMC_EVENTS_MASK			0x1Full
#define FXR_HIFIS_ERR_FIRST_BMC_EVENTS_SMASK			0x1Full
/*
* Table #15 of fxr_top - HIFIS_ERR_EN_QUAR
* This is the Error Enable for the Quarantine Interrupt. If a bit is set, the 
* corresponding error bit in HIFIS_ERR_STS will cause an interrupt on the QUAR 
* interrupt signal.
*/
#define FXR_HIFIS_ERR_EN_QUAR					(FXR_HIFIS_CSRS + 0x000000000238)
#define FXR_HIFIS_ERR_EN_QUAR_RESETCSR				0x0000000000000000ull
#define FXR_HIFIS_ERR_EN_QUAR_EVENTS_SHIFT			0
#define FXR_HIFIS_ERR_EN_QUAR_EVENTS_MASK			0x1Full
#define FXR_HIFIS_ERR_EN_QUAR_EVENTS_SMASK			0x1Full
/*
* Table #16 of fxr_top - HIFIS_ERR_FIRST_QUAR
* This is the First Error CSR for the Quarantine Interrupt. When this CSR is 
* clear, it will capture the next HIFIS_ERR_STS value when a new QUAR Interrupt 
* occurs.
*/
#define FXR_HIFIS_ERR_FIRST_QUAR				(FXR_HIFIS_CSRS + 0x000000000240)
#define FXR_HIFIS_ERR_FIRST_QUAR_RESETCSR			0x0000000000000000ull
#define FXR_HIFIS_ERR_FIRST_QUAR_EVENTS_SHIFT			0
#define FXR_HIFIS_ERR_FIRST_QUAR_EVENTS_MASK			0x1Full
#define FXR_HIFIS_ERR_FIRST_QUAR_EVENTS_SMASK			0x1Full
/*
* Table #17 of fxr_top - HIFIS_ERR_INFO
* Error Info for TBD. (There may be many Error Info Registers.)
*/
#define FXR_HIFIS_ERR_INFO					(FXR_HIFIS_CSRS + 0x000000000248)
#define FXR_HIFIS_ERR_INFO_RESETCSR				0x0000000000000000ull
#define FXR_HIFIS_ERR_INFO_ADM_HDR_SYND_SHIFT			8
#define FXR_HIFIS_ERR_INFO_ADM_HDR_SYND_MASK			0xFFull
#define FXR_HIFIS_ERR_INFO_ADM_HDR_SYND_SMASK			0xFF00ull
#define FXR_HIFIS_ERR_INFO_IMI_HDR_SYND_SHIFT			0
#define FXR_HIFIS_ERR_INFO_IMI_HDR_SYND_MASK			0xFFull
#define FXR_HIFIS_ERR_INFO_IMI_HDR_SYND_SMASK			0xFFull

#endif 		/* DEF_FXR_HIFIS_SW_DEF */
