/*
*------------------------------------------------------------------------------
*                                                                              
*  INTEL CONFIDENTIAL                                                          
*                                                                              
*  Copyright 2016 Intel Corporation All Rights Reserved.                 
*                                                                              
*  The source code contained or described herein and all documents related     
*  to the source code ("Material") are owned by Intel Corporation or its    
*  suppliers or licensors. Title to the Material remains with Intel            
*  Corporation or its suppliers and licensors. The Material contains trade     
*  secrets and proprietary and confidential information of Intel or its        
*  suppliers and licensors. The Material is protected by worldwide copyright   
*  and trade secret laws and treaty provisions. No part of the Material may    
*  be used, copied, reproduced, modified, published, uploaded, posted,         
*  transmitted, distributed, or disclosed in any way without Intel's prior     
*  express written permission.                                                 
*                                                                              
*  No license under any patent, copyright, trade secret or other intellectual  
*  property right is granted to or conferred upon you by disclosure or         
*  delivery of the Materials, either expressly, by implication, inducement,    
*  estoppel or otherwise. Any license under such intellectual property rights  
*  must be express and approved by Intel in writing.                           
*                                                                              
*------------------------------------------------------------------------------
*  Auto-generated by /nfs/sc/disks/slx_0108/pvesv/fxr_autogen/i_csrs.pl
*  i_csrs.pl Version 1.5 last modified on Thursday 1/7/16 17:24:50
*  /nfs/sc/disks/slx_0108/pvesv/fxr_autogen/i_csrs.pl -C -R -ST fxr_rx_e2e -o /nfs/sc/disks/slx_0108/pvesv/fxr_autogen/fxr /nfs/sc/disks/slx_0108/pvesv/fxr_autogen/Fox_River/xml/300_Memory_Map.xml /nfs/sc/disks/slx_0108/pvesv/fxr_autogen/Fox_River/xml/332_Memory_Map_RX_E2E.xml
*------------------------------------------------------------------------------
*/

#ifndef DEF_FXR_RX_E2E_SW_DEF
#define DEF_FXR_RX_E2E_SW_DEF

#ifndef FXR_RX_E2E_CSRS
#define FXR_RX_E2E_CSRS									0x000000000000
#endif
#define FXR_NUM_CONTEXTS								192
#define FXR_NUM_PIDS									4096
#define FXR_MAX_CONTEXT									191
#define FXR_TX_CONTEXT_ENTRIES								128
#define FXR_TX_CONTEXT_MAX								127
#define FXR_RX_CONTEXT_ENTRIES								16
#define FXR_RX_CONTEXT_MAX								15
#define FXR_NUM_SL									32
#define FXR_MAX_SL									31
#define RX_E2E_BASE									0
/*
* Table #4 of fxr_top - RXE2E_CFG_PSN_BASE_ADDR_P0_TC
* Host memory base addresses of psn state (both RX and TX) for port 0, per 
* tc.
*/
#define FXR_RXE2E_CFG_PSN_BASE_ADDR_P0_TC						(FXR_RX_E2E_CSRS + 0x000000000000)
#define FXR_RXE2E_CFG_PSN_BASE_ADDR_P0_TC_RESETCSR					0x0000000000000000ull
#define FXR_RXE2E_CFG_PSN_BASE_ADDR_P0_TC_ADDRESS_SHIFT					12
#define FXR_RXE2E_CFG_PSN_BASE_ADDR_P0_TC_ADDRESS_MASK					0x1FFFFFFFFFFFull
#define FXR_RXE2E_CFG_PSN_BASE_ADDR_P0_TC_ADDRESS_SMASK					0x1FFFFFFFFFFF000ull
/*
* Table #5 of fxr_top - RXE2E_CFG_PSN_BASE_ADDR_P1_TC
* Host memory base addresses of psn state (both RX and TX) for port 1, per 
* tc.
*/
#define FXR_RXE2E_CFG_PSN_BASE_ADDR_P1_TC						(FXR_RX_E2E_CSRS + 0x000000000020)
#define FXR_RXE2E_CFG_PSN_BASE_ADDR_P1_TC_RESETCSR					0x0000000000000000ull
#define FXR_RXE2E_CFG_PSN_BASE_ADDR_P1_TC_ADDRESS_SHIFT					12
#define FXR_RXE2E_CFG_PSN_BASE_ADDR_P1_TC_ADDRESS_MASK					0x1FFFFFFFFFFFull
#define FXR_RXE2E_CFG_PSN_BASE_ADDR_P1_TC_ADDRESS_SMASK					0x1FFFFFFFFFFF000ull
/*
* Table #6 of fxr_top - RXE2E_CFG_VALID_TC_SLID
* Describes max slid per port, valid TC's per port. Packets with invalid TC or 
* slid > max will not do a PSN Cache lookup and will get packet status 
* PKT_STATUS_NOT_CONNECTED. These values also limit the amount of host memory 
* PSN cache table backing needed for evicts and fills.
*/
#define FXR_RXE2E_CFG_VALID_TC_SLID							(FXR_RX_E2E_CSRS + 0x000000000040)
#define FXR_RXE2E_CFG_VALID_TC_SLID_RESETCSR						0x00FFFFFFFFFFFFFFull
#define FXR_RXE2E_CFG_VALID_TC_SLID_TC_VALID_P1_SHIFT					52
#define FXR_RXE2E_CFG_VALID_TC_SLID_TC_VALID_P1_MASK					0xFull
#define FXR_RXE2E_CFG_VALID_TC_SLID_TC_VALID_P1_SMASK					0xF0000000000000ull
#define FXR_RXE2E_CFG_VALID_TC_SLID_MAX_SLID_P1_SHIFT					28
#define FXR_RXE2E_CFG_VALID_TC_SLID_MAX_SLID_P1_MASK					0xFFFFFFull
#define FXR_RXE2E_CFG_VALID_TC_SLID_MAX_SLID_P1_SMASK					0xFFFFFF0000000ull
#define FXR_RXE2E_CFG_VALID_TC_SLID_TC_VALID_P0_SHIFT					24
#define FXR_RXE2E_CFG_VALID_TC_SLID_TC_VALID_P0_MASK					0xFull
#define FXR_RXE2E_CFG_VALID_TC_SLID_TC_VALID_P0_SMASK					0xF000000ull
#define FXR_RXE2E_CFG_VALID_TC_SLID_MAX_SLID_P0_SHIFT					0
#define FXR_RXE2E_CFG_VALID_TC_SLID_MAX_SLID_P0_MASK					0xFFFFFFull
#define FXR_RXE2E_CFG_VALID_TC_SLID_MAX_SLID_P0_SMASK					0xFFFFFFull
/*
* Table #7 of fxr_top - RXE2E_CFG_SPECIAL_ACK_RATE
*  Periodically, a special ack is sent carrying the current expected unordered 
* psn and max_psn_distance for source OTR to use in flow control. This is used 
* by OTR to adjust the base of the PSN window it is allowed to send as well as 
* the size of the window. The special_ack_rate_code controls the frequency of 
* these special acks. Note that a special nack is also sent if a packet was 
* unscorable due to no big scoreboards available or psn offset from expected 
* unordered psn is > big scoreboard size. A special ack is also sent if this 
* packet has already been seen (unordered packets only).
*/
#define FXR_RXE2E_CFG_SPECIAL_ACK_RATE							(FXR_RX_E2E_CSRS + 0x000000000048)
#define FXR_RXE2E_CFG_SPECIAL_ACK_RATE_RESETCSR						0x0000000000000004ull
#define FXR_RXE2E_CFG_SPECIAL_ACK_RATE_SPECIAL_ACK_RATE_CODE_SHIFT			0
#define FXR_RXE2E_CFG_SPECIAL_ACK_RATE_SPECIAL_ACK_RATE_CODE_MASK			0x7ull
#define FXR_RXE2E_CFG_SPECIAL_ACK_RATE_SPECIAL_ACK_RATE_CODE_SMASK			0x7ull
/*
* Table #8 of fxr_top - RXE2E_CFG_PORT_MODE
* This is the Port Mode configuration csr. See #%%#<blue text>Section 7.1.2.2.3, 
* 'Packet Sequence Number Table Structures'#%%# for how this csr affects client 
* psn cache addresses. See Portals Transport Layer #%%#<blue text>Section 
* 10.9.8, 'Integrated Multi-Rail Support'#%%# for a description of these 
* modes.
*/
#define FXR_RXE2E_CFG_PORT_MODE								(FXR_RX_E2E_CSRS + 0x000000000050)
#define FXR_RXE2E_CFG_PORT_MODE_RESETCSR						0x0000000000000000ull
#define FXR_RXE2E_CFG_PORT_MODE_MODE_SHIFT						0
#define FXR_RXE2E_CFG_PORT_MODE_MODE_MASK						0x3ull
#define FXR_RXE2E_CFG_PORT_MODE_MODE_SMASK						0x3ull
/*
* Table #9 of fxr_top - RXE2E_CFG_LMC
* This CSR contains the the number of low DLID bits the network has masked for 
* the packet to arrive. This is used to determine the HIARB address for psn 
* cache evicts and fills. See #%%#<blue text>Section 19.5.3, 'PSN State 
* Layout'#%%#. The max value for LMC is 2. A value of 3 written to this register 
* will be interpreted as if it was 2. See #%%#<blue text>Section 7.1.2.2.3, 
* 'Packet Sequence Number Table Structures'#%%# for how this csr affects client 
* psn cache addresses. 
*/
#define FXR_RXE2E_CFG_LMC								(FXR_RX_E2E_CSRS + 0x000000000058)
#define FXR_RXE2E_CFG_LMC_RESETCSR							0x0000000000000000ull
#define FXR_RXE2E_CFG_LMC_LMC_P1_SHIFT							4
#define FXR_RXE2E_CFG_LMC_LMC_P1_MASK							0x3ull
#define FXR_RXE2E_CFG_LMC_LMC_P1_SMASK							0x30ull
#define FXR_RXE2E_CFG_LMC_LMC_P0_SHIFT							0
#define FXR_RXE2E_CFG_LMC_LMC_P0_MASK							0x3ull
#define FXR_RXE2E_CFG_LMC_LMC_P0_SMASK							0x3ull
/*
* Table #10 of fxr_top - RXE2E_CFG_LM_CREDIT_FUND_MAX
* This CSR contains the configuration parameters necessary to configure the max 
* number of credit funds outstanding to the Link Mux. Any value > 16 will be 
* clamped to 16 to prevent E2E input fifo overrun, i.e. the effective credit max 
* = min(csr value, 16). These credit funds will be used by Link Mux to send 
* packet flits to E2E. It is ok to write these while system is running. Note 
* that 0 will shut off an interface 
*/
#define FXR_RXE2E_CFG_LM_CREDIT_FUND_MAX						(FXR_RX_E2E_CSRS + 0x000000000060)
#define FXR_RXE2E_CFG_LM_CREDIT_FUND_MAX_RESETCSR					0x0000008421084210ull
#define FXR_RXE2E_CFG_LM_CREDIT_FUND_MAX_MC1_TC3_CRDT_FUND_MAX_SHIFT			35
#define FXR_RXE2E_CFG_LM_CREDIT_FUND_MAX_MC1_TC3_CRDT_FUND_MAX_MASK			0x1Full
#define FXR_RXE2E_CFG_LM_CREDIT_FUND_MAX_MC1_TC3_CRDT_FUND_MAX_SMASK			0xF800000000ull
#define FXR_RXE2E_CFG_LM_CREDIT_FUND_MAX_MC1_TC2_CRDT_FUND_MAX_SHIFT			30
#define FXR_RXE2E_CFG_LM_CREDIT_FUND_MAX_MC1_TC2_CRDT_FUND_MAX_MASK			0x1Full
#define FXR_RXE2E_CFG_LM_CREDIT_FUND_MAX_MC1_TC2_CRDT_FUND_MAX_SMASK			0x7C0000000ull
#define FXR_RXE2E_CFG_LM_CREDIT_FUND_MAX_MC1_TC1_CRDT_FUND_MAX_SHIFT			25
#define FXR_RXE2E_CFG_LM_CREDIT_FUND_MAX_MC1_TC1_CRDT_FUND_MAX_MASK			0x1Full
#define FXR_RXE2E_CFG_LM_CREDIT_FUND_MAX_MC1_TC1_CRDT_FUND_MAX_SMASK			0x3E000000ull
#define FXR_RXE2E_CFG_LM_CREDIT_FUND_MAX_MC1_TC0_CRDT_FUND_MAX_SHIFT			20
#define FXR_RXE2E_CFG_LM_CREDIT_FUND_MAX_MC1_TC0_CRDT_FUND_MAX_MASK			0x1Full
#define FXR_RXE2E_CFG_LM_CREDIT_FUND_MAX_MC1_TC0_CRDT_FUND_MAX_SMASK			0x1F00000ull
#define FXR_RXE2E_CFG_LM_CREDIT_FUND_MAX_MC0_TC3_CRDT_FUND_MAX_SHIFT			15
#define FXR_RXE2E_CFG_LM_CREDIT_FUND_MAX_MC0_TC3_CRDT_FUND_MAX_MASK			0x1Full
#define FXR_RXE2E_CFG_LM_CREDIT_FUND_MAX_MC0_TC3_CRDT_FUND_MAX_SMASK			0xF8000ull
#define FXR_RXE2E_CFG_LM_CREDIT_FUND_MAX_MC0_TC2_CRDT_FUND_MAX_SHIFT			10
#define FXR_RXE2E_CFG_LM_CREDIT_FUND_MAX_MC0_TC2_CRDT_FUND_MAX_MASK			0x1Full
#define FXR_RXE2E_CFG_LM_CREDIT_FUND_MAX_MC0_TC2_CRDT_FUND_MAX_SMASK			0x7C00ull
#define FXR_RXE2E_CFG_LM_CREDIT_FUND_MAX_MC0_TC1_CRDT_FUND_MAX_SHIFT			5
#define FXR_RXE2E_CFG_LM_CREDIT_FUND_MAX_MC0_TC1_CRDT_FUND_MAX_MASK			0x1Full
#define FXR_RXE2E_CFG_LM_CREDIT_FUND_MAX_MC0_TC1_CRDT_FUND_MAX_SMASK			0x3E0ull
#define FXR_RXE2E_CFG_LM_CREDIT_FUND_MAX_MC0_TC0_CRDT_FUND_MAX_SHIFT			0
#define FXR_RXE2E_CFG_LM_CREDIT_FUND_MAX_MC0_TC0_CRDT_FUND_MAX_MASK			0x1Full
#define FXR_RXE2E_CFG_LM_CREDIT_FUND_MAX_MC0_TC0_CRDT_FUND_MAX_SMASK			0x1Full
/*
* Table #11 of fxr_top - RXE2E_CFG_PSN_CACHE_CLIENT_DISABLE
* 
*/
#define FXR_RXE2E_CFG_PSN_CACHE_CLIENT_DISABLE						(FXR_RX_E2E_CSRS + 0x000000000068)
#define FXR_RXE2E_CFG_PSN_CACHE_CLIENT_DISABLE_RESETCSR					0x0000000000000000ull
#define FXR_RXE2E_CFG_PSN_CACHE_CLIENT_DISABLE_CLIENT_PSN_CACHE_REQUEST_DISABLE_SHIFT	0
#define FXR_RXE2E_CFG_PSN_CACHE_CLIENT_DISABLE_CLIENT_PSN_CACHE_REQUEST_DISABLE_MASK	0x1ull
#define FXR_RXE2E_CFG_PSN_CACHE_CLIENT_DISABLE_CLIENT_PSN_CACHE_REQUEST_DISABLE_SMASK	0x1ull
/*
* Table #12 of fxr_top - RXE2E_CFG_CREDIT_ENABLE
* This CSR contains the enable bits for credits for HIARB, OTR and RXHP. Setting 
* an enable to 0 will make it appear that there are no credit funds for a 
* transfer, so no further transfer requests will be initiated. RXHP may have 
* some pkt_status transfers in progress that will continue, but no new ones will 
* be initiated. These bits do not affect the number of credit funds nor the 
* accumulation of more credit funds while the enable is 0. Disabling and then 
* enabling an interface with these bits looks just like a transmission pause.. 
* 
*/
#define FXR_RXE2E_CFG_CREDIT_ENABLE							(FXR_RX_E2E_CSRS + 0x000000000070)
#define FXR_RXE2E_CFG_CREDIT_ENABLE_RESETCSR						0x000000000000001Full
#define FXR_RXE2E_CFG_CREDIT_ENABLE_HIARB_CREDIT_ENABLE_SHIFT				4
#define FXR_RXE2E_CFG_CREDIT_ENABLE_HIARB_CREDIT_ENABLE_MASK				0x1ull
#define FXR_RXE2E_CFG_CREDIT_ENABLE_HIARB_CREDIT_ENABLE_SMASK				0x10ull
#define FXR_RXE2E_CFG_CREDIT_ENABLE_OTR_PKT_STATUS_CREDIT_ENABLE_SHIFT			3
#define FXR_RXE2E_CFG_CREDIT_ENABLE_OTR_PKT_STATUS_CREDIT_ENABLE_MASK			0x1ull
#define FXR_RXE2E_CFG_CREDIT_ENABLE_OTR_PKT_STATUS_CREDIT_ENABLE_SMASK			0x8ull
#define FXR_RXE2E_CFG_CREDIT_ENABLE_OTR_HDR_FLIT_CREDIT_ENABLE_SHIFT			2
#define FXR_RXE2E_CFG_CREDIT_ENABLE_OTR_HDR_FLIT_CREDIT_ENABLE_MASK			0x1ull
#define FXR_RXE2E_CFG_CREDIT_ENABLE_OTR_HDR_FLIT_CREDIT_ENABLE_SMASK			0x4ull
#define FXR_RXE2E_CFG_CREDIT_ENABLE_RXHP_PKT_STATUS_CREDIT_ENABLE_SHIFT			1
#define FXR_RXE2E_CFG_CREDIT_ENABLE_RXHP_PKT_STATUS_CREDIT_ENABLE_MASK			0x1ull
#define FXR_RXE2E_CFG_CREDIT_ENABLE_RXHP_PKT_STATUS_CREDIT_ENABLE_SMASK			0x2ull
#define FXR_RXE2E_CFG_CREDIT_ENABLE_RXHP_HDR_FLIT_CREDIT_ENABLE_SHIFT			0
#define FXR_RXE2E_CFG_CREDIT_ENABLE_RXHP_HDR_FLIT_CREDIT_ENABLE_MASK			0x1ull
#define FXR_RXE2E_CFG_CREDIT_ENABLE_RXHP_HDR_FLIT_CREDIT_ENABLE_SMASK			0x1ull
/*
* Table #13 of fxr_top - RXE2E_CFG_RC_ORDERED_MAP
* This CSR contains the mapping of the packet rc[2:0] field to ordered needed 
* for psn checking. It is reset to 0xF to agree with Stormlake #%%#<blue 
* text>Section 8.2.4.7, 'Routing Control'#%%#. 
*/
#define FXR_RXE2E_CFG_RC_ORDERED_MAP							(FXR_RX_E2E_CSRS + 0x000000000078)
#define FXR_RXE2E_CFG_RC_ORDERED_MAP_RESETCSR						0x000000000000000Full
#define FXR_RXE2E_CFG_RC_ORDERED_MAP_ORDERED_SHIFT					0
#define FXR_RXE2E_CFG_RC_ORDERED_MAP_ORDERED_MASK					0xFFull
#define FXR_RXE2E_CFG_RC_ORDERED_MAP_ORDERED_SMASK					0xFFull
/*
* Table #14 of fxr_top - RXE2E_CFG_PORT_MIRROR
* Enable for Port Mirroring. Turn on this bit when this node is in Port 
* Mirroring Mode. rx_e2e will do the following:
*/
#define FXR_RXE2E_CFG_PORT_MIRROR							(FXR_RX_E2E_CSRS + 0x000000000080)
#define FXR_RXE2E_CFG_PORT_MIRROR_RESETCSR						0x0000000000000000ull
#define FXR_RXE2E_CFG_PORT_MIRROR_PORT_MIRROR_ON_SHIFT					0
#define FXR_RXE2E_CFG_PORT_MIRROR_PORT_MIRROR_ON_MASK					0x1ull
#define FXR_RXE2E_CFG_PORT_MIRROR_PORT_MIRROR_ON_SMASK					0x1ull
/*
* Table #15 of fxr_top - RXE2E_CFG_PSN_CACHE_ACCESS_CTL
* The PSN Cache access control can be used to write or read, PSN cache data and 
* tag memories as well as invalidate tag entries and flush cache data to host 
* memory. For reads, if the requested address is not in cache, a fill request is 
* sent to hiarb with possibly an evict request. For writes, if the requested 
* address is not in cache, an evict request is sent to hiarb (assuming no 
* invalid entries in tag line) and then the PSN Cache Data is written.
*/
#define FXR_RXE2E_CFG_PSN_CACHE_ACCESS_CTL						(FXR_RX_E2E_CSRS + 0x000000000088)
#define FXR_RXE2E_CFG_PSN_CACHE_ACCESS_CTL_RESETCSR					0x63FFFFFFE0000000ull
#define FXR_RXE2E_CFG_PSN_CACHE_ACCESS_CTL_BAD_ADDR_SHIFT				63
#define FXR_RXE2E_CFG_PSN_CACHE_ACCESS_CTL_BAD_ADDR_MASK				0x1ull
#define FXR_RXE2E_CFG_PSN_CACHE_ACCESS_CTL_BAD_ADDR_SMASK				0x8000000000000000ull
#define FXR_RXE2E_CFG_PSN_CACHE_ACCESS_CTL_BUSY_SHIFT					62
#define FXR_RXE2E_CFG_PSN_CACHE_ACCESS_CTL_BUSY_MASK					0x1ull
#define FXR_RXE2E_CFG_PSN_CACHE_ACCESS_CTL_BUSY_SMASK					0x4000000000000000ull
#define FXR_RXE2E_CFG_PSN_CACHE_ACCESS_CTL_CMD_SHIFT					58
#define FXR_RXE2E_CFG_PSN_CACHE_ACCESS_CTL_CMD_MASK					0xFull
#define FXR_RXE2E_CFG_PSN_CACHE_ACCESS_CTL_CMD_SMASK					0x3C00000000000000ull
#define FXR_RXE2E_CFG_PSN_CACHE_ACCESS_CTL_MASK_ADDRESS_SHIFT				29
#define FXR_RXE2E_CFG_PSN_CACHE_ACCESS_CTL_MASK_ADDRESS_MASK				0x1FFFFFFFull
#define FXR_RXE2E_CFG_PSN_CACHE_ACCESS_CTL_MASK_ADDRESS_SMASK				0x3FFFFFFE0000000ull
#define FXR_RXE2E_CFG_PSN_CACHE_ACCESS_CTL_ADDRESS_SHIFT				0
#define FXR_RXE2E_CFG_PSN_CACHE_ACCESS_CTL_ADDRESS_MASK					0x1FFFFFFFull
#define FXR_RXE2E_CFG_PSN_CACHE_ACCESS_CTL_ADDRESS_SMASK				0x1FFFFFFFull
/*
* Table #16 of fxr_top - RXE2E_CFG_PSN_CACHE_ACCESS_DATA
* This csr along with #%%#RXE2E_CFG_PSN_CACHE_ACCESS_CTL#%%# is used to read, 
* write (warmup/teardown) the PSN Cache. See  #%%#RXE2E_CFG_PSN_CACHE_ACCESS_CTL#%%# 
* for proper technique. .
*/
#define FXR_RXE2E_CFG_PSN_CACHE_ACCESS_DATA						(FXR_RX_E2E_CSRS + 0x000000000090)
#define FXR_RXE2E_CFG_PSN_CACHE_ACCESS_DATA_RESETCSR					0x0000000000000000ull
#define FXR_RXE2E_CFG_PSN_CACHE_ACCESS_DATA_CONNECTED_SHIFT				63
#define FXR_RXE2E_CFG_PSN_CACHE_ACCESS_DATA_CONNECTED_MASK				0x1ull
#define FXR_RXE2E_CFG_PSN_CACHE_ACCESS_DATA_CONNECTED_SMASK				0x8000000000000000ull
#define FXR_RXE2E_CFG_PSN_CACHE_ACCESS_DATA_MISSING_ORDERED_SEEN_SHIFT			62
#define FXR_RXE2E_CFG_PSN_CACHE_ACCESS_DATA_MISSING_ORDERED_SEEN_MASK			0x1ull
#define FXR_RXE2E_CFG_PSN_CACHE_ACCESS_DATA_MISSING_ORDERED_SEEN_SMASK			0x4000000000000000ull
#define FXR_RXE2E_CFG_PSN_CACHE_ACCESS_DATA_ORDERED_PSN_SHIFT				46
#define FXR_RXE2E_CFG_PSN_CACHE_ACCESS_DATA_ORDERED_PSN_MASK				0xFFFFull
#define FXR_RXE2E_CFG_PSN_CACHE_ACCESS_DATA_ORDERED_PSN_SMASK				0x3FFFC00000000000ull
#define FXR_RXE2E_CFG_PSN_CACHE_ACCESS_DATA_UNORDERED_PSN_SHIFT				30
#define FXR_RXE2E_CFG_PSN_CACHE_ACCESS_DATA_UNORDERED_PSN_MASK				0xFFFFull
#define FXR_RXE2E_CFG_PSN_CACHE_ACCESS_DATA_UNORDERED_PSN_SMASK				0x3FFFC0000000ull
#define FXR_RXE2E_CFG_PSN_CACHE_ACCESS_DATA_BIG_IN_USE_SHIFT				29
#define FXR_RXE2E_CFG_PSN_CACHE_ACCESS_DATA_BIG_IN_USE_MASK				0x1ull
#define FXR_RXE2E_CFG_PSN_CACHE_ACCESS_DATA_BIG_IN_USE_SMASK				0x20000000ull
#define FXR_RXE2E_CFG_PSN_CACHE_ACCESS_DATA_SMALL_SCOREBOARD_SHIFT			0
#define FXR_RXE2E_CFG_PSN_CACHE_ACCESS_DATA_SMALL_SCOREBOARD_MASK			0x1FFFFFFFull
#define FXR_RXE2E_CFG_PSN_CACHE_ACCESS_DATA_SMALL_SCOREBOARD_SMASK			0x1FFFFFFFull
/*
* Table #17 of fxr_top - RXE2E_CFG_PSN_CACHE_ACCESS_DATA_BIT_ENABLE
* This csr is used for masked bit writes to the PSN Cache. This csr is only used 
* with CACHE_CMD_WR. If this csr is all 1's, no read or fill is necessary. If 
* this csr is not all 1's, we need to do a read-modify-write which may require a 
* fill from host memory. See  #%%#RXE2E_CFG_PSN_CACHE_ACCESS_CTL#%%# for proper 
* technique. .
*/
#define FXR_RXE2E_CFG_PSN_CACHE_ACCESS_DATA_BIT_ENABLE					(FXR_RX_E2E_CSRS + 0x000000000098)
#define FXR_RXE2E_CFG_PSN_CACHE_ACCESS_DATA_BIT_ENABLE_RESETCSR				0xFFFFFFFFFFFFFFFFull
#define FXR_RXE2E_CFG_PSN_CACHE_ACCESS_DATA_BIT_ENABLE_CONNECTED_SHIFT			63
#define FXR_RXE2E_CFG_PSN_CACHE_ACCESS_DATA_BIT_ENABLE_CONNECTED_MASK			0x1ull
#define FXR_RXE2E_CFG_PSN_CACHE_ACCESS_DATA_BIT_ENABLE_CONNECTED_SMASK			0x8000000000000000ull
#define FXR_RXE2E_CFG_PSN_CACHE_ACCESS_DATA_BIT_ENABLE_MISSING_ORDERED_SEEN_SHIFT	62
#define FXR_RXE2E_CFG_PSN_CACHE_ACCESS_DATA_BIT_ENABLE_MISSING_ORDERED_SEEN_MASK	0x1ull
#define FXR_RXE2E_CFG_PSN_CACHE_ACCESS_DATA_BIT_ENABLE_MISSING_ORDERED_SEEN_SMASK	0x4000000000000000ull
#define FXR_RXE2E_CFG_PSN_CACHE_ACCESS_DATA_BIT_ENABLE_ORDERED_PSN_SHIFT		46
#define FXR_RXE2E_CFG_PSN_CACHE_ACCESS_DATA_BIT_ENABLE_ORDERED_PSN_MASK			0xFFFFull
#define FXR_RXE2E_CFG_PSN_CACHE_ACCESS_DATA_BIT_ENABLE_ORDERED_PSN_SMASK		0x3FFFC00000000000ull
#define FXR_RXE2E_CFG_PSN_CACHE_ACCESS_DATA_BIT_ENABLE_UNORDERED_PSN_SHIFT		30
#define FXR_RXE2E_CFG_PSN_CACHE_ACCESS_DATA_BIT_ENABLE_UNORDERED_PSN_MASK		0xFFFFull
#define FXR_RXE2E_CFG_PSN_CACHE_ACCESS_DATA_BIT_ENABLE_UNORDERED_PSN_SMASK		0x3FFFC0000000ull
#define FXR_RXE2E_CFG_PSN_CACHE_ACCESS_DATA_BIT_ENABLE_BIG_IN_USE_SHIFT			29
#define FXR_RXE2E_CFG_PSN_CACHE_ACCESS_DATA_BIT_ENABLE_BIG_IN_USE_MASK			0x1ull
#define FXR_RXE2E_CFG_PSN_CACHE_ACCESS_DATA_BIT_ENABLE_BIG_IN_USE_SMASK			0x20000000ull
#define FXR_RXE2E_CFG_PSN_CACHE_ACCESS_DATA_BIT_ENABLE_SMALL_SCOREBOARD_SHIFT		0
#define FXR_RXE2E_CFG_PSN_CACHE_ACCESS_DATA_BIT_ENABLE_SMALL_SCOREBOARD_MASK		0x1FFFFFFFull
#define FXR_RXE2E_CFG_PSN_CACHE_ACCESS_DATA_BIT_ENABLE_SMALL_SCOREBOARD_SMASK		0x1FFFFFFFull
/*
* Table #18 of fxr_top - RXE2E_CFG_PSN_CACHE_ACCESS_TAG
* This is the psn cache tag data csr. This csr along with #%%#RXE2E_CFG_PSN_CACHE_ACCESS_CTL#%%# 
* is used to read, write the PSN Cache Tag. See  #%%#RXE2E_CFG_PSN_CACHE_ACCESS_CTL#%%# 
* for proper technique. This layout is for two ways. There are 8 of these regs 
* for a total of 16 ways.
*/
#define FXR_RXE2E_CFG_PSN_CACHE_ACCESS_TAG						(FXR_RX_E2E_CSRS + 0x000000000100)
#define FXR_RXE2E_CFG_PSN_CACHE_ACCESS_TAG_RESETCSR					0x0000000000000000ull
#define FXR_RXE2E_CFG_PSN_CACHE_ACCESS_TAG_RESERVE_HI_SHIFT				62
#define FXR_RXE2E_CFG_PSN_CACHE_ACCESS_TAG_RESERVE_HI_MASK				0x3ull
#define FXR_RXE2E_CFG_PSN_CACHE_ACCESS_TAG_RESERVE_HI_SMASK				0xC000000000000000ull
#define FXR_RXE2E_CFG_PSN_CACHE_ACCESS_TAG_TAG_WAY_VALID_HI_SHIFT			61
#define FXR_RXE2E_CFG_PSN_CACHE_ACCESS_TAG_TAG_WAY_VALID_HI_MASK			0x1ull
#define FXR_RXE2E_CFG_PSN_CACHE_ACCESS_TAG_TAG_WAY_VALID_HI_SMASK			0x2000000000000000ull
#define FXR_RXE2E_CFG_PSN_CACHE_ACCESS_TAG_TAG_WAY_ADDR_HI_SHIFT			32
#define FXR_RXE2E_CFG_PSN_CACHE_ACCESS_TAG_TAG_WAY_ADDR_HI_MASK				0x1FFFFFFFull
#define FXR_RXE2E_CFG_PSN_CACHE_ACCESS_TAG_TAG_WAY_ADDR_HI_SMASK			0x1FFFFFFF00000000ull
#define FXR_RXE2E_CFG_PSN_CACHE_ACCESS_TAG_RESERVE_LO_SHIFT				30
#define FXR_RXE2E_CFG_PSN_CACHE_ACCESS_TAG_RESERVE_LO_MASK				0x3ull
#define FXR_RXE2E_CFG_PSN_CACHE_ACCESS_TAG_RESERVE_LO_SMASK				0xC0000000ull
#define FXR_RXE2E_CFG_PSN_CACHE_ACCESS_TAG_TAG_WAY_VALID_LO_SHIFT			29
#define FXR_RXE2E_CFG_PSN_CACHE_ACCESS_TAG_TAG_WAY_VALID_LO_MASK			0x1ull
#define FXR_RXE2E_CFG_PSN_CACHE_ACCESS_TAG_TAG_WAY_VALID_LO_SMASK			0x20000000ull
#define FXR_RXE2E_CFG_PSN_CACHE_ACCESS_TAG_TAG_WAY_ADDR_LO_SHIFT			0
#define FXR_RXE2E_CFG_PSN_CACHE_ACCESS_TAG_TAG_WAY_ADDR_LO_MASK				0x1FFFFFFFull
#define FXR_RXE2E_CFG_PSN_CACHE_ACCESS_TAG_TAG_WAY_ADDR_LO_SMASK			0x1FFFFFFFull
/*
* Table #19 of fxr_top - RXE2E_CFG_MC0_HDR_FLIT_CNT_CAM
* This table is used to determine how many MC0 32B header flits to send to RXHP. 
* If the following holds true for a packet:
*/
#define FXR_RXE2E_CFG_MC0_HDR_FLIT_CNT_CAM						(FXR_RX_E2E_CSRS + 0x000000000200)
#define FXR_RXE2E_CFG_MC0_HDR_FLIT_CNT_CAM_RESETCSR					0x0000000000000001ull
#define FXR_RXE2E_CFG_MC0_HDR_FLIT_CNT_CAM_VALID_SHIFT					49
#define FXR_RXE2E_CFG_MC0_HDR_FLIT_CNT_CAM_VALID_MASK					0x1ull
#define FXR_RXE2E_CFG_MC0_HDR_FLIT_CNT_CAM_VALID_SMASK					0x2000000000000ull
#define FXR_RXE2E_CFG_MC0_HDR_FLIT_CNT_CAM_L2_SHIFT					47
#define FXR_RXE2E_CFG_MC0_HDR_FLIT_CNT_CAM_L2_MASK					0x3ull
#define FXR_RXE2E_CFG_MC0_HDR_FLIT_CNT_CAM_L2_SMASK					0x1800000000000ull
#define FXR_RXE2E_CFG_MC0_HDR_FLIT_CNT_CAM_L2EXT_SHIFT					43
#define FXR_RXE2E_CFG_MC0_HDR_FLIT_CNT_CAM_L2EXT_MASK					0xFull
#define FXR_RXE2E_CFG_MC0_HDR_FLIT_CNT_CAM_L2EXT_SMASK					0x780000000000ull
#define FXR_RXE2E_CFG_MC0_HDR_FLIT_CNT_CAM_HD_SHIFT					42
#define FXR_RXE2E_CFG_MC0_HDR_FLIT_CNT_CAM_HD_MASK					0x1ull
#define FXR_RXE2E_CFG_MC0_HDR_FLIT_CNT_CAM_HD_SMASK					0x40000000000ull
#define FXR_RXE2E_CFG_MC0_HDR_FLIT_CNT_CAM_NI_1_SHIFT					41
#define FXR_RXE2E_CFG_MC0_HDR_FLIT_CNT_CAM_NI_1_MASK					0x1ull
#define FXR_RXE2E_CFG_MC0_HDR_FLIT_CNT_CAM_NI_1_SMASK					0x20000000000ull
#define FXR_RXE2E_CFG_MC0_HDR_FLIT_CNT_CAM_L4_SHIFT					33
#define FXR_RXE2E_CFG_MC0_HDR_FLIT_CNT_CAM_L4_MASK					0xFFull
#define FXR_RXE2E_CFG_MC0_HDR_FLIT_CNT_CAM_L4_SMASK					0x1FE00000000ull
#define FXR_RXE2E_CFG_MC0_HDR_FLIT_CNT_CAM_OPCODE_SHIFT					26
#define FXR_RXE2E_CFG_MC0_HDR_FLIT_CNT_CAM_OPCODE_MASK					0x7Full
#define FXR_RXE2E_CFG_MC0_HDR_FLIT_CNT_CAM_OPCODE_SMASK					0x1FC000000ull
#define FXR_RXE2E_CFG_MC0_HDR_FLIT_CNT_CAM_L2_MASK_SHIFT				24
#define FXR_RXE2E_CFG_MC0_HDR_FLIT_CNT_CAM_L2_MASK_MASK					0x3ull
#define FXR_RXE2E_CFG_MC0_HDR_FLIT_CNT_CAM_L2_MASK_SMASK				0x3000000ull
#define FXR_RXE2E_CFG_MC0_HDR_FLIT_CNT_CAM_L2EXT_MASK_SHIFT				20
#define FXR_RXE2E_CFG_MC0_HDR_FLIT_CNT_CAM_L2EXT_MASK_MASK				0xFull
#define FXR_RXE2E_CFG_MC0_HDR_FLIT_CNT_CAM_L2EXT_MASK_SMASK				0xF00000ull
#define FXR_RXE2E_CFG_MC0_HDR_FLIT_CNT_CAM_HD_MASK_SHIFT				19
#define FXR_RXE2E_CFG_MC0_HDR_FLIT_CNT_CAM_HD_MASK_MASK					0x1ull
#define FXR_RXE2E_CFG_MC0_HDR_FLIT_CNT_CAM_HD_MASK_SMASK				0x80000ull
#define FXR_RXE2E_CFG_MC0_HDR_FLIT_CNT_CAM_NI_1_MASK_SHIFT				18
#define FXR_RXE2E_CFG_MC0_HDR_FLIT_CNT_CAM_NI_1_MASK_MASK				0x1ull
#define FXR_RXE2E_CFG_MC0_HDR_FLIT_CNT_CAM_NI_1_MASK_SMASK				0x40000ull
#define FXR_RXE2E_CFG_MC0_HDR_FLIT_CNT_CAM_L4_MASK_SHIFT				10
#define FXR_RXE2E_CFG_MC0_HDR_FLIT_CNT_CAM_L4_MASK_MASK					0xFFull
#define FXR_RXE2E_CFG_MC0_HDR_FLIT_CNT_CAM_L4_MASK_SMASK				0x3FC00ull
#define FXR_RXE2E_CFG_MC0_HDR_FLIT_CNT_CAM_OPCODE_MASK_SHIFT				3
#define FXR_RXE2E_CFG_MC0_HDR_FLIT_CNT_CAM_OPCODE_MASK_MASK				0x7Full
#define FXR_RXE2E_CFG_MC0_HDR_FLIT_CNT_CAM_OPCODE_MASK_SMASK				0x3F8ull
#define FXR_RXE2E_CFG_MC0_HDR_FLIT_CNT_CAM_CNT_M1_SHIFT					0
#define FXR_RXE2E_CFG_MC0_HDR_FLIT_CNT_CAM_CNT_M1_MASK					0x7ull
#define FXR_RXE2E_CFG_MC0_HDR_FLIT_CNT_CAM_CNT_M1_SMASK					0x7ull
/*
* Table #20 of fxr_top - RXE2E_ERR_STS_1
* This is the Error Status CSR. Bits are set by hardware or by writing to the 
* #%%#RXE2E_ERR_FRC_1#%%# CSR. Bits are cleared by writing to the 
* #%%#RXE2E_ERR_CLR_1#%%# CSR.
*/
#define FXR_RXE2E_ERR_STS_1								(FXR_RX_E2E_CSRS + 0x000000000300)
#define FXR_RXE2E_ERR_STS_1_RESETCSR							0x0000000000000000ull
#define FXR_RXE2E_ERR_STS_1_ANY_SBE_CNTR_NON_ZERO_SHIFT					20
#define FXR_RXE2E_ERR_STS_1_ANY_SBE_CNTR_NON_ZERO_MASK					0x1ull
#define FXR_RXE2E_ERR_STS_1_ANY_SBE_CNTR_NON_ZERO_SMASK					0x100000ull
#define FXR_RXE2E_ERR_STS_1_ANY_SBE_CNTR_MAX_SHIFT					19
#define FXR_RXE2E_ERR_STS_1_ANY_SBE_CNTR_MAX_MASK					0x1ull
#define FXR_RXE2E_ERR_STS_1_ANY_SBE_CNTR_MAX_SMASK					0x80000ull
#define FXR_RXE2E_ERR_STS_1_ANY_MBE_CNTR_NON_ZERO_SHIFT					18
#define FXR_RXE2E_ERR_STS_1_ANY_MBE_CNTR_NON_ZERO_MASK					0x1ull
#define FXR_RXE2E_ERR_STS_1_ANY_MBE_CNTR_NON_ZERO_SMASK					0x40000ull
#define FXR_RXE2E_ERR_STS_1_ANY_MBE_CNTR_MAX_SHIFT					17
#define FXR_RXE2E_ERR_STS_1_ANY_MBE_CNTR_MAX_MASK					0x1ull
#define FXR_RXE2E_ERR_STS_1_ANY_MBE_CNTR_MAX_SMASK					0x20000ull
#define FXR_RXE2E_ERR_STS_1_BIG_SCOREBOARD_SBE_SHIFT					16
#define FXR_RXE2E_ERR_STS_1_BIG_SCOREBOARD_SBE_MASK					0x1ull
#define FXR_RXE2E_ERR_STS_1_BIG_SCOREBOARD_SBE_SMASK					0x10000ull
#define FXR_RXE2E_ERR_STS_1_BIG_SCOREBOARD_MBE_SHIFT					15
#define FXR_RXE2E_ERR_STS_1_BIG_SCOREBOARD_MBE_MASK					0x1ull
#define FXR_RXE2E_ERR_STS_1_BIG_SCOREBOARD_MBE_SMASK					0x8000ull
#define FXR_RXE2E_ERR_STS_1_MC1CRC_SHIFT						14
#define FXR_RXE2E_ERR_STS_1_MC1CRC_MASK							0x1ull
#define FXR_RXE2E_ERR_STS_1_MC1CRC_SMASK						0x4000ull
#define FXR_RXE2E_ERR_STS_1_MC0CRC_SHIFT						13
#define FXR_RXE2E_ERR_STS_1_MC0CRC_MASK							0x1ull
#define FXR_RXE2E_ERR_STS_1_MC0CRC_SMASK						0x2000ull
#define FXR_RXE2E_ERR_STS_1_PSN_CACHE_DATA_SBE_SHIFT					12
#define FXR_RXE2E_ERR_STS_1_PSN_CACHE_DATA_SBE_MASK					0x1ull
#define FXR_RXE2E_ERR_STS_1_PSN_CACHE_DATA_SBE_SMASK					0x1000ull
#define FXR_RXE2E_ERR_STS_1_PSN_CACHE_DATA_MBE_SHIFT					11
#define FXR_RXE2E_ERR_STS_1_PSN_CACHE_DATA_MBE_MASK					0x1ull
#define FXR_RXE2E_ERR_STS_1_PSN_CACHE_DATA_MBE_SMASK					0x800ull
#define FXR_RXE2E_ERR_STS_1_PSN_CACHE_TAG_SBE_SHIFT					10
#define FXR_RXE2E_ERR_STS_1_PSN_CACHE_TAG_SBE_MASK					0x1ull
#define FXR_RXE2E_ERR_STS_1_PSN_CACHE_TAG_SBE_SMASK					0x400ull
#define FXR_RXE2E_ERR_STS_1_PSN_CACHE_TAG_MBE_SHIFT					9
#define FXR_RXE2E_ERR_STS_1_PSN_CACHE_TAG_MBE_MASK					0x1ull
#define FXR_RXE2E_ERR_STS_1_PSN_CACHE_TAG_MBE_SMASK					0x200ull
#define FXR_RXE2E_ERR_STS_1_MC1_INPUT_FIFO_SBE_SHIFT					8
#define FXR_RXE2E_ERR_STS_1_MC1_INPUT_FIFO_SBE_MASK					0x1ull
#define FXR_RXE2E_ERR_STS_1_MC1_INPUT_FIFO_SBE_SMASK					0x100ull
#define FXR_RXE2E_ERR_STS_1_MC1_INPUT_FIFO_MBE_SHIFT					7
#define FXR_RXE2E_ERR_STS_1_MC1_INPUT_FIFO_MBE_MASK					0x1ull
#define FXR_RXE2E_ERR_STS_1_MC1_INPUT_FIFO_MBE_SMASK					0x80ull
#define FXR_RXE2E_ERR_STS_1_MC0_INPUT_FIFO_SBE_SHIFT					6
#define FXR_RXE2E_ERR_STS_1_MC0_INPUT_FIFO_SBE_MASK					0x1ull
#define FXR_RXE2E_ERR_STS_1_MC0_INPUT_FIFO_SBE_SMASK					0x40ull
#define FXR_RXE2E_ERR_STS_1_MC0_INPUT_FIFO_MBE_SHIFT					5
#define FXR_RXE2E_ERR_STS_1_MC0_INPUT_FIFO_MBE_MASK					0x1ull
#define FXR_RXE2E_ERR_STS_1_MC0_INPUT_FIFO_MBE_SMASK					0x20ull
#define FXR_RXE2E_ERR_STS_1_MC1_LM_IN_SBE_SHIFT						4
#define FXR_RXE2E_ERR_STS_1_MC1_LM_IN_SBE_MASK						0x1ull
#define FXR_RXE2E_ERR_STS_1_MC1_LM_IN_SBE_SMASK						0x10ull
#define FXR_RXE2E_ERR_STS_1_MC1_LM_IN_MBE_SHIFT						3
#define FXR_RXE2E_ERR_STS_1_MC1_LM_IN_MBE_MASK						0x1ull
#define FXR_RXE2E_ERR_STS_1_MC1_LM_IN_MBE_SMASK						0x8ull
#define FXR_RXE2E_ERR_STS_1_MC0_LM_IN_SBE_SHIFT						2
#define FXR_RXE2E_ERR_STS_1_MC0_LM_IN_SBE_MASK						0x1ull
#define FXR_RXE2E_ERR_STS_1_MC0_LM_IN_SBE_SMASK						0x4ull
#define FXR_RXE2E_ERR_STS_1_MC0_LM_IN_MBE_SHIFT						1
#define FXR_RXE2E_ERR_STS_1_MC0_LM_IN_MBE_MASK						0x1ull
#define FXR_RXE2E_ERR_STS_1_MC0_LM_IN_MBE_SMASK						0x2ull
#define FXR_RXE2E_ERR_STS_1_DIAGNOSTIC_SHIFT						0
#define FXR_RXE2E_ERR_STS_1_DIAGNOSTIC_MASK						0x1ull
#define FXR_RXE2E_ERR_STS_1_DIAGNOSTIC_SMASK						0x1ull
/*
* Table #21 of fxr_top - RXE2E_ERR_CLR_1
* This is the Error Clear CSR. Writing a 1 to a valid bit will clear the 
* corresponding bit in the #%%#RXE2E_ERR_STS_1#%%# CSR.
*/
#define FXR_RXE2E_ERR_CLR_1								(FXR_RX_E2E_CSRS + 0x000000000308)
#define FXR_RXE2E_ERR_CLR_1_RESETCSR							0x0000000000000000ull
#define FXR_RXE2E_ERR_CLR_1_EVENTS_SHIFT						0
#define FXR_RXE2E_ERR_CLR_1_EVENTS_MASK							0x1FFFFFull
#define FXR_RXE2E_ERR_CLR_1_EVENTS_SMASK						0x1FFFFFull
/*
* Table #22 of fxr_top - RXE2E_ERR_FRC_1
* This is the Error Force CSR. Writing a 1 to a valid bit will set the 
* corresponding bit in the #%%#RXE2E_ERR_STS_1#%%# CSR.
*/
#define FXR_RXE2E_ERR_FRC_1								(FXR_RX_E2E_CSRS + 0x000000000310)
#define FXR_RXE2E_ERR_FRC_1_RESETCSR							0x0000000000000000ull
#define FXR_RXE2E_ERR_FRC_1_EVENTS_SHIFT						0
#define FXR_RXE2E_ERR_FRC_1_EVENTS_MASK							0x1FFFFFull
#define FXR_RXE2E_ERR_FRC_1_EVENTS_SMASK						0x1FFFFFull
/*
* Table #23 of fxr_top - RXE2E_ERR_EN_HOST_1
* This is the Error Enable for the Host Interrupt. If a bit is set, the 
* corresponding error bit in #%%#RXE2E_ERR_STS_1#%%# will cause an interrupt on 
* the HOST interrupt signal.
*/
#define FXR_RXE2E_ERR_EN_HOST_1								(FXR_RX_E2E_CSRS + 0x000000000318)
#define FXR_RXE2E_ERR_EN_HOST_1_RESETCSR						0x0000000000000000ull
#define FXR_RXE2E_ERR_EN_HOST_1_EVENTS_SHIFT						0
#define FXR_RXE2E_ERR_EN_HOST_1_EVENTS_MASK						0x1FFFFFull
#define FXR_RXE2E_ERR_EN_HOST_1_EVENTS_SMASK						0x1FFFFFull
/*
* Table #24 of fxr_top - RXE2E_ERR_FIRST_HOST_1
* This is the First Error CSR for the Host Interrupt. When this CSR is clear, it 
* will capture the next #%%#RXE2E_ERR_STS_1#%%# value when a new HOST Interrupt 
* occurs.
*/
#define FXR_RXE2E_ERR_FIRST_HOST_1							(FXR_RX_E2E_CSRS + 0x000000000320)
#define FXR_RXE2E_ERR_FIRST_HOST_1_RESETCSR						0x0000000000000000ull
#define FXR_RXE2E_ERR_FIRST_HOST_1_EVENTS_SHIFT						0
#define FXR_RXE2E_ERR_FIRST_HOST_1_EVENTS_MASK						0x1FFFFFull
#define FXR_RXE2E_ERR_FIRST_HOST_1_EVENTS_SMASK						0x1FFFFFull
/*
* Table #25 of fxr_top - RXE2E_ERR_EN_BMC_1
* This is the Error Enable for the BMC Interrupt. If a bit is set, the 
* corresponding error bit in #%%#RXE2E_ERR_STS_1#%%# will cause an interrupt on 
* the BMC interrupt signal.
*/
#define FXR_RXE2E_ERR_EN_BMC_1								(FXR_RX_E2E_CSRS + 0x000000000328)
#define FXR_RXE2E_ERR_EN_BMC_1_RESETCSR							0x0000000000000000ull
#define FXR_RXE2E_ERR_EN_BMC_1_EVENTS_SHIFT						0
#define FXR_RXE2E_ERR_EN_BMC_1_EVENTS_MASK						0x1FFFFFull
#define FXR_RXE2E_ERR_EN_BMC_1_EVENTS_SMASK						0x1FFFFFull
/*
* Table #26 of fxr_top - RXE2E_ERR_FIRST_BMC_1
* 
*/
#define FXR_RXE2E_ERR_FIRST_BMC_1							(FXR_RX_E2E_CSRS + 0x000000000330)
#define FXR_RXE2E_ERR_FIRST_BMC_1_RESETCSR						0x0000000000000000ull
#define FXR_RXE2E_ERR_FIRST_BMC_1_EVENTS_SHIFT						0
#define FXR_RXE2E_ERR_FIRST_BMC_1_EVENTS_MASK						0x1FFFFFull
#define FXR_RXE2E_ERR_FIRST_BMC_1_EVENTS_SMASK						0x1FFFFFull
/*
* Table #27 of fxr_top - RXE2E_ERR_EN_QUAR_1
* This is the Error Enable for the Quarantine Interrupt. If a bit is set, the 
* corresponding error bit in #%%#RXE2E_ERR_STS_1#%%# will cause an interrupt on 
* the QUAR interrupt signal.
*/
#define FXR_RXE2E_ERR_EN_QUAR_1								(FXR_RX_E2E_CSRS + 0x000000000338)
#define FXR_RXE2E_ERR_EN_QUAR_1_RESETCSR						0x0000000000000000ull
#define FXR_RXE2E_ERR_EN_QUAR_1_EVENTS_SHIFT						0
#define FXR_RXE2E_ERR_EN_QUAR_1_EVENTS_MASK						0x1FFFFFull
#define FXR_RXE2E_ERR_EN_QUAR_1_EVENTS_SMASK						0x1FFFFFull
/*
* Table #28 of fxr_top - RXE2E_ERR_FIRST_QUAR_1
* This is the First Error CSR for the Quarantine Interrupt. When this CSR is 
* clear, it will capture the next #%%#RXE2E_ERR_STS_1#%%# value when a new QUAR 
* Interrupt occurs.
*/
#define FXR_RXE2E_ERR_FIRST_QUAR_1							(FXR_RX_E2E_CSRS + 0x000000000340)
#define FXR_RXE2E_ERR_FIRST_QUAR_1_RESETCSR						0x0000000000000000ull
#define FXR_RXE2E_ERR_FIRST_QUAR_1_EVENTS_SHIFT						0
#define FXR_RXE2E_ERR_FIRST_QUAR_1_EVENTS_MASK						0x1FFFFFull
#define FXR_RXE2E_ERR_FIRST_QUAR_1_EVENTS_SMASK						0x1FFFFFull
/*
* Table #29 of fxr_top - RXE2E_ERR_SBE_MBE_CNTR_SUMMARY_STATUS
* This is a summary status register for the sbe/mbe err counters in the various 
* errinfo regs. It saves having to read all the error info regs looking for 
* sbe/mbe cntr values.
*/
#define FXR_RXE2E_ERR_SBE_MBE_CNTR_SUMMARY_STATUS					(FXR_RX_E2E_CSRS + 0x000000000400)
#define FXR_RXE2E_ERR_SBE_MBE_CNTR_SUMMARY_STATUS_RESETCSR				0x0000000000000000ull
#define FXR_RXE2E_ERR_SBE_MBE_CNTR_SUMMARY_STATUS_SOME_SBE_CNTR_MAX_SHIFT		3
#define FXR_RXE2E_ERR_SBE_MBE_CNTR_SUMMARY_STATUS_SOME_SBE_CNTR_MAX_MASK		0x1ull
#define FXR_RXE2E_ERR_SBE_MBE_CNTR_SUMMARY_STATUS_SOME_SBE_CNTR_MAX_SMASK		0x8ull
#define FXR_RXE2E_ERR_SBE_MBE_CNTR_SUMMARY_STATUS_SOME_SBE_CNTR_NON_ZERO_SHIFT		2
#define FXR_RXE2E_ERR_SBE_MBE_CNTR_SUMMARY_STATUS_SOME_SBE_CNTR_NON_ZERO_MASK		0x1ull
#define FXR_RXE2E_ERR_SBE_MBE_CNTR_SUMMARY_STATUS_SOME_SBE_CNTR_NON_ZERO_SMASK		0x4ull
#define FXR_RXE2E_ERR_SBE_MBE_CNTR_SUMMARY_STATUS_SOME_MBE_CNTR_MAX_SHIFT		1
#define FXR_RXE2E_ERR_SBE_MBE_CNTR_SUMMARY_STATUS_SOME_MBE_CNTR_MAX_MASK		0x1ull
#define FXR_RXE2E_ERR_SBE_MBE_CNTR_SUMMARY_STATUS_SOME_MBE_CNTR_MAX_SMASK		0x2ull
#define FXR_RXE2E_ERR_SBE_MBE_CNTR_SUMMARY_STATUS_SOME_MBE_CNTR_NON_ZERO_SHIFT		0
#define FXR_RXE2E_ERR_SBE_MBE_CNTR_SUMMARY_STATUS_SOME_MBE_CNTR_NON_ZERO_MASK		0x1ull
#define FXR_RXE2E_ERR_SBE_MBE_CNTR_SUMMARY_STATUS_SOME_MBE_CNTR_NON_ZERO_SMASK		0x1ull
/*
* Table #30 of fxr_top - RXE2E_ERR_INFO_MC0_LM_INPUT_SBE_MBE
* Error Info for the MC0 Linkmux input #%%#mc0_lm_in_sbe#%%# and 
* #%%#mc0_lm_in_mbe#%%# events. There is no address associated with these. There 
* are 4 ecc domains: 3:0 cover data 255:192, 191:128, 127:64, 63:0 respectively. 
* In case of simultaneous errors in more than 1 ecc domain, the syndrome of the 
* least significant ecc domain is what is saved.
*/
#define FXR_RXE2E_ERR_INFO_MC0_LM_INPUT_SBE_MBE						(FXR_RX_E2E_CSRS + 0x000000000408)
#define FXR_RXE2E_ERR_INFO_MC0_LM_INPUT_SBE_MBE_RESETCSR				0x0000000000000000ull
#define FXR_RXE2E_ERR_INFO_MC0_LM_INPUT_SBE_MBE_SBE_COUNT_SHIFT				46
#define FXR_RXE2E_ERR_INFO_MC0_LM_INPUT_SBE_MBE_SBE_COUNT_MASK				0xFFull
#define FXR_RXE2E_ERR_INFO_MC0_LM_INPUT_SBE_MBE_SBE_COUNT_SMASK				0x3FC00000000000ull
#define FXR_RXE2E_ERR_INFO_MC0_LM_INPUT_SBE_MBE_SBE_SHIFT				42
#define FXR_RXE2E_ERR_INFO_MC0_LM_INPUT_SBE_MBE_SBE_MASK				0xFull
#define FXR_RXE2E_ERR_INFO_MC0_LM_INPUT_SBE_MBE_SBE_SMASK				0x3C0000000000ull
#define FXR_RXE2E_ERR_INFO_MC0_LM_INPUT_SBE_MBE_SBE_LAST_DOMAIN_SHIFT			40
#define FXR_RXE2E_ERR_INFO_MC0_LM_INPUT_SBE_MBE_SBE_LAST_DOMAIN_MASK			0x3ull
#define FXR_RXE2E_ERR_INFO_MC0_LM_INPUT_SBE_MBE_SBE_LAST_DOMAIN_SMASK			0x30000000000ull
#define FXR_RXE2E_ERR_INFO_MC0_LM_INPUT_SBE_MBE_SBE_LAST_SYNDROME_SHIFT			32
#define FXR_RXE2E_ERR_INFO_MC0_LM_INPUT_SBE_MBE_SBE_LAST_SYNDROME_MASK			0xFFull
#define FXR_RXE2E_ERR_INFO_MC0_LM_INPUT_SBE_MBE_SBE_LAST_SYNDROME_SMASK			0xFF00000000ull
#define FXR_RXE2E_ERR_INFO_MC0_LM_INPUT_SBE_MBE_MBE_COUNT_SHIFT				14
#define FXR_RXE2E_ERR_INFO_MC0_LM_INPUT_SBE_MBE_MBE_COUNT_MASK				0xFFull
#define FXR_RXE2E_ERR_INFO_MC0_LM_INPUT_SBE_MBE_MBE_COUNT_SMASK				0x3FC000ull
#define FXR_RXE2E_ERR_INFO_MC0_LM_INPUT_SBE_MBE_MBE_SHIFT				10
#define FXR_RXE2E_ERR_INFO_MC0_LM_INPUT_SBE_MBE_MBE_MASK				0xFull
#define FXR_RXE2E_ERR_INFO_MC0_LM_INPUT_SBE_MBE_MBE_SMASK				0x3C00ull
#define FXR_RXE2E_ERR_INFO_MC0_LM_INPUT_SBE_MBE_MBE_LAST_DOMAIN_SHIFT			8
#define FXR_RXE2E_ERR_INFO_MC0_LM_INPUT_SBE_MBE_MBE_LAST_DOMAIN_MASK			0x3ull
#define FXR_RXE2E_ERR_INFO_MC0_LM_INPUT_SBE_MBE_MBE_LAST_DOMAIN_SMASK			0x300ull
#define FXR_RXE2E_ERR_INFO_MC0_LM_INPUT_SBE_MBE_MBE_LAST_SYNDROME_SHIFT			0
#define FXR_RXE2E_ERR_INFO_MC0_LM_INPUT_SBE_MBE_MBE_LAST_SYNDROME_MASK			0xFFull
#define FXR_RXE2E_ERR_INFO_MC0_LM_INPUT_SBE_MBE_MBE_LAST_SYNDROME_SMASK			0xFFull
/*
* Table #31 of fxr_top - RXE2E_ERR_INFO_MC1_LM_INPUT_SBE_MBE
* Error Info for the MC1 Linkmux input #%%#mc1_lm_in_sbe#%%# and 
* #%%#mc1_lm_in_mbe#%%# events. There is no address associated with these. There 
* are 4 ecc domains: 3:0 cover data 255:192, 191:128, 127:64, 63:0 respectively. 
* In case of simultaneous errors in more than 1 ecc domain, the syndrome of the 
* least significant ecc domain is what is saved.
*/
#define FXR_RXE2E_ERR_INFO_MC1_LM_INPUT_SBE_MBE						(FXR_RX_E2E_CSRS + 0x000000000410)
#define FXR_RXE2E_ERR_INFO_MC1_LM_INPUT_SBE_MBE_RESETCSR				0x0000000000000000ull
#define FXR_RXE2E_ERR_INFO_MC1_LM_INPUT_SBE_MBE_SBE_COUNT_SHIFT				46
#define FXR_RXE2E_ERR_INFO_MC1_LM_INPUT_SBE_MBE_SBE_COUNT_MASK				0xFFFull
#define FXR_RXE2E_ERR_INFO_MC1_LM_INPUT_SBE_MBE_SBE_COUNT_SMASK				0x3FFC00000000000ull
#define FXR_RXE2E_ERR_INFO_MC1_LM_INPUT_SBE_MBE_SBE_SHIFT				42
#define FXR_RXE2E_ERR_INFO_MC1_LM_INPUT_SBE_MBE_SBE_MASK				0xFull
#define FXR_RXE2E_ERR_INFO_MC1_LM_INPUT_SBE_MBE_SBE_SMASK				0x3C0000000000ull
#define FXR_RXE2E_ERR_INFO_MC1_LM_INPUT_SBE_MBE_SBE_LAST_DOMAIN_SHIFT			40
#define FXR_RXE2E_ERR_INFO_MC1_LM_INPUT_SBE_MBE_SBE_LAST_DOMAIN_MASK			0x3ull
#define FXR_RXE2E_ERR_INFO_MC1_LM_INPUT_SBE_MBE_SBE_LAST_DOMAIN_SMASK			0x30000000000ull
#define FXR_RXE2E_ERR_INFO_MC1_LM_INPUT_SBE_MBE_SBE_LAST_SYNDROME_SHIFT			32
#define FXR_RXE2E_ERR_INFO_MC1_LM_INPUT_SBE_MBE_SBE_LAST_SYNDROME_MASK			0xFFull
#define FXR_RXE2E_ERR_INFO_MC1_LM_INPUT_SBE_MBE_SBE_LAST_SYNDROME_SMASK			0xFF00000000ull
#define FXR_RXE2E_ERR_INFO_MC1_LM_INPUT_SBE_MBE_MBE_COUNT_SHIFT				14
#define FXR_RXE2E_ERR_INFO_MC1_LM_INPUT_SBE_MBE_MBE_COUNT_MASK				0xFull
#define FXR_RXE2E_ERR_INFO_MC1_LM_INPUT_SBE_MBE_MBE_COUNT_SMASK				0x3C000ull
#define FXR_RXE2E_ERR_INFO_MC1_LM_INPUT_SBE_MBE_MBE_SHIFT				10
#define FXR_RXE2E_ERR_INFO_MC1_LM_INPUT_SBE_MBE_MBE_MASK				0xFull
#define FXR_RXE2E_ERR_INFO_MC1_LM_INPUT_SBE_MBE_MBE_SMASK				0x3C00ull
#define FXR_RXE2E_ERR_INFO_MC1_LM_INPUT_SBE_MBE_MBE_LAST_DOMAIN_SHIFT			8
#define FXR_RXE2E_ERR_INFO_MC1_LM_INPUT_SBE_MBE_MBE_LAST_DOMAIN_MASK			0x3ull
#define FXR_RXE2E_ERR_INFO_MC1_LM_INPUT_SBE_MBE_MBE_LAST_DOMAIN_SMASK			0x300ull
#define FXR_RXE2E_ERR_INFO_MC1_LM_INPUT_SBE_MBE_MBE_LAST_SYNDROME_SHIFT			0
#define FXR_RXE2E_ERR_INFO_MC1_LM_INPUT_SBE_MBE_MBE_LAST_SYNDROME_MASK			0xFFull
#define FXR_RXE2E_ERR_INFO_MC1_LM_INPUT_SBE_MBE_MBE_LAST_SYNDROME_SMASK			0xFFull
/*
* Table #32 of fxr_top - RXE2E_ERR_INFO_MC0_INPUT_SBE_MBE
* Error Info for the #%%#mc0_input_fifo_sbe#%%# and #%%#mc0_input_fifo_mbe#%%# 
* events. There are 4 ecc domains: 3:0 cover data 255:192, 191:128, 127:64, 63:0 
* respectively. In case of simultaneous errors in more than 1 ecc domain, the 
* syndrome of the least significant ecc domain is what is saved.
*/
#define FXR_RXE2E_ERR_INFO_MC0_INPUT_SBE_MBE						(FXR_RX_E2E_CSRS + 0x000000000418)
#define FXR_RXE2E_ERR_INFO_MC0_INPUT_SBE_MBE_RESETCSR					0x0000000000000000ull
#define FXR_RXE2E_ERR_INFO_MC0_INPUT_SBE_MBE_SBE_LAST_ADDRESS_SHIFT			50
#define FXR_RXE2E_ERR_INFO_MC0_INPUT_SBE_MBE_SBE_LAST_ADDRESS_MASK			0x3Full
#define FXR_RXE2E_ERR_INFO_MC0_INPUT_SBE_MBE_SBE_LAST_ADDRESS_SMASK			0xFC000000000000ull
#define FXR_RXE2E_ERR_INFO_MC0_INPUT_SBE_MBE_SBE_COUNT_SHIFT				38
#define FXR_RXE2E_ERR_INFO_MC0_INPUT_SBE_MBE_SBE_COUNT_MASK				0xFFFull
#define FXR_RXE2E_ERR_INFO_MC0_INPUT_SBE_MBE_SBE_COUNT_SMASK				0x3FFC000000000ull
#define FXR_RXE2E_ERR_INFO_MC0_INPUT_SBE_MBE_SBE_SHIFT					34
#define FXR_RXE2E_ERR_INFO_MC0_INPUT_SBE_MBE_SBE_MASK					0xFull
#define FXR_RXE2E_ERR_INFO_MC0_INPUT_SBE_MBE_SBE_SMASK					0x3C00000000ull
#define FXR_RXE2E_ERR_INFO_MC0_INPUT_SBE_MBE_SBE_LAST_DOMAIN_SHIFT			32
#define FXR_RXE2E_ERR_INFO_MC0_INPUT_SBE_MBE_SBE_LAST_DOMAIN_MASK			0x3ull
#define FXR_RXE2E_ERR_INFO_MC0_INPUT_SBE_MBE_SBE_LAST_DOMAIN_SMASK			0x300000000ull
#define FXR_RXE2E_ERR_INFO_MC0_INPUT_SBE_MBE_SBE_LAST_SYNDROME_SHIFT			24
#define FXR_RXE2E_ERR_INFO_MC0_INPUT_SBE_MBE_SBE_LAST_SYNDROME_MASK			0xFFull
#define FXR_RXE2E_ERR_INFO_MC0_INPUT_SBE_MBE_SBE_LAST_SYNDROME_SMASK			0xFF000000ull
#define FXR_RXE2E_ERR_INFO_MC0_INPUT_SBE_MBE_MBE_LAST_ADDRESS_SHIFT			18
#define FXR_RXE2E_ERR_INFO_MC0_INPUT_SBE_MBE_MBE_LAST_ADDRESS_MASK			0x3Full
#define FXR_RXE2E_ERR_INFO_MC0_INPUT_SBE_MBE_MBE_LAST_ADDRESS_SMASK			0xFC0000ull
#define FXR_RXE2E_ERR_INFO_MC0_INPUT_SBE_MBE_MBE_COUNT_SHIFT				14
#define FXR_RXE2E_ERR_INFO_MC0_INPUT_SBE_MBE_MBE_COUNT_MASK				0xFull
#define FXR_RXE2E_ERR_INFO_MC0_INPUT_SBE_MBE_MBE_COUNT_SMASK				0x3C000ull
#define FXR_RXE2E_ERR_INFO_MC0_INPUT_SBE_MBE_MBE_SHIFT					10
#define FXR_RXE2E_ERR_INFO_MC0_INPUT_SBE_MBE_MBE_MASK					0xFull
#define FXR_RXE2E_ERR_INFO_MC0_INPUT_SBE_MBE_MBE_SMASK					0x3C00ull
#define FXR_RXE2E_ERR_INFO_MC0_INPUT_SBE_MBE_MBE_LAST_DOMAIN_SHIFT			8
#define FXR_RXE2E_ERR_INFO_MC0_INPUT_SBE_MBE_MBE_LAST_DOMAIN_MASK			0x3ull
#define FXR_RXE2E_ERR_INFO_MC0_INPUT_SBE_MBE_MBE_LAST_DOMAIN_SMASK			0x300ull
#define FXR_RXE2E_ERR_INFO_MC0_INPUT_SBE_MBE_MBE_LAST_SYNDROME_SHIFT			0
#define FXR_RXE2E_ERR_INFO_MC0_INPUT_SBE_MBE_MBE_LAST_SYNDROME_MASK			0xFFull
#define FXR_RXE2E_ERR_INFO_MC0_INPUT_SBE_MBE_MBE_LAST_SYNDROME_SMASK			0xFFull
/*
* Table #33 of fxr_top - RXE2E_ERR_INFO_MC1_INPUT_SBE_MBE
* Error Info for the #%%#mc1_input_fifo_sbe#%%# and #%%#mc1_input_fifo_mbe#%%# 
* events. There are 4 ecc domains: 3:0 cover data 255:192, 191:128, 127:64, 63:0 
* respectively. In case of simultaneous errors in more than 1 ecc domain, the 
* syndrome of the least significant ecc domain is what is saved.
*/
#define FXR_RXE2E_ERR_INFO_MC1_INPUT_SBE_MBE						(FXR_RX_E2E_CSRS + 0x000000000420)
#define FXR_RXE2E_ERR_INFO_MC1_INPUT_SBE_MBE_RESETCSR					0x0000000000000000ull
#define FXR_RXE2E_ERR_INFO_MC1_INPUT_SBE_MBE_SBE_LAST_ADDRESS_SHIFT			50
#define FXR_RXE2E_ERR_INFO_MC1_INPUT_SBE_MBE_SBE_LAST_ADDRESS_MASK			0x3Full
#define FXR_RXE2E_ERR_INFO_MC1_INPUT_SBE_MBE_SBE_LAST_ADDRESS_SMASK			0xFC000000000000ull
#define FXR_RXE2E_ERR_INFO_MC1_INPUT_SBE_MBE_SBE_COUNT_SHIFT				38
#define FXR_RXE2E_ERR_INFO_MC1_INPUT_SBE_MBE_SBE_COUNT_MASK				0xFFFull
#define FXR_RXE2E_ERR_INFO_MC1_INPUT_SBE_MBE_SBE_COUNT_SMASK				0x3FFC000000000ull
#define FXR_RXE2E_ERR_INFO_MC1_INPUT_SBE_MBE_SBE_SHIFT					34
#define FXR_RXE2E_ERR_INFO_MC1_INPUT_SBE_MBE_SBE_MASK					0xFull
#define FXR_RXE2E_ERR_INFO_MC1_INPUT_SBE_MBE_SBE_SMASK					0x3C00000000ull
#define FXR_RXE2E_ERR_INFO_MC1_INPUT_SBE_MBE_SBE_LAST_DOMAIN_SHIFT			32
#define FXR_RXE2E_ERR_INFO_MC1_INPUT_SBE_MBE_SBE_LAST_DOMAIN_MASK			0x3ull
#define FXR_RXE2E_ERR_INFO_MC1_INPUT_SBE_MBE_SBE_LAST_DOMAIN_SMASK			0x300000000ull
#define FXR_RXE2E_ERR_INFO_MC1_INPUT_SBE_MBE_SBE_LAST_SYNDROME_SHIFT			24
#define FXR_RXE2E_ERR_INFO_MC1_INPUT_SBE_MBE_SBE_LAST_SYNDROME_MASK			0xFFull
#define FXR_RXE2E_ERR_INFO_MC1_INPUT_SBE_MBE_SBE_LAST_SYNDROME_SMASK			0xFF000000ull
#define FXR_RXE2E_ERR_INFO_MC1_INPUT_SBE_MBE_MBE_LAST_ADDRESS_SHIFT			18
#define FXR_RXE2E_ERR_INFO_MC1_INPUT_SBE_MBE_MBE_LAST_ADDRESS_MASK			0x3Full
#define FXR_RXE2E_ERR_INFO_MC1_INPUT_SBE_MBE_MBE_LAST_ADDRESS_SMASK			0xFC0000ull
#define FXR_RXE2E_ERR_INFO_MC1_INPUT_SBE_MBE_MBE_COUNT_SHIFT				14
#define FXR_RXE2E_ERR_INFO_MC1_INPUT_SBE_MBE_MBE_COUNT_MASK				0xFull
#define FXR_RXE2E_ERR_INFO_MC1_INPUT_SBE_MBE_MBE_COUNT_SMASK				0x3C000ull
#define FXR_RXE2E_ERR_INFO_MC1_INPUT_SBE_MBE_MBE_SHIFT					10
#define FXR_RXE2E_ERR_INFO_MC1_INPUT_SBE_MBE_MBE_MASK					0xFull
#define FXR_RXE2E_ERR_INFO_MC1_INPUT_SBE_MBE_MBE_SMASK					0x3C00ull
#define FXR_RXE2E_ERR_INFO_MC1_INPUT_SBE_MBE_MBE_LAST_DOMAIN_SHIFT			8
#define FXR_RXE2E_ERR_INFO_MC1_INPUT_SBE_MBE_MBE_LAST_DOMAIN_MASK			0x3ull
#define FXR_RXE2E_ERR_INFO_MC1_INPUT_SBE_MBE_MBE_LAST_DOMAIN_SMASK			0x300ull
#define FXR_RXE2E_ERR_INFO_MC1_INPUT_SBE_MBE_MBE_LAST_SYNDROME_SHIFT			0
#define FXR_RXE2E_ERR_INFO_MC1_INPUT_SBE_MBE_MBE_LAST_SYNDROME_MASK			0xFFull
#define FXR_RXE2E_ERR_INFO_MC1_INPUT_SBE_MBE_MBE_LAST_SYNDROME_SMASK			0xFFull
/*
* Table #34 of fxr_top - RXE2E_ERR_INFO_PSN_CACHE_TAG_SBE
* Error Info for the PSN Cache tag #%%#psn_cache_tag_sbe#%%# events. There are 8 
* ecc domains each domain covers two tag ways. tag_mem[543:0] = 
* {tag_ecc[7:0][7:0],tag_way_data[7:0][1:0][29:0]}
*/
#define FXR_RXE2E_ERR_INFO_PSN_CACHE_TAG_SBE						(FXR_RX_E2E_CSRS + 0x000000000428)
#define FXR_RXE2E_ERR_INFO_PSN_CACHE_TAG_SBE_RESETCSR					0x0000000000000000ull
#define FXR_RXE2E_ERR_INFO_PSN_CACHE_TAG_SBE_SBE_LAST_ADDRESS_SHIFT			31
#define FXR_RXE2E_ERR_INFO_PSN_CACHE_TAG_SBE_SBE_LAST_ADDRESS_MASK			0x7FFull
#define FXR_RXE2E_ERR_INFO_PSN_CACHE_TAG_SBE_SBE_LAST_ADDRESS_SMASK			0x3FF80000000ull
#define FXR_RXE2E_ERR_INFO_PSN_CACHE_TAG_SBE_SBE_COUNT_SHIFT				19
#define FXR_RXE2E_ERR_INFO_PSN_CACHE_TAG_SBE_SBE_COUNT_MASK				0xFFFull
#define FXR_RXE2E_ERR_INFO_PSN_CACHE_TAG_SBE_SBE_COUNT_SMASK				0x7FF80000ull
#define FXR_RXE2E_ERR_INFO_PSN_CACHE_TAG_SBE_SBE_SHIFT					11
#define FXR_RXE2E_ERR_INFO_PSN_CACHE_TAG_SBE_SBE_MASK					0xFFull
#define FXR_RXE2E_ERR_INFO_PSN_CACHE_TAG_SBE_SBE_SMASK					0x7F800ull
#define FXR_RXE2E_ERR_INFO_PSN_CACHE_TAG_SBE_SBE_LAST_DOMAIN_SHIFT			8
#define FXR_RXE2E_ERR_INFO_PSN_CACHE_TAG_SBE_SBE_LAST_DOMAIN_MASK			0x7ull
#define FXR_RXE2E_ERR_INFO_PSN_CACHE_TAG_SBE_SBE_LAST_DOMAIN_SMASK			0x700ull
#define FXR_RXE2E_ERR_INFO_PSN_CACHE_TAG_SBE_SBE_LAST_SYNDROME_SHIFT			0
#define FXR_RXE2E_ERR_INFO_PSN_CACHE_TAG_SBE_SBE_LAST_SYNDROME_MASK			0xFFull
#define FXR_RXE2E_ERR_INFO_PSN_CACHE_TAG_SBE_SBE_LAST_SYNDROME_SMASK			0xFFull
/*
* Table #35 of fxr_top - RXE2E_ERR_INFO_PSN_CACHE_TAG_MBE
* Error Info for the PSN Cache tag #%%#psn_cache_tag_mbe#%%# events. There are 8 
* ecc domains each domain covers two tag ways. tag_mem[543:0] = 
* {tag_ecc[7:0][7:0],tag_way_data[7:0][1:0][29:0]}
*/
#define FXR_RXE2E_ERR_INFO_PSN_CACHE_TAG_MBE						(FXR_RX_E2E_CSRS + 0x000000000430)
#define FXR_RXE2E_ERR_INFO_PSN_CACHE_TAG_MBE_RESETCSR					0x0000000000000000ull
#define FXR_RXE2E_ERR_INFO_PSN_CACHE_TAG_MBE_MBE_LAST_ADDRESS_SHIFT			23
#define FXR_RXE2E_ERR_INFO_PSN_CACHE_TAG_MBE_MBE_LAST_ADDRESS_MASK			0x7FFull
#define FXR_RXE2E_ERR_INFO_PSN_CACHE_TAG_MBE_MBE_LAST_ADDRESS_SMASK			0x3FF800000ull
#define FXR_RXE2E_ERR_INFO_PSN_CACHE_TAG_MBE_MBE_COUNT_SHIFT				19
#define FXR_RXE2E_ERR_INFO_PSN_CACHE_TAG_MBE_MBE_COUNT_MASK				0xFull
#define FXR_RXE2E_ERR_INFO_PSN_CACHE_TAG_MBE_MBE_COUNT_SMASK				0x780000ull
#define FXR_RXE2E_ERR_INFO_PSN_CACHE_TAG_MBE_MBE_SHIFT					11
#define FXR_RXE2E_ERR_INFO_PSN_CACHE_TAG_MBE_MBE_MASK					0xFFull
#define FXR_RXE2E_ERR_INFO_PSN_CACHE_TAG_MBE_MBE_SMASK					0x7F800ull
#define FXR_RXE2E_ERR_INFO_PSN_CACHE_TAG_MBE_MBE_LAST_DOMAIN_SHIFT			8
#define FXR_RXE2E_ERR_INFO_PSN_CACHE_TAG_MBE_MBE_LAST_DOMAIN_MASK			0x7ull
#define FXR_RXE2E_ERR_INFO_PSN_CACHE_TAG_MBE_MBE_LAST_DOMAIN_SMASK			0x700ull
#define FXR_RXE2E_ERR_INFO_PSN_CACHE_TAG_MBE_MBE_LAST_SYNDROME_SHIFT			0
#define FXR_RXE2E_ERR_INFO_PSN_CACHE_TAG_MBE_MBE_LAST_SYNDROME_MASK			0xFFull
#define FXR_RXE2E_ERR_INFO_PSN_CACHE_TAG_MBE_MBE_LAST_SYNDROME_SMASK			0xFFull
/*
* Table #36 of fxr_top - RXE2E_ERR_INFO_PSN_CACHE_DATA_SBE_MBE
* Error Info for the PSN Cache Data #%%#psn_cache_data_sbe#%%# and 
* #%%#psn_cache_data_mbe#%%# events. There is no address associated with these. 
* 
*/
#define FXR_RXE2E_ERR_INFO_PSN_CACHE_DATA_SBE_MBE					(FXR_RX_E2E_CSRS + 0x000000000438)
#define FXR_RXE2E_ERR_INFO_PSN_CACHE_DATA_SBE_MBE_RESETCSR				0x0000000000000000ull
#define FXR_RXE2E_ERR_INFO_PSN_CACHE_DATA_SBE_MBE_SBE_COUNT_SHIFT			20
#define FXR_RXE2E_ERR_INFO_PSN_CACHE_DATA_SBE_MBE_SBE_COUNT_MASK			0xFFFull
#define FXR_RXE2E_ERR_INFO_PSN_CACHE_DATA_SBE_MBE_SBE_COUNT_SMASK			0xFFF00000ull
#define FXR_RXE2E_ERR_INFO_PSN_CACHE_DATA_SBE_MBE_SBE_LAST_SYNDROME_SHIFT		12
#define FXR_RXE2E_ERR_INFO_PSN_CACHE_DATA_SBE_MBE_SBE_LAST_SYNDROME_MASK		0xFFull
#define FXR_RXE2E_ERR_INFO_PSN_CACHE_DATA_SBE_MBE_SBE_LAST_SYNDROME_SMASK		0xFF000ull
#define FXR_RXE2E_ERR_INFO_PSN_CACHE_DATA_SBE_MBE_MBE_COUNT_SHIFT			8
#define FXR_RXE2E_ERR_INFO_PSN_CACHE_DATA_SBE_MBE_MBE_COUNT_MASK			0xFull
#define FXR_RXE2E_ERR_INFO_PSN_CACHE_DATA_SBE_MBE_MBE_COUNT_SMASK			0xF00ull
#define FXR_RXE2E_ERR_INFO_PSN_CACHE_DATA_SBE_MBE_MBE_LAST_SYNDROME_SHIFT		0
#define FXR_RXE2E_ERR_INFO_PSN_CACHE_DATA_SBE_MBE_MBE_LAST_SYNDROME_MASK		0xFFull
#define FXR_RXE2E_ERR_INFO_PSN_CACHE_DATA_SBE_MBE_MBE_LAST_SYNDROME_SMASK		0xFFull
/*
* Table #37 of fxr_top - RXE2E_ERR_INFO_BIG_SCOREBOARD_SBE
* Error Info for the #%%#big_scoreboard_sbe#%%# events. There are 16 ecc 
* domains. big_scoreboard_mem[1149:0] = {ecc[15:0][7:0],data[15:0][63:0]}. Note 
* that data[15][63:62] is always written with 0. This reflects the big 
* scoreboard width is 1022, not 1024.
*/
#define FXR_RXE2E_ERR_INFO_BIG_SCOREBOARD_SBE						(FXR_RX_E2E_CSRS + 0x000000000440)
#define FXR_RXE2E_ERR_INFO_BIG_SCOREBOARD_SBE_RESETCSR					0x0000000000000000ull
#define FXR_RXE2E_ERR_INFO_BIG_SCOREBOARD_SBE_SBE_LAST_ADDRESS_SHIFT			40
#define FXR_RXE2E_ERR_INFO_BIG_SCOREBOARD_SBE_SBE_LAST_ADDRESS_MASK			0x3FFull
#define FXR_RXE2E_ERR_INFO_BIG_SCOREBOARD_SBE_SBE_LAST_ADDRESS_SMASK			0x3FF0000000000ull
#define FXR_RXE2E_ERR_INFO_BIG_SCOREBOARD_SBE_SBE_COUNT_SHIFT				28
#define FXR_RXE2E_ERR_INFO_BIG_SCOREBOARD_SBE_SBE_COUNT_MASK				0xFFFull
#define FXR_RXE2E_ERR_INFO_BIG_SCOREBOARD_SBE_SBE_COUNT_SMASK				0xFFF0000000ull
#define FXR_RXE2E_ERR_INFO_BIG_SCOREBOARD_SBE_SBE_SHIFT					12
#define FXR_RXE2E_ERR_INFO_BIG_SCOREBOARD_SBE_SBE_MASK					0xFFFFull
#define FXR_RXE2E_ERR_INFO_BIG_SCOREBOARD_SBE_SBE_SMASK					0xFFFF000ull
#define FXR_RXE2E_ERR_INFO_BIG_SCOREBOARD_SBE_SBE_LAST_DOMAIN_SHIFT			8
#define FXR_RXE2E_ERR_INFO_BIG_SCOREBOARD_SBE_SBE_LAST_DOMAIN_MASK			0xFull
#define FXR_RXE2E_ERR_INFO_BIG_SCOREBOARD_SBE_SBE_LAST_DOMAIN_SMASK			0xF00ull
#define FXR_RXE2E_ERR_INFO_BIG_SCOREBOARD_SBE_SBE_LAST_SYNDROME_SHIFT			0
#define FXR_RXE2E_ERR_INFO_BIG_SCOREBOARD_SBE_SBE_LAST_SYNDROME_MASK			0xFFull
#define FXR_RXE2E_ERR_INFO_BIG_SCOREBOARD_SBE_SBE_LAST_SYNDROME_SMASK			0xFFull
/*
* Table #38 of fxr_top - RXE2E_ERR_INFO_BIG_SCOREBOARD_MBE
* Error Info for the #%%#big_scoreboard_mbe#%%# events. There are 16 ecc 
* domains. big_scoreboard_mem[1149:0] = {ecc[15:0][7:0],data[15:0][63:0]}. Note 
* that data[15][63:62] is always written with 0. This reflects the big 
* scoreboard data width is 1022, not 1024.
*/
#define FXR_RXE2E_ERR_INFO_BIG_SCOREBOARD_MBE						(FXR_RX_E2E_CSRS + 0x000000000448)
#define FXR_RXE2E_ERR_INFO_BIG_SCOREBOARD_MBE_RESETCSR					0x0000000000000000ull
#define FXR_RXE2E_ERR_INFO_BIG_SCOREBOARD_MBE_MBE_LAST_ADDRESS_SHIFT			32
#define FXR_RXE2E_ERR_INFO_BIG_SCOREBOARD_MBE_MBE_LAST_ADDRESS_MASK			0x3FFull
#define FXR_RXE2E_ERR_INFO_BIG_SCOREBOARD_MBE_MBE_LAST_ADDRESS_SMASK			0x3FF00000000ull
#define FXR_RXE2E_ERR_INFO_BIG_SCOREBOARD_MBE_MBE_COUNT_SHIFT				28
#define FXR_RXE2E_ERR_INFO_BIG_SCOREBOARD_MBE_MBE_COUNT_MASK				0xFull
#define FXR_RXE2E_ERR_INFO_BIG_SCOREBOARD_MBE_MBE_COUNT_SMASK				0xF0000000ull
#define FXR_RXE2E_ERR_INFO_BIG_SCOREBOARD_MBE_MBE_SHIFT					12
#define FXR_RXE2E_ERR_INFO_BIG_SCOREBOARD_MBE_MBE_MASK					0xFFFFull
#define FXR_RXE2E_ERR_INFO_BIG_SCOREBOARD_MBE_MBE_SMASK					0xFFFF000ull
#define FXR_RXE2E_ERR_INFO_BIG_SCOREBOARD_MBE_MBE_LAST_DOMAIN_SHIFT			8
#define FXR_RXE2E_ERR_INFO_BIG_SCOREBOARD_MBE_MBE_LAST_DOMAIN_MASK			0xFull
#define FXR_RXE2E_ERR_INFO_BIG_SCOREBOARD_MBE_MBE_LAST_DOMAIN_SMASK			0xF00ull
#define FXR_RXE2E_ERR_INFO_BIG_SCOREBOARD_MBE_MBE_LAST_SYNDROME_SHIFT			0
#define FXR_RXE2E_ERR_INFO_BIG_SCOREBOARD_MBE_MBE_LAST_SYNDROME_MASK			0xFFull
#define FXR_RXE2E_ERR_INFO_BIG_SCOREBOARD_MBE_MBE_LAST_SYNDROME_SMASK			0xFFull
/*
* Table #39 of fxr_top - RXE2E_ERR_INFO_CRC
* Error Info for the #%%#MC0 crc#%%# and #%%#MC1 crc#%%# events.
*/
#define FXR_RXE2E_ERR_INFO_CRC								(FXR_RX_E2E_CSRS + 0x000000000450)
#define FXR_RXE2E_ERR_INFO_CRC_RESETCSR							0x0000000000000000ull
#define FXR_RXE2E_ERR_INFO_CRC_MC1_CRC_CNT_SHIFT					16
#define FXR_RXE2E_ERR_INFO_CRC_MC1_CRC_CNT_MASK						0xFFFFull
#define FXR_RXE2E_ERR_INFO_CRC_MC1_CRC_CNT_SMASK					0xFFFF0000ull
#define FXR_RXE2E_ERR_INFO_CRC_MC0_CRC_CNT_SHIFT					0
#define FXR_RXE2E_ERR_INFO_CRC_MC0_CRC_CNT_MASK						0xFFFFull
#define FXR_RXE2E_ERR_INFO_CRC_MC0_CRC_CNT_SMASK					0xFFFFull
/*
* Table #40 of fxr_top - RXE2E_ERR_INJECT_SBE_MBE
* Error Injection for the various sbe/mbe fields. Setting a single bit will 
* cause an sbe in the ecc field and cause that bit to be flipped, no data bits 
* will be flipped. Setting 2 bits will cause an mbe. An even number of bits > 2 
* may or may not cause an mbe. Setting an odd number of bits that is a legal 
* syndrome for that data width will cause an sbe and the corresponding data bit 
* to be flipped. See shrtl_ecc_correct.sv for legal syndromes for each data 
* width.
*/
#define FXR_RXE2E_ERR_INJECT_SBE_MBE							(FXR_RX_E2E_CSRS + 0x000000000458)
#define FXR_RXE2E_ERR_INJECT_SBE_MBE_RESETCSR						0x0000000000000000ull
#define FXR_RXE2E_ERR_INJECT_SBE_MBE_BIG_SCOREBOARD_ERR_INJ_ENABLE_SHIFT		55
#define FXR_RXE2E_ERR_INJECT_SBE_MBE_BIG_SCOREBOARD_ERR_INJ_ENABLE_MASK			0x1ull
#define FXR_RXE2E_ERR_INJECT_SBE_MBE_BIG_SCOREBOARD_ERR_INJ_ENABLE_SMASK		0x80000000000000ull
#define FXR_RXE2E_ERR_INJECT_SBE_MBE_BIG_SCOREBOARD_ERR_INJ_DOMAIN_SHIFT		51
#define FXR_RXE2E_ERR_INJECT_SBE_MBE_BIG_SCOREBOARD_ERR_INJ_DOMAIN_MASK			0xFull
#define FXR_RXE2E_ERR_INJECT_SBE_MBE_BIG_SCOREBOARD_ERR_INJ_DOMAIN_SMASK		0x78000000000000ull
#define FXR_RXE2E_ERR_INJECT_SBE_MBE_BIG_SCOREBOARD_ERR_INJ_MASK_SHIFT			43
#define FXR_RXE2E_ERR_INJECT_SBE_MBE_BIG_SCOREBOARD_ERR_INJ_MASK_MASK			0xFFull
#define FXR_RXE2E_ERR_INJECT_SBE_MBE_BIG_SCOREBOARD_ERR_INJ_MASK_SMASK			0x7F80000000000ull
#define FXR_RXE2E_ERR_INJECT_SBE_MBE_PSN_CACHE_DATA_ERR_INJ_ENABLE_SHIFT		42
#define FXR_RXE2E_ERR_INJECT_SBE_MBE_PSN_CACHE_DATA_ERR_INJ_ENABLE_MASK			0x1ull
#define FXR_RXE2E_ERR_INJECT_SBE_MBE_PSN_CACHE_DATA_ERR_INJ_ENABLE_SMASK		0x40000000000ull
#define FXR_RXE2E_ERR_INJECT_SBE_MBE_PSN_CACHE_DATA_ERR_INJ_MASK_SHIFT			34
#define FXR_RXE2E_ERR_INJECT_SBE_MBE_PSN_CACHE_DATA_ERR_INJ_MASK_MASK			0xFFull
#define FXR_RXE2E_ERR_INJECT_SBE_MBE_PSN_CACHE_DATA_ERR_INJ_MASK_SMASK			0x3FC00000000ull
#define FXR_RXE2E_ERR_INJECT_SBE_MBE_PSN_CACHE_TAG_ERR_INJ_ENABLE_SHIFT			33
#define FXR_RXE2E_ERR_INJECT_SBE_MBE_PSN_CACHE_TAG_ERR_INJ_ENABLE_MASK			0x1ull
#define FXR_RXE2E_ERR_INJECT_SBE_MBE_PSN_CACHE_TAG_ERR_INJ_ENABLE_SMASK			0x200000000ull
#define FXR_RXE2E_ERR_INJECT_SBE_MBE_PSN_CACHE_TAG_ERR_INJ_DOMAIN_SHIFT			30
#define FXR_RXE2E_ERR_INJECT_SBE_MBE_PSN_CACHE_TAG_ERR_INJ_DOMAIN_MASK			0x7ull
#define FXR_RXE2E_ERR_INJECT_SBE_MBE_PSN_CACHE_TAG_ERR_INJ_DOMAIN_SMASK			0x1C0000000ull
#define FXR_RXE2E_ERR_INJECT_SBE_MBE_PSN_CACHE_TAG_ERR_INJ_MASK_SHIFT			22
#define FXR_RXE2E_ERR_INJECT_SBE_MBE_PSN_CACHE_TAG_ERR_INJ_MASK_MASK			0xFFull
#define FXR_RXE2E_ERR_INJECT_SBE_MBE_PSN_CACHE_TAG_ERR_INJ_MASK_SMASK			0x3FC00000ull
#define FXR_RXE2E_ERR_INJECT_SBE_MBE_MC1_INPUT_FIFO_ERR_INJ_ENABLE_SHIFT		21
#define FXR_RXE2E_ERR_INJECT_SBE_MBE_MC1_INPUT_FIFO_ERR_INJ_ENABLE_MASK			0x1ull
#define FXR_RXE2E_ERR_INJECT_SBE_MBE_MC1_INPUT_FIFO_ERR_INJ_ENABLE_SMASK		0x200000ull
#define FXR_RXE2E_ERR_INJECT_SBE_MBE_MC1_INPUT_FIFO_ERR_INJ_DOMAIN_SHIFT		19
#define FXR_RXE2E_ERR_INJECT_SBE_MBE_MC1_INPUT_FIFO_ERR_INJ_DOMAIN_MASK			0x3ull
#define FXR_RXE2E_ERR_INJECT_SBE_MBE_MC1_INPUT_FIFO_ERR_INJ_DOMAIN_SMASK		0x180000ull
#define FXR_RXE2E_ERR_INJECT_SBE_MBE_MC1_INPUT_FIFO_ERR_INJ_MASK_SHIFT			11
#define FXR_RXE2E_ERR_INJECT_SBE_MBE_MC1_INPUT_FIFO_ERR_INJ_MASK_MASK			0xFFull
#define FXR_RXE2E_ERR_INJECT_SBE_MBE_MC1_INPUT_FIFO_ERR_INJ_MASK_SMASK			0x7F800ull
#define FXR_RXE2E_ERR_INJECT_SBE_MBE_MC0_INPUT_FIFO_ERR_INJ_ENABLE_SHIFT		10
#define FXR_RXE2E_ERR_INJECT_SBE_MBE_MC0_INPUT_FIFO_ERR_INJ_ENABLE_MASK			0x1ull
#define FXR_RXE2E_ERR_INJECT_SBE_MBE_MC0_INPUT_FIFO_ERR_INJ_ENABLE_SMASK		0x400ull
#define FXR_RXE2E_ERR_INJECT_SBE_MBE_MC0_INPUT_FIFO_ERR_INJ_DOMAIN_SHIFT		8
#define FXR_RXE2E_ERR_INJECT_SBE_MBE_MC0_INPUT_FIFO_ERR_INJ_DOMAIN_MASK			0x3ull
#define FXR_RXE2E_ERR_INJECT_SBE_MBE_MC0_INPUT_FIFO_ERR_INJ_DOMAIN_SMASK		0x300ull
#define FXR_RXE2E_ERR_INJECT_SBE_MBE_MC0_INPUT_FIFO_ERR_INJ_MASK_SHIFT			0
#define FXR_RXE2E_ERR_INJECT_SBE_MBE_MC0_INPUT_FIFO_ERR_INJ_MASK_MASK			0xFFull
#define FXR_RXE2E_ERR_INJECT_SBE_MBE_MC0_INPUT_FIFO_ERR_INJ_MASK_SMASK			0xFFull
/*
* Table #41 of fxr_top - RXE2E_DBG_PSN_CACHE_TAG_WAY_ENABLE
* These bits enable the 16 PSN Cache Tag Ways for filling and evicting. Set bits 
* to 0 to remove them from being an evict or fill candidate. For example, 
* setting to 16'h3 will only enable ways 1 and 0. This will stress the cache 
* causing more evicts and fills. This can be useful for testing the cache. Every 
* bit cleared will decrease the cache capacity by 1/16th. Any valid cache 
* entries that are in a disabled way will be invisible so another request for 
* that entry will result in a fill from memory, with possibly stale data, to one 
* of the enabled ways.
*/
#define FXR_RXE2E_DBG_PSN_CACHE_TAG_WAY_ENABLE						(FXR_RX_E2E_CSRS + 0x000000000500)
#define FXR_RXE2E_DBG_PSN_CACHE_TAG_WAY_ENABLE_RESETCSR					0x000000000000FFFFull
#define FXR_RXE2E_DBG_PSN_CACHE_TAG_WAY_ENABLE_WAY_ENABLE_SHIFT				0
#define FXR_RXE2E_DBG_PSN_CACHE_TAG_WAY_ENABLE_WAY_ENABLE_MASK				0xFFFFull
#define FXR_RXE2E_DBG_PSN_CACHE_TAG_WAY_ENABLE_WAY_ENABLE_SMASK				0xFFFFull
/*
* Table #42 of fxr_top - RXE2E_DBG_BIG_SCOREBOARD_ACCESS_ADDR
* This is an RXE2E debug CSR. It allows indirect access to the Big Scoreboard. 
* This can not be written to during normal operation. This register is for debug 
* use only.  The data for the read or write to the big scoreboard  is contained 
* in#%%#RXE2E_DBG_BIG_SCOREBOARD_ACCESS_DATA#%%#. E2E logic will generate the 
* ecc for writes. For writes, write #%%#RXE2E_DBG_BIG_SCOREBOARD_ACCESS_DATA#%%# 
* before writing this register. For reads,
*/
#define FXR_RXE2E_DBG_BIG_SCOREBOARD_ACCESS_ADDR					(FXR_RX_E2E_CSRS + 0x000000000508)
#define FXR_RXE2E_DBG_BIG_SCOREBOARD_ACCESS_ADDR_RESETCSR				0x0000000000000000ull
#define FXR_RXE2E_DBG_BIG_SCOREBOARD_ACCESS_ADDR_BUSY_SHIFT				63
#define FXR_RXE2E_DBG_BIG_SCOREBOARD_ACCESS_ADDR_BUSY_MASK				0x1ull
#define FXR_RXE2E_DBG_BIG_SCOREBOARD_ACCESS_ADDR_BUSY_SMASK				0x8000000000000000ull
#define FXR_RXE2E_DBG_BIG_SCOREBOARD_ACCESS_ADDR_WRITE_SHIFT				62
#define FXR_RXE2E_DBG_BIG_SCOREBOARD_ACCESS_ADDR_WRITE_MASK				0x1ull
#define FXR_RXE2E_DBG_BIG_SCOREBOARD_ACCESS_ADDR_WRITE_SMASK				0x4000000000000000ull
#define FXR_RXE2E_DBG_BIG_SCOREBOARD_ACCESS_ADDR_ADDRESS_SHIFT				0
#define FXR_RXE2E_DBG_BIG_SCOREBOARD_ACCESS_ADDR_ADDRESS_MASK				0x3FFull
#define FXR_RXE2E_DBG_BIG_SCOREBOARD_ACCESS_ADDR_ADDRESS_SMASK				0x3FFull
/*
* Table #43 of fxr_top - RXE2E_DBG_BIG_SCOREBOARD_ACCESS_DATA
* This is an RXE2E debug CSR. It allows indirect access to the Big Scoreboard.  
* This register is for debug use only. Note that this register is 1023 bits 
* wide. This register is written before doing a write and read after doing a 
* read as defined by #%%#RXE2E_DBG_BIG_SCOREBOARD_ACCESS_ADDR#%%#. Note 
* big_data[15][63] is always read and written as 0 by E2E logic.
*/
#define FXR_RXE2E_DBG_BIG_SCOREBOARD_ACCESS_DATA					(FXR_RX_E2E_CSRS + 0x000000000600)
#define FXR_RXE2E_DBG_BIG_SCOREBOARD_ACCESS_DATA_RESETCSR				0x0000000000000000ull
#define FXR_RXE2E_DBG_BIG_SCOREBOARD_ACCESS_DATA_BIG_DATA_SHIFT				0
#define FXR_RXE2E_DBG_BIG_SCOREBOARD_ACCESS_DATA_BIG_DATA_MASK				0xFFFFFFFFFFFFFFFFull
#define FXR_RXE2E_DBG_BIG_SCOREBOARD_ACCESS_DATA_BIG_DATA_SMASK				0xFFFFFFFFFFFFFFFFull

#endif 		/* DEF_FXR_RX_E2E_SW_DEF */
