/*
* Autogenerated by i_csrs.pl on Wed May 18 23:05:55 2016
* 
* i_csrs.pl Version 1.5 last modified on Thursday 1/7/16 17:24:50.
*/

#ifndef DEF_FXR_FC_SW_STRUCT_DEFS
#define DEF_FXR_FC_SW_STRUCT_DEFS



#endif                 /* DEF_FXR_FC_SW_STRUCT_DEFS */
