/*
* Autogenerated by i_csrs.pl on Thu May 12 14:12:30 2016
* 
* i_csrs.pl Version 1.5 last modified on Thursday 1/7/16 17:24:50.
*/

#ifndef DEF_MNH_MISC_SW_STRUCT_DEFS
#define DEF_MNH_MISC_SW_STRUCT_DEFS



#endif                 /* DEF_MNH_MISC_SW_STRUCT_DEFS */
