//                                                                             
// File:       fxr_loca_csrs.h                                                 
// Creator:    pvesvslx                                                        
// Time:       Friday Aug 1, 2014 [11:06:09 am]                                
//                                                                             
// Path:       /tmp/pvesvslx/nebulon_run/30229                                 
// Arguments:  /p/com/eda/denali/blueprint/3.7.4/Linux/blueprint -chdr -I      
//             /p/slx/eda/intel/nebulon/2.05_fdo/include -I                    
//             /p/slx/pvesv/fxr_autogen/fxr fxr_loca.rdl                       
//                                                                             
// Sources:    /tmp/pvesvslx/nebulon_run/30229/lib_udp.rdl                     
//             /tmp/pvesvslx/nebulon_run/30229/fxr_loca.rdl                    
//             /tmp/pvesvslx/nebulon_run/30229/fxr_loca.rdlh                   
//             /p/com/eda/intel/nebulon/2.05p1/generators/generator_common.pm  
//             /p/com/eda/intel/nebulon/2.05p1/generators/chdr.pm              
//                                                                             
// Blueprint:   3.7.4 (Tue Jun 23 00:17:01 PDT 2009)                           
// Machine:    scci56217                                                       
// OS:         Linux 2.6.16.60-0.58.1.3835.0.PTF.638363-smp                    
// Description:                                                                
//                                                                             
//LOCA Address Map                                                             
//                                                                             
// Copyright (C) 2014 Denali Software Inc.  All rights reserved                
// THIS FILE IS AUTOMATICALLY GENERATED BY DENALI BLUEPRINT, DO NOT EDIT       
//                                                                             



// LOCA_CONTROL desc:  The LOCA Control register enables selected modes and operations
// within the LOCA Block.
typedef volatile union {
    struct {
        uint64_t  CLEAN_EVICT_NOTIFY   :   1;    //  Clean Eviction Notification
                                                 // enable
        uint64_t  AGGRESSIVE_REFETCH   :   1;    //  Aggressive Refetch enable
        uint64_t  SO_PUT_OPTIMIZATION  :   1;    //  Strongly Ordered PUT
                                                 // optimization enable
        uint64_t  CACHE_DISABLE        :   1;    //  L1 Cache Disable
        uint64_t  reserved_63_4        :  60;    //  Reserved

    };
    uint64_t                         val;
} LOCA_CONTROL_t;

// --------------------------------------------------------------------------------------------------------------------------------

// starting the array instantiation section
typedef struct {
    LOCA_CONTROL_t             LOCA_CONTROL;     // offset 4'h0, width 64
} fxr_loca_csrs_t;                               // size:  4'h8
