/*
* -------------------------------------------------------------------
* --                      Intel Proprietary
* --              Copyright (C) 2014 Intel Corporation
* --                    All Rights Reserved
* -------------------------------------------------------------------
* --           Auto-generated by /p/slx/pvesv/wfr_autogen/utils/scripts/i_csrs/i_csrs.pl 
* --  i_csrs.pl Version 1.5 last modified on Tuesday 7/29/14 09:09:34
* --   /p/slx/pvesv/wfr_autogen/utils/scripts/i_csrs/i_csrs.pl -C -o /p/slx/pvesv/fxr_autogen/fxr /p/slx/pvesv/fxr_autogen/Fox_River/xml/300_Memory_Map.xml  
* --------------------------------------------------------------------
*/

#ifndef DEF_FXR_TOP_MAP_SW_DEF
#define DEF_FXR_TOP_MAP_SW_DEF

#define FXR_NUM_CONTEXTS		256
#define FXR_NUM_PIDS			4096
#define FXR_MAX_CONTEXT			255
#define FXR_TX_CONTEXT_ENTRIES		128
#define FXR_TX_CONTEXT_MAX		127
#define FXR_RX_CONTEXT_ENTRIES		16
#define FXR_RX_CONTEXT_MAX		15
#define FXR_NUM_SL			32
#define FXR_MAX_SL			31
#define FXR_TOP_MAP			0x000000000000
#define FXR_TX_CI_FAST			(FXR_TOP_MAP + 0x000000000000)
#define FXR_RX_CI_FAST			(FXR_TOP_MAP + 0x000000400000)
#define FXR_TX_CI			(FXR_TOP_MAP + 0x000001000000)
#define FXR_TX_OTR			(FXR_TOP_MAP + 0x000001400000)
#define FXR_TX_DMA			(FXR_TOP_MAP + 0x000001800000)
#define FXR_RX_CI			(FXR_TOP_MAP + 0x000002000000)
#define FXR_RX_HP			(FXR_TOP_MAP + 0x000002400000)
#define FXR_RX_E2E			(FXR_TOP_MAP + 0x000002800000)
#define FXR_HIFIS			(FXR_TOP_MAP + 0x000003000000)
#define FXR_LOCA			(FXR_TOP_MAP + 0x000003200000)
#define FXR_PCIM			(FXR_TOP_MAP + 0x000003400000)
#define FXR_PMON			(FXR_TOP_MAP + 0x000003500000)
#define FXR_SMA			(FXR_TOP_MAP + 0x000003600000)
#define FXR_LM			(FXR_TOP_MAP + 0x000003700000)
#define FXR_FC			(FXR_TOP_MAP + 0x000003800000)
#define FXR_MNH			(FXR_TOP_MAP + 0x000003880000)
#define FXR_AT			(FXR_TOP_MAP + 0x000004000000)
#define FXR_VNIC_WRAP		(FXR_TOP_MAP + 0x000005000000)

#endif 		/* DEF_FXR_TOP_MAP_SW_DEF */
