//                                                                             
// File:       fxr_tx_dma_csrs.h                                               
// Creator:    pvesvslx                                                        
// Time:       Friday Aug 1, 2014 [11:06:22 am]                                
//                                                                             
// Path:       /tmp/pvesvslx/nebulon_run/30229                                 
// Arguments:  /p/com/eda/denali/blueprint/3.7.4/Linux/blueprint -chdr -I      
//             /p/slx/eda/intel/nebulon/2.05_fdo/include -I                    
//             /p/slx/pvesv/fxr_autogen/fxr fxr_tx_dma.rdl                     
//                                                                             
// Sources:    /tmp/pvesvslx/nebulon_run/30229/lib_udp.rdl                     
//             /tmp/pvesvslx/nebulon_run/30229/fxr_tx_dma.rdlh                 
//             /tmp/pvesvslx/nebulon_run/30229/fxr_tx_dma.rdl                  
//             /p/com/eda/intel/nebulon/2.05p1/generators/generator_common.pm  
//             /p/com/eda/intel/nebulon/2.05p1/generators/chdr.pm              
//                                                                             
// Blueprint:   3.7.4 (Tue Jun 23 00:17:01 PDT 2009)                           
// Machine:    scci56217                                                       
// OS:         Linux 2.6.16.60-0.58.1.3835.0.PTF.638363-smp                    
// Description:                                                                
//                                                                             
//Transmit DMA address map                                                     
//                                                                             
// Copyright (C) 2014 Denali Software Inc.  All rights reserved                
// THIS FILE IS AUTOMATICALLY GENERATED BY DENALI BLUEPRINT, DO NOT EDIT       
//                                                                             



// TX_DMA_PKT_BUF_DBG desc:  Provides access to the TX DMA packet buffer for debug and diagnostic
// purposes. The packet buffer must not be written during normal system
// operation.
typedef volatile union {
    struct {
        uint64_t  PKT_BUF_DATA         :  64;    //  Packet buffer data.

    };
    uint64_t                         val;
} TX_DMA_PKT_BUF_DBG_t;

// --------------------------------------------------------------------------------------------------------------------------------

// FXR_TX_DMA_MAX_MTU desc:  This is an OTR CSR.
typedef volatile union {
    struct {
        uint64_t  MAX_MTU              :  14;    //  The maximum MTU (in bytes)
                                                 // allowed for a given SL.
        uint64_t  RSVD_0               :  50;    // Nebulon auto filled RSVD [63:14]

    };
    uint64_t                         val;
} FXR_TX_DMA_MAX_MTU_t;

// --------------------------------------------------------------------------------------------------------------------------------

// starting the array instantiation section
typedef struct {
    TX_DMA_PKT_BUF_DBG_t       TX_DMA_PKT_BUF_DBG[16384]; // offset 4'h0, width 64
    FXR_TX_DMA_MAX_MTU_t       FXR_TX_DMA_MAX_MTU[32]; // offset 20'h20000, width 64
} fxr_tx_dma_csrs_t;                             // size:  20'h20100
