/*
* Autogenerated by i_csrs.pl on Fri Aug  1 11:06:33 2014
* 
* i_csrs.pl Version 1.5 last modified on Tuesday 7/29/14 09:09:34.
*/

#ifndef DEF_FXR_RX_DMA_SW_STRUCT
#define DEF_FXR_RX_DMA_SW_STRUCT

/*
*  Structures and Unions from Tables
*/

#endif                 /* DEF_FXR_RX_DMA_SW_STRUCT */
