//                                                                             
// File:       fxr_hifis_csrs.h                                                
// Creator:    pvesvslx                                                        
// Time:       Friday Aug 1, 2014 [11:06:06 am]                                
//                                                                             
// Path:       /tmp/pvesvslx/nebulon_run/30229                                 
// Arguments:  /p/com/eda/denali/blueprint/3.7.4/Linux/blueprint -chdr -I      
//             /p/slx/eda/intel/nebulon/2.05_fdo/include -I                    
//             /p/slx/pvesv/fxr_autogen/fxr fxr_hifis.rdl                      
//                                                                             
// Sources:    /tmp/pvesvslx/nebulon_run/30229/fxr_hifis.rdlh                  
//             /tmp/pvesvslx/nebulon_run/30229/lib_udp.rdl                     
//             /tmp/pvesvslx/nebulon_run/30229/fxr_hifis.rdl                   
//             /p/com/eda/intel/nebulon/2.05p1/generators/generator_common.pm  
//             /p/com/eda/intel/nebulon/2.05p1/generators/chdr.pm              
//                                                                             
// Blueprint:   3.7.4 (Tue Jun 23 00:17:01 PDT 2009)                           
// Machine:    scci56217                                                       
// OS:         Linux 2.6.16.60-0.58.1.3835.0.PTF.638363-smp                    
// Description:                                                                
//                                                                             
//HI-FI Shim Address MAP                                                       
//                                                                             
// Copyright (C) 2014 Denali Software Inc.  All rights reserved                
// THIS FILE IS AUTOMATICALLY GENERATED BY DENALI BLUEPRINT, DO NOT EDIT       
//                                                                             



// HIFISCONTROL desc:  The HIFIS Control register enables selected modes and operations
// within the HIFIS Block.
typedef volatile union {
    struct {
        uint64_t  PCIM_REQ_THRESH      :   4;    //  PCIM Request Buffer
                                                 // Threshold. When PCIM request
                                                 // buffer entry count is greater
                                                 // than PCIM_REQ_THRESH value,
                                                 // flow control is asserted to
                                                 // the PCIM block.
        uint64_t  LOCA_RSP_THRESH      :   4;    //  LOCA Response Buffer
                                                 // Threshold. When LOCA response
                                                 // buffer entry count is greater
                                                 // than the LOCA_RSP_THREH value,
                                                 // flow control is asserted to
                                                 // the LOCA bloc.
        uint64_t  reserved_63_8        :  56;    //  Reserved

    };
    uint64_t                         val;
} HIFISCONTROL_t;

// --------------------------------------------------------------------------------------------------------------------------------

// starting the array instantiation section
typedef struct {
    HIFISCONTROL_t             HIFISCONTROL;     // offset 8'h50, width 64
} fxr_hifis_csrs_t;                              // size:  8'h58
