/*
* Autogenerated by i_csrs.pl on Wed May  7 12:01:29 2014
* 
* i_csrs.pl Version 1.5 last modified on Wednesday 5/7/14 07:25:46.
*/

#ifndef DEF_WFR_MISC_SW_STRUCT
#define DEF_WFR_MISC_SW_STRUCT

/*
*  Stuctures and Unions from Tables
*/

#endif                 /* DEF_WFR_MISC_SW_STRUCT */
